
(INCLUDE |ai:ken;declar >|) 
(DEFCOMMENT MOVIE) 
(DEFINE-FORM (ERASE+DRAW-FRAME PREVIOUS-FRAME CURRENT-FRAME SPEED LAST-RUNTIME) (ERASERDOWN) 
(AND PREVIOUS-FRAME (RUN-FRAME (SET-MINUS PREVIOUS-FRAME CURRENT-FRAME) -999.9 LAST-RUNTIME 
(QUOTE (ERASE)))) (PENDOWN) (RUN-FRAME (SET-MINUS CURRENT-FRAME PREVIOUS-FRAME) SPEED 
LAST-RUNTIME (QUOTE (DISPLAY)))) 
(DEFINE-FORM (PUT-IN-WHOLINE X) (SSTATUS WHO3 (APPEND-ATOMS (QUOTE F=) X)) X) 
(DEFINE-FORM (PRINT-THE-MOVIE-ARRAY FRAMES MOVIE-NAME FRAME-NUMBER FILE-OBJECT) (PRINT (CONS 
(QUOTE ARRAY) (CONS MOVIE-NAME (CONS (QUOTE T) (CONS FRAME-NUMBER NIL)))) FILE-OBJECT) 
(PRINT (CONS (QUOTE FILLARRAY) (CONS (CONS (QUOTE QUOTE) (CONS MOVIE-NAME NIL)) (CONS (CONS 
(QUOTE QUOTE) (CONS (NREVERSE FRAMES) NIL)) NIL))) FILE-OBJECT) (PRINT (CONS (QUOTE COND) 
(CONS (CONS (QUOTE (BOUNDP (QUOTE :COMPILED-MOVIES))) (CONS (CONS (QUOTE SETQ) (CONS (QUOTE 
:COMPILED-MOVIES) (CONS (CONS (QUOTE CONS) (CONS (CONS (QUOTE QUOTE) (CONS MOVIE-NAME NIL)) 
(QUOTE (:COMPILED-MOVIES)))) NIL))) NIL)) (CONS (CONS (QUOTE T) (CONS (CONS (QUOTE SETQ) 
(CONS (QUOTE :COMPILED-MOVIES) (CONS (CONS (QUOTE QUOTE) (CONS (CONS MOVIE-NAME NIL) NIL)) 
NIL))) NIL)) NIL))) FILE-OBJECT)) 
(DEFINE-SYNONYM EOF EVAL-ON-FRAME) 
(DEFINE-FORM (SHOW-MOVIE FIRST-FRAME LAST-FRAME SKIP-EVERY) (COND ((LET ((:MESSAGE (QUOTE 
(RECALL YOUR COMPILED?)))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR COMPILED?)|) (QUOTE 
MOVIE))) (PROJECT-COMPILED-MOVIE (NAME-OF :SELF) FIRST-FRAME (MIN LAST-FRAME (1- (LET 
((:MESSAGE (QUOTE (RECALL YOUR FRAME-COUNT)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR FRAME-COUNT)|) (QUOTE MOVIE))))) SKIP-EVERY (LET ((:MESSAGE (QUOTE 
(RECALL YOUR SPEED)))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR SPEED)|) (QUOTE MOVIE))) (LET 
((:MESSAGE (QUOTE (RECALL YOUR NEW-FRAME-ACTION)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR NEW-FRAME-ACTION)|) (QUOTE MOVIE))))) (T (SHOW-NORMAL-MOVIE FIRST-FRAME 
LAST-FRAME SKIP-EVERY)))) 
(DEFINE-FORM (SHOW-NORMAL-MOVIE FIRST-FRAME LAST-FRAME SKIP-EVERY) (WIPE) (LET ((INCREMENT 
(COND ((< FIRST-FRAME LAST-FRAME) SKIP-EVERY) (T (- SKIP-EVERY))))) (DO ((FRAME-NUMBER 
FIRST-FRAME (+ FRAME-NUMBER INCREMENT)) (LAST-RUNTIME (RUNTIME) (RUNTIME)) (BEGIN-TIME 
(RUNTIME)) (SPEED (//$ (FLOAT (LET ((:MESSAGE (QUOTE (RECALL YOUR SPEED)))) (COMPILED-ASK 
(QUOTE |MOVIE(RECALL YOUR SPEED)|) (QUOTE MOVIE)))))) (NEW-FRAME-ACTION (LET ((:MESSAGE 
(QUOTE (RECALL YOUR NEW-FRAME-ACTION)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR NEW-FRAME-ACTION)|) (QUOTE MOVIE)))) (LAST-FRAME (MIN LAST-FRAME (LET 
((:MESSAGE (QUOTE (RECALL YOUR FRAME-COUNT)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR FRAME-COUNT)|) (QUOTE MOVIE))))) (FRAME NIL (LET ((:MESSAGE (CONS (QUOTE 
RECALL) (CONS (QUOTE YOUR) (CONS (CONS (QUOTE FRAME) (CONS FRAME-NUMBER NIL)) NIL))))) 
(COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR (FRAME ?))|) (QUOTE MOVIE)))) (PREVIOUS-FRAME NIL 
FRAME)) ((COND ((> INCREMENT 0) (> FRAME-NUMBER LAST-FRAME)) (T (< FRAME-NUMBER 
LAST-FRAME))) (CONS (//$ (FLOAT (- (RUNTIME) BEGIN-TIME)) 1000000.0) (QUOTE (CPU SECONDS)))) 
(PUT-IN-WHOLINE FRAME-NUMBER) (COND ((NULL FRAME)) ((EQ NEW-FRAME-ACTION (QUOTE ERASE-OLD)) 
(ERASE+DRAW-FRAME PREVIOUS-FRAME FRAME SPEED LAST-RUNTIME)) ((EQ (FIRST NEW-FRAME-ACTION) 
(QUOTE ERASE-PREVIOUS)) (ERASE+DRAW-FRAME (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE 
YOUR) (CONS (CONS (QUOTE FRAME) (CONS (- FRAME-NUMBER (SECOND NEW-FRAME-ACTION)) NIL)) 
NIL))))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR (FRAME ?))|) (QUOTE MOVIE))) FRAME SPEED 
LAST-RUNTIME)) (T (EVAL NEW-FRAME-ACTION) (RUN-FRAME FRAME SPEED LAST-RUNTIME (QUOTE 
(DISPLAY)))))))) 
(DEFINE-FORM (RUN-FRAME CURRENT-APPEARANCES SPEED LAST-RUNTIME ACTION) (MAPC (FUNCTION 
(LAMBDA (CURRENT-APPEARANCE) (AND CURRENT-APPEARANCE (ASK1 (ACTOR-OF CURRENT-APPEARANCE) 
ACTION NIL)))) CURRENT-APPEARANCES) (SLEEP (-$ SPEED (//$ (FLOAT (- (RUNTIME) LAST-RUNTIME)) 
1000000.0)))) 
(DEFINE-FORM (COMPILE-APPEARANCE APPEARANCE APPEARANCE-NAME FILE-OBJECT) (LET ((:SELF 
(ACTOR-OF (QUOTE TURTLE-COMMAND-HOLDER))) (:MESSAGE (QUOTE (SET YOUR TURTLE-COMMANDS TO 
NIL)))) (COMPILED-ASK (QUOTE |TURTLE-COMMAND-HOLDER(SET YOUR TURTLE-COMMANDS TO NIL)|) 
(QUOTE TURTLE-COMMAND-HOLDER))) (LET ((:SELF (ACTOR-OF APPEARANCE)) (:MESSAGE (QUOTE 
(DISPLAY)))) (COMPILED-ASK (QUOTE |OBJECT(DISPLAY)|) (QUOTE OBJECT))) (LET ((DISPLAY-CODE 
(LET ((:SELF (ACTOR-OF (QUOTE TURTLE-COMMAND-HOLDER))) (:MESSAGE (QUOTE (RECALL YOUR 
TURTLE-COMMANDS)))) (COMPILED-ASK (QUOTE 
|TURTLE-COMMAND-HOLDER(RECALL YOUR TURTLE-COMMANDS)|) (QUOTE TURTLE-COMMAND-HOLDER))))) (LET 
((:SELF (ACTOR-OF (QUOTE TURTLE-COMMAND-HOLDER))) (:MESSAGE (QUOTE (SET YOUR TURTLE-COMMANDS 
TO NIL)))) (COMPILED-ASK (QUOTE |TURTLE-COMMAND-HOLDER(SET YOUR TURTLE-COMMANDS TO NIL)|) 
(QUOTE TURTLE-COMMAND-HOLDER))) (LET ((:SELF (ACTOR-OF APPEARANCE)) (:MESSAGE (QUOTE 
(ERASE)))) (COMPILED-ASK (QUOTE |OBJECT(ERASE)|) (QUOTE OBJECT))) (LET ((ERASE-CODE (LET 
((:SELF (ACTOR-OF (QUOTE TURTLE-COMMAND-HOLDER))) (:MESSAGE (QUOTE (RECALL YOUR 
TURTLE-COMMANDS)))) (COMPILED-ASK (QUOTE 
|TURTLE-COMMAND-HOLDER(RECALL YOUR TURTLE-COMMANDS)|) (QUOTE TURTLE-COMMAND-HOLDER))))) 
(COND ((AND (ONE-LONG DISPLAY-CODE) (ONE-LONG ERASE-CODE) (EQUAL (REST (REST (FIRST 
DISPLAY-CODE))) (REST (REST (FIRST ERASE-CODE))))) (PRINT (CONS (QUOTE DEFUN) (CONS 
APPEARANCE-NAME (CONS (QUOTE (PENMODE)) (CONS (QUOTE (FUNCALL PENMODE)) (REST (REST (FIRST 
DISPLAY-CODE))))))) FILE-OBJECT)) (T (PRINT (CONS (QUOTE DEFUN) (CONS APPEARANCE-NAME (CONS 
(QUOTE (PENMODE)) (CONS (CONS (QUOTE COND) (CONS (CONS (QUOTE (EQUAL PENMODE (QUOTE 
PENDOWN))) (NREVERSE DISPLAY-CODE)) (CONS (CONS (QUOTE (EQUAL PENMODE (QUOTE ERASERDOWN))) 
(NREVERSE ERASE-CODE)) (QUOTE ((T (COMPILED-APPEARANCE-ERROR PENMODE))))))) NIL)))) 
FILE-OBJECT)))))) 
(DEFINE-FORM (SAVE-COPY-OF-THE-MOVIE MOVIE FILE-NAME) (LET ((COMPILE-COPY (LET ((:SELF 
(ACTOR-OF MOVIE)) (:MESSAGE (CONS (QUOTE MAKE) (CONS (QUOTE COPY) (CONS (CONS (QUOTE 
TO-BE-COMPILED) (CONS (NAME-OF MOVIE) NIL)) NIL))))) (COMPILED-ASK (QUOTE 
|MOVIE(MAKE COPY (TO-BE-COMPILED ?))|) (QUOTE MOVIE))))) (LET ((:SELF (ACTOR-OF 
COMPILE-COPY)) (:MESSAGE (QUOTE (FORGET YOUR (FRAME ?))))) (COMPILED-ASK (QUOTE 
|MOVIE(FORGET YOUR (FRAME ?))|) (QUOTE MOVIE))) (LET ((:SELF (ACTOR-OF COMPILE-COPY)) 
(:MESSAGE (QUOTE (SET YOUR COMPILED? TO SHOULD-BE)))) (COMPILED-ASK (QUOTE 
|MOVIE(SET YOUR COMPILED? TO SHOULD-BE)|) (QUOTE MOVIE))) (LET ((:SELF (ACTOR-OF 
COMPILE-COPY)) (:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE NAME) (CONS 
(QUOTE TO) (CONS (NAME-OF MOVIE) NIL))))))) (COMPILED-ASK (QUOTE |MOVIE(SET YOUR NAME TO ?)|) 
(QUOTE MOVIE))) (LET ((:SELF (ACTOR-OF COMPILE-COPY)) (:MESSAGE (CONS (QUOTE SAVE) 
FILE-NAME))) (COMPILED-ASK (QUOTE |MOVIE(SAVE %)|) (QUOTE MOVIE))) (LET ((:SELF (ACTOR-OF 
COMPILE-COPY)) (:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE NAME) (CONS 
(QUOTE TO) (CONS COMPILE-COPY NIL))))))) (COMPILED-ASK (QUOTE |MOVIE(SET YOUR NAME TO ?)|) 
(QUOTE MOVIE))) (LET ((:SELF (ACTOR-OF COMPILE-COPY)) (:MESSAGE (QUOTE (UNMAKE)))) 
(COMPILED-ASK (QUOTE |MOVIE(UNMAKE)|) (QUOTE MOVIE))))) 
(DEFINE-FORM (EVAL-ON-FRAME MOVIE FORM FRAME-NUMBER) (LET ((FRAME-HANDLER (LET ((:SELF 
(ACTOR-OF MOVIE)) (:MESSAGE (QUOTE (RECALL YOUR NEW-FRAME-HANDLER)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR NEW-FRAME-HANDLER)|) (QUOTE MOVIE))))) (COND (FRAME-HANDLER (ASK1 
(ACTOR-OF FRAME-HANDLER) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS 
(CONS (QUOTE JUST) (CONS (QUOTE MADE) (CONS (QUOTE FRAME) (CONS (QUOTE NUMBER) (CONS 
FRAME-NUMBER (QUOTE (FOR ?MOVIE))))))) (CONS FORM (CONS (CONS (QUOTE COMPILE-USING) (CONS 
(QUOTE FRAME-HANDLER) (CONS (CONS (QUOTE ASK-OLD) (CONS (QUOTE :SELF) (CONS (QUOTE JUST) 
(CONS (QUOTE MADE) (CONS (QUOTE FRAME) (CONS (QUOTE NUMBER) (CONS FRAME-NUMBER (CONS (QUOTE 
FOR) (CONS MOVIE NIL))))))))) NIL))) NIL)))))) NIL)) (T (WARNING (QUOTE EVAL-ON-FRAME) (CONS 
MOVIE (QUOTE (IS NOT A MOVIE)))))))) 
(DECLARE (SPECIAL MOVIE-RECALL-1 MOVIE-RECALL-2 MOVIE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
MOVIE-FILM-4 MOVIE-FILM-5 MOVIE-STORE-6 MOVIE-STOP-7 MOVIE-RECORD-8 MOVIE-PROJECT-9 
MOVIE-PROJECT-10 MOVIE-PROJECT-11 MOVIE-PROJECT-12 MOVIE-PROJECT-13 MOVIE-PROJECT-14 
MOVIE-PRINT-15 MOVIE-SMART-16)) 
(SETQ MOVIE-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SOMETHING))) 
(DEFPROP MOVIE-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ MOVIE-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE MOVIE))) 
(DEFPROP MOVIE-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ MOVIE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE (NIL 
(SPEED . 999999) (TICKS-PER-FRAME . 1) (FRAMES-PER-SECOND . 1) (NEW-FRAME-ACTION . 
ERASE-OLD) (NEW-FRAME-HANDLER . FRAME-HANDLER) (SCREEN-MODE . SILENT) (FRAME-COUNT . 0))))) 
(DEFPROP MOVIE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) 
METHOD-PATTERN) 
(DEFPROP MOVIE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ MOVIE-FILM-4 (QUOTE MOVIE-FILM-4)) 
(DEFPROP MOVIE-FILM-4 (FILM THE NEXT ? TICKS) METHOD-PATTERN) 
(DEFUN MOVIE-FILM-4 NIL ((LAMBDA (LENGTH) (LET ((:SELF (ACTOR-OF (QUOTE MOVIE))) (:MESSAGE 
(CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE CURRENT-MOVIE) (CONS (QUOTE TO) (CONS 
(NAME-OF :SELF) NIL))))))) (COMPILED-ASK (QUOTE |MOVIE(SET YOUR CURRENT-MOVIE TO ?)|) (QUOTE 
MOVIE))) (LET ((SCREEN-MODE (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (RECALL 
YOUR MODE)))) (COMPILED-ASK (QUOTE |SCREEN(RECALL YOUR MODE)|) (QUOTE SCREEN))))) 
(UNWIND-PROTECT (PROGN (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (CONS (QUOTE SET) 
(CONS (QUOTE YOUR) (CONS (QUOTE MODE) (CONS (QUOTE TO) (CONS (LET ((:MESSAGE (QUOTE (RECALL 
YOUR SCREEN-MODE)))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR SCREEN-MODE)|) (QUOTE MOVIE))) 
NIL))))))) (COMPILED-ASK (QUOTE |SCREEN(SET YOUR MODE TO ?)|) (QUOTE SCREEN))) (DO ((TIME 0 
(1+ TIME)) (FRAME-NUMBER (LET ((:MESSAGE (QUOTE (RECALL YOUR FRAME-COUNT)))) (COMPILED-ASK 
(QUOTE |MOVIE(RECALL YOUR FRAME-COUNT)|) (QUOTE MOVIE)))) (UNIVERSE (LET ((:MESSAGE (QUOTE 
(RECALL YOUR UNIVERSE)))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR UNIVERSE)|) (QUOTE 
MOVIE)))) (NEW-FRAME-HANDLER (LET ((:MESSAGE (QUOTE (RECALL YOUR NEW-FRAME-HANDLER)))) 
(COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR NEW-FRAME-HANDLER)|) (QUOTE MOVIE)))) 
(:TICKS-PER-FRAME (LET ((:MESSAGE (QUOTE (RECALL YOUR TICKS-PER-FRAME)))) (COMPILED-ASK 
(QUOTE |MOVIE(RECALL YOUR TICKS-PER-FRAME)|) (QUOTE MOVIE)))) (:FRAMES-PER-SECOND (LET 
((:MESSAGE (QUOTE (RECALL YOUR FRAMES-PER-SECOND)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR FRAMES-PER-SECOND)|) (QUOTE MOVIE)))) (STOPPED? NIL (LET ((:MESSAGE 
(QUOTE (RECALL YOUR STOPPED?)))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR STOPPED?)|) (QUOTE 
MOVIE))))) ((OR STOPPED? (> TIME LENGTH) (NULL (LET ((:SELF (ACTOR-OF UNIVERSE)) (:MESSAGE 
(QUOTE (RECALL YOUR ACTORS-TO-RUN-NEXT)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR ACTORS-TO-RUN-NEXT)|) (QUOTE MOVIE))))) FRAME-NUMBER) (COND ((= (\ TIME 
:TICKS-PER-FRAME) 0) (PUT-IN-WHOLINE FRAME-NUMBER) (LET ((:SELF (ACTOR-OF 
NEW-FRAME-HANDLER)) (:MESSAGE (CONS (QUOTE JUST) (CONS (QUOTE MADE) (CONS (QUOTE FRAME) 
(CONS (QUOTE NUMBER) (CONS FRAME-NUMBER (CONS (QUOTE FOR) (CONS :SELF NIL))))))))) 
(COMPILED-ASK (QUOTE |FRAME-HANDLER(JUST MADE FRAME NUMBER ? FOR ?)|) (QUOTE 
FRAME-HANDLER))) (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE 
FRAME-COUNT) (CONS (QUOTE TO) (CONS FRAME-NUMBER NIL))))))) (COMPILED-ASK (QUOTE 
|MOVIE(SET YOUR FRAME-COUNT TO ?)|) (QUOTE MOVIE))) (SETQ FRAME-NUMBER (1+ FRAME-NUMBER)))) 
(LET ((:SELF (ACTOR-OF UNIVERSE)) (:MESSAGE (QUOTE (TICK)))) (COMPILED-ASK (QUOTE 
|UNIVERSE(TICK)|) (QUOTE UNIVERSE))))) (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE 
(CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE MODE) (CONS (QUOTE TO) (CONS SCREEN-MODE 
NIL))))))) (COMPILED-ASK (QUOTE |SCREEN(SET YOUR MODE TO ?)|) (QUOTE SCREEN)))))) (CADDDR 
:MESSAGE))) 
(SETQ MOVIE-FILM-5 (QUOTE MOVIE-FILM-5)) 
(DEFPROP MOVIE-FILM-5 (FILM SECRETLY THE NEXT ? TICKS) METHOD-PATTERN) 
(DEFUN MOVIE-FILM-5 NIL ((LAMBDA (LENGTH) (LET ((:MESSAGE (QUOTE (SET YOUR NEW-FRAME-HANDLER 
TO JUST-STORE-AWAY-FRAME)))) (COMPILED-ASK (QUOTE 
|MOVIE(SET YOUR NEW-FRAME-HANDLER TO JUST-STORE-AWAY-FRAME)|) (QUOTE MOVIE))) (LET 
((:MESSAGE (CONS (QUOTE FILM) (CONS (QUOTE THE) (CONS (QUOTE NEXT) (CONS LENGTH (QUOTE 
(TICKS)))))))) (COMPILED-ASK (QUOTE |MOVIE(FILM THE NEXT ? TICKS)|) (QUOTE MOVIE)))) (FIRST 
(CDDDDR :MESSAGE)))) 
(SETQ MOVIE-STORE-6 (QUOTE MOVIE-STORE-6)) 
(DEFPROP MOVIE-STORE-6 (STORE AWAY THE FRAME NUMBER ?) METHOD-PATTERN) 
(DEFUN MOVIE-STORE-6 NIL ((LAMBDA (NUMBER) (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE 
YOUR) (CONS (CONS (QUOTE FRAME) (CONS NUMBER NIL)) (CONS (QUOTE TO) (CONS (OR (LET ((:SELF 
(ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (SAVE SCREEN)))) (COMPILED-ASK (QUOTE 
|SCREEN(SAVE SCREEN)|) (QUOTE SCREEN))) (QUOTE (NIL))) NIL))))))) (COMPILED-ASK (QUOTE 
|MOVIE(SET YOUR (FRAME ?) TO ?)|) (QUOTE MOVIE)))) (CADR (CDDDDR :MESSAGE)))) 
(SETQ MOVIE-STOP-7 (QUOTE MOVIE-STOP-7)) 
(DEFPROP MOVIE-STOP-7 (STOP FILMING) METHOD-PATTERN) 
(DEFUN MOVIE-STOP-7 NIL (LET ((:MESSAGE (QUOTE (SET YOUR STOPPED? TO T)))) (COMPILED-ASK 
(QUOTE |MOVIE(SET YOUR STOPPED? TO T)|) (QUOTE MOVIE)))) 
(SETQ MOVIE-RECORD-8 (QUOTE MOVIE-RECORD-8)) 
(DEFPROP MOVIE-RECORD-8 (RECORD ?) METHOD-PATTERN) 
(DEFUN MOVIE-RECORD-8 NIL ((LAMBDA (EVENT) (LET ((:MESSAGE (CONS (QUOTE MEMORIZE) (CONS 
(CONS (QUOTE HAPPENED) (CONS EVENT (CONS (QUOTE AT) (CONS (QUOTE FRAME) (CONS (LET 
((:MESSAGE (QUOTE (RECALL YOUR FRAME-COUNT)))) (COMPILED-ASK (QUOTE 
|MOVIE(RECALL YOUR FRAME-COUNT)|) (QUOTE MOVIE))) NIL))))) NIL)))) (COMPILED-ASK (QUOTE 
|MOVIE(MEMORIZE (HAPPENED ? AT FRAME ?))|) (QUOTE MOVIE)))) (CADR :MESSAGE))) 
(SETQ MOVIE-PROJECT-9 (QUOTE MOVIE-PROJECT-9)) 
(DEFPROP MOVIE-PROJECT-9 (PROJECT) METHOD-PATTERN) 
(DEFUN MOVIE-PROJECT-9 NIL (SHOW-MOVIE 0 999999999 1)) 
(SETQ MOVIE-PROJECT-10 (QUOTE MOVIE-PROJECT-10)) 
(DEFPROP MOVIE-PROJECT-10 (PROJECT FRAMES ? TO ? SHOWING EVERY ?) METHOD-PATTERN) 
(DEFUN MOVIE-PROJECT-10 NIL ((LAMBDA (SO-MANY END BEGIN) (SHOW-MOVIE BEGIN END SO-MANY)) 
(CADDDR (CDDDDR :MESSAGE)) (FIRST (CDDDDR :MESSAGE)) (CADDR :MESSAGE))) 
(SETQ MOVIE-PROJECT-11 (QUOTE MOVIE-PROJECT-11)) 
(DEFPROP MOVIE-PROJECT-11 (PROJECT FRAMES ? TO ?) METHOD-PATTERN) 
(DEFUN MOVIE-PROJECT-11 NIL ((LAMBDA (END BEGIN) (SHOW-MOVIE BEGIN END 1)) (FIRST (CDDDDR 
:MESSAGE)) (CADDR :MESSAGE))) 
(SETQ MOVIE-PROJECT-12 (QUOTE MOVIE-PROJECT-12)) 
(DEFPROP MOVIE-PROJECT-12 (PROJECT STARTING AT FRAME ? SHOWING EVERY ?) METHOD-PATTERN) 
(DEFUN MOVIE-PROJECT-12 NIL ((LAMBDA (SO-MANY BEGIN) (SHOW-MOVIE BEGIN 999999999 SO-MANY)) 
(CADDDR (CDDDDR :MESSAGE)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ MOVIE-PROJECT-13 (QUOTE MOVIE-PROJECT-13)) 
(DEFPROP MOVIE-PROJECT-13 (PROJECT SHOWING EVERY ?) METHOD-PATTERN) 
(DEFUN MOVIE-PROJECT-13 NIL ((LAMBDA (SO-MANY) (SHOW-MOVIE 0 999999999 SO-MANY)) (CADDDR 
:MESSAGE))) 
(SETQ MOVIE-PROJECT-14 (QUOTE MOVIE-PROJECT-14)) 
(DEFPROP MOVIE-PROJECT-14 (PROJECT FRAME ?) METHOD-PATTERN) 
(DEFUN MOVIE-PROJECT-14 NIL ((LAMBDA (NUMBER) (SHOW-MOVIE NUMBER NUMBER 999999999)) (CADDR 
:MESSAGE))) 
(SETQ MOVIE-PRINT-15 (QUOTE MOVIE-PRINT-15)) 
(DEFPROP MOVIE-PRINT-15 (PRINT FRAMES ? TO ?) METHOD-PATTERN) 
(DEFUN MOVIE-PRINT-15 NIL ((LAMBDA (END BEGIN) (DO ((I BEGIN (1+ I))) ((> I END)) (LET 
((:MESSAGE (CONS (QUOTE ASK) (CONS (QUOTE EACH) (CONS (QUOTE OF) (CONS (QUOTE YOUR) (CONS 
(CONS (QUOTE FRAME) (CONS I NIL)) (QUOTE (TO PRINT MEMORY))))))))) (COMPILED-ASK (QUOTE 
|MOVIE(ASK EACH OF YOUR (FRAME ?) TO PRINT MEMORY)|) (QUOTE MOVIE))) (TERPRI) (PRINC (QUOTE 
|End of frame number |)) (PRINC I))) (FIRST (CDDDDR :MESSAGE)) (CADDR :MESSAGE))) 
(SETQ MOVIE-SMART-16 (QUOTE MOVIE-SMART-16)) 
(DEFPROP MOVIE-SMART-16 (SMART COMPILE %) METHOD-PATTERN) 
(DEFUN MOVIE-SMART-16 NIL ((LAMBDA (FILE-NAME) (SAVE-COPY-OF-THE-MOVIE :SELF FILE-NAME) 
(LET-FILES ((FILE-OBJECT (OPEN FILE-NAME (QUOTE APPEND))) (MOVIE-NAME (LET ((NAME (NAME-OF 
:SELF))) (COND ((NULL NAME) (QUOTE UNNAMED-MOVIE)) ((ATOM NAME) NAME) (T (APPEND-ATOMS 
NAME))))) (ORIGINAL-MODE (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (RECALL 
YOUR MODE)))) (COMPILED-ASK (QUOTE |SCREEN(RECALL YOUR MODE)|) (QUOTE SCREEN))))) 
(UNWIND-PROTECT (PROGN (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (SET YOUR 
MODE TO (SILENT-BUT-TELL TURTLE-COMMAND-HOLDER))))) (COMPILED-ASK (QUOTE 
|SCREEN(SET YOUR MODE TO (SILENT-BUT-TELL TURTLE-COMMAND-HOLDER))|) (QUOTE SCREEN))) (DO 
((COMPILED-APPEARANCES NIL) (FRAMES NIL) (*NOPOINT NIL) (FRAME-COUNT (LET ((:MESSAGE (QUOTE 
(RECALL YOUR FRAME-COUNT)))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR FRAME-COUNT)|) (QUOTE 
MOVIE)))) (FRAME-NUMBER 0 (1+ FRAME-NUMBER))) ((= FRAME-NUMBER FRAME-COUNT) 
(PRINT-THE-MOVIE-ARRAY FRAMES MOVIE-NAME FRAME-NUMBER FILE-OBJECT)) (DO ((APPEARANCES (LET 
((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS (CONS (QUOTE FRAME) (CONS 
FRAME-NUMBER NIL)) NIL))))) (COMPILED-ASK (QUOTE |MOVIE(RECALL YOUR (FRAME ?))|) (QUOTE 
MOVIE))) (REST APPEARANCES)) (FRAME)) ((NULL APPEARANCES) (PUSH FRAME FRAMES)) (PUSH (COND 
((SECOND (ASSQ (FIRST APPEARANCES) COMPILED-APPEARANCES))) (T (LET ((APPEARANCE-NAME 
(INTERN-APPEND-ATOMS MOVIE-NAME (QUOTE -) (GEN-NUMBER MOVIE-NAME)))) (COMPILE-APPEARANCE 
(FIRST APPEARANCES) APPEARANCE-NAME FILE-OBJECT) (PUSH (LIST (FIRST APPEARANCES) 
APPEARANCE-NAME) COMPILED-APPEARANCES) APPEARANCE-NAME))) FRAME)))) (LET ((:SELF (ACTOR-OF 
(QUOTE SCREEN))) (:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE MODE) (CONS 
(QUOTE TO) (CONS ORIGINAL-MODE NIL))))))) (COMPILED-ASK (QUOTE |SCREEN(SET YOUR MODE TO ?)|) 
(QUOTE SCREEN)))))) (CDDR :MESSAGE))) 
(DEFUN ORIGINAL-METHODS-OF-MOVIE (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE (QUOTE (RECALL 
YOUR NAME))) MOVIE-RECALL-2)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
MOVIE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (EQ (FIRST MESSAGE) (QUOTE FILM)) 
(COND ((AND (AND (EQ (CADR MESSAGE) (QUOTE THE)) (AND (EQ (CADDR MESSAGE) (QUOTE NEXT)) 
(EQUAL (CDDDDR MESSAGE) (QUOTE (TICKS))))) MOVIE-FILM-4)) ((AND (AND (EQ (CADR MESSAGE) 
(QUOTE SECRETLY)) (AND (EQ (CADDR MESSAGE) (QUOTE THE)) (AND (EQ (CADDDR MESSAGE) (QUOTE 
NEXT)) (EQUAL (REST (CDDDDR MESSAGE)) (QUOTE (TICKS)))))) MOVIE-FILM-5))))) ((AND (AND (EQ 
(FIRST MESSAGE) (QUOTE STORE)) (AND (EQ (CADR MESSAGE) (QUOTE AWAY)) (AND (EQ (CADDR 
MESSAGE) (QUOTE THE)) (AND (EQ (CADDDR MESSAGE) (QUOTE FRAME)) (AND (EQ (FIRST (CDDDDR 
MESSAGE)) (QUOTE NUMBER)) (ONE-LONG (REST (CDDDDR MESSAGE)))))))) MOVIE-STORE-6)) ((AND 
(EQUAL MESSAGE (QUOTE (STOP FILMING))) MOVIE-STOP-7)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE 
RECORD)) (ONE-LONG (REST MESSAGE))) MOVIE-RECORD-8)) ((AND (EQ (FIRST MESSAGE) (QUOTE 
PROJECT)) (COND ((AND (NULL (REST MESSAGE)) MOVIE-PROJECT-9)) ((AND (EQ (CADR MESSAGE) 
(QUOTE FRAMES)) (COND ((AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))) 
MOVIE-PROJECT-11) ((AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (AND (EQ (CADR (CDDDDR MESSAGE)) 
(QUOTE SHOWING)) (AND (EQ (CADDR (CDDDDR MESSAGE)) (QUOTE EVERY)) (ONE-LONG (CDDDR (CDDDDR 
MESSAGE)))))) MOVIE-PROJECT-10)))) ((AND (AND (EQ (CADR MESSAGE) (QUOTE STARTING)) (AND (EQ 
(CADDR MESSAGE) (QUOTE AT)) (AND (EQ (CADDDR MESSAGE) (QUOTE FRAME)) (AND (EQ (CADR (CDDDDR 
MESSAGE)) (QUOTE SHOWING)) (AND (EQ (CADDR (CDDDDR MESSAGE)) (QUOTE EVERY)) (ONE-LONG (CDDDR 
(CDDDDR MESSAGE)))))))) MOVIE-PROJECT-12)) ((AND (AND (EQ (CADR MESSAGE) (QUOTE SHOWING)) 
(AND (EQ (CADDR MESSAGE) (QUOTE EVERY)) (ONE-LONG (CDDDR MESSAGE)))) MOVIE-PROJECT-13)) 
((AND (AND (EQ (CADR MESSAGE) (QUOTE FRAME)) (ONE-LONG (CDDR MESSAGE))) 
MOVIE-PROJECT-14))))) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE PRINT)) (AND (EQ (CADR MESSAGE) 
(QUOTE FRAMES)) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))) 
MOVIE-PRINT-15)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE SMART)) (EQ (CADR MESSAGE) (QUOTE 
COMPILE))) MOVIE-SMART-16)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 16 MOVIE-RECALL-1 
(ORIGINAL-METHODS-OF-MOVIE MOVIE-RECALL-2 MOVIE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
MOVIE-FILM-4 MOVIE-FILM-5 MOVIE-STORE-6 MOVIE-STOP-7 MOVIE-RECORD-8 MOVIE-PROJECT-9 
MOVIE-PROJECT-10 MOVIE-PROJECT-11 MOVIE-PROJECT-12 MOVIE-PROJECT-13 MOVIE-PROJECT-14 
MOVIE-PRINT-15 MOVIE-SMART-16))) (QUOTE MOVIE)) 
(REMPROP (QUOTE MOVIE) (QUOTE ACTOR-LOAD)) 
(ASK SOMETHING ADD MOVIE TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL FRAME-HANDLER-RECALL-1 FRAME-HANDLER-SET-6 FRAME-HANDLER-RECALL-5 
FRAME-HANDLER-RECALL-2 FRAME-HANDLER-JUST-3 
FRAME-HANDLER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4)) 
(SETQ FRAME-HANDLER-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SOMETHING))) 
(DEFPROP FRAME-HANDLER-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ FRAME-HANDLER-SET-6 (QUOTE FRAME-HANDLER-SET-6)) 
(DEFPROP FRAME-HANDLER-SET-6 (SET YOUR OFFSPRING TO ?) METHOD-PATTERN) 
(DEFPROP FRAME-HANDLER-SET-6 T PRIVATE?) 
(DEFUN FRAME-HANDLER-SET-6 NIL ((LAMBDA (THE-NEW-VALUE) (SET-DIRECTOR-SYMBOL-FOR-VALUE 
FRAME-HANDLER-RECALL-5 THE-NEW-VALUE)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ FRAME-HANDLER-RECALL-5 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE (JUST-STORE-AWAY-FRAME)))) 
(DEFPROP FRAME-HANDLER-RECALL-5 (RECALL YOUR YOUR OFFSPRING) METHOD-PATTERN) 
(DEFPROP FRAME-HANDLER-RECALL-5 T PRIVATE?) 
(SETQ FRAME-HANDLER-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE FRAME-HANDLER))) 
(DEFPROP FRAME-HANDLER-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ FRAME-HANDLER-JUST-3 (QUOTE FRAME-HANDLER-JUST-3)) 
(DEFPROP FRAME-HANDLER-JUST-3 (JUST MADE FRAME NUMBER ? FOR ?) METHOD-PATTERN) 
(DEFUN FRAME-HANDLER-JUST-3 NIL ((LAMBDA (MOVIE FRAME-NUMBER) (LET ((ORIGINAL-MODE (LET 
((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (RECALL YOUR MODE)))) (COMPILED-ASK 
(QUOTE |SCREEN(RECALL YOUR MODE)|) (QUOTE SCREEN))))) (COND ((NOT (EQ ORIGINAL-MODE (QUOTE 
NORMAL))) (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (SET YOUR MODE TO 
NORMAL)))) (COMPILED-ASK (QUOTE |SCREEN(SET YOUR MODE TO NORMAL)|) (QUOTE SCREEN))) (LET 
((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE (WIPE)))) (COMPILED-ASK (QUOTE 
|SCREEN(WIPE)|) (QUOTE SCREEN))) (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (CONS 
(QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE MODE) (CONS (QUOTE TO) (CONS ORIGINAL-MODE 
NIL))))))) (COMPILED-ASK (QUOTE |SCREEN(SET YOUR MODE TO ?)|) (QUOTE SCREEN)))))) (LET 
((:SELF (ACTOR-OF MOVIE)) (:MESSAGE (CONS (QUOTE STORE) (CONS (QUOTE AWAY) (CONS (QUOTE THE) 
(CONS (QUOTE FRAME) (CONS (QUOTE NUMBER) (CONS FRAME-NUMBER NIL)))))))) (COMPILED-ASK (QUOTE 
|MOVIE(STORE AWAY THE FRAME NUMBER ?)|) (QUOTE MOVIE)))) (CADDR (CDDDDR :MESSAGE)) (FIRST 
(CDDDDR :MESSAGE)))) 
(SETQ FRAME-HANDLER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP FRAME-HANDLER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP FRAME-HANDLER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 T PRIVATE?) 
(DEFUN ORIGINAL-METHODS-OF-FRAME-HANDLER (MESSAGE ACTOR) (COND ((AND (AND (EQ (FIRST 
MESSAGE) (QUOTE SET)) (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADDR MESSAGE) (QUOTE 
OFFSPRING)) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))))) (AND (EQ 
ACTOR :SELF) FRAME-HANDLER-SET-6))) ((AND (EQ (FIRST MESSAGE) (QUOTE RECALL)) (AND (EQ (CADR 
MESSAGE) (QUOTE YOUR)) (COND ((AND (EQUAL (CDDR MESSAGE) (QUOTE (YOUR OFFSPRING))) (AND (EQ 
ACTOR :SELF) FRAME-HANDLER-RECALL-5))) ((AND (EQUAL (CDDR MESSAGE) (QUOTE (NAME))) 
FRAME-HANDLER-RECALL-2)))))) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE JUST)) (AND (EQ (CADR 
MESSAGE) (QUOTE MADE)) (AND (EQ (CADDR MESSAGE) (QUOTE FRAME)) (AND (EQ (CADDDR MESSAGE) 
(QUOTE NUMBER)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE FOR)) (ONE-LONG (CDDR (CDDDDR 
MESSAGE)))))))) FRAME-HANDLER-JUST-3)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
FRAME-HANDLER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4))))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 6 FRAME-HANDLER-RECALL-1 
(ORIGINAL-METHODS-OF-FRAME-HANDLER FRAME-HANDLER-SET-6 FRAME-HANDLER-RECALL-5 
FRAME-HANDLER-RECALL-2 FRAME-HANDLER-JUST-3 
FRAME-HANDLER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4))) (QUOTE FRAME-HANDLER)) 
(REMPROP (QUOTE FRAME-HANDLER) (QUOTE ACTOR-LOAD)) 
(ASK SOMETHING ADD FRAME-HANDLER TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL JUST-STORE-AWAY-FRAME-RECALL-1 
JUST-STORE-AWAY-FRAME-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 JUST-STORE-AWAY-FRAME-RECALL-2 
JUST-STORE-AWAY-FRAME-JUST-3)) 
(SETQ JUST-STORE-AWAY-FRAME-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE FRAME-HANDLER))) 
(DEFPROP JUST-STORE-AWAY-FRAME-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ JUST-STORE-AWAY-FRAME-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 (QUOTE 
(DIRECTOR-SYMBOL-FOR-VALUE (NIL)))) 
(DEFPROP JUST-STORE-AWAY-FRAME-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP JUST-STORE-AWAY-FRAME-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 T PRIVATE?) 
(SETQ JUST-STORE-AWAY-FRAME-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
JUST-STORE-AWAY-FRAME))) 
(DEFPROP JUST-STORE-AWAY-FRAME-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ JUST-STORE-AWAY-FRAME-JUST-3 (QUOTE JUST-STORE-AWAY-FRAME-JUST-3)) 
(DEFPROP JUST-STORE-AWAY-FRAME-JUST-3 (JUST MADE FRAME NUMBER ? FOR ?) METHOD-PATTERN) 
(DEFUN JUST-STORE-AWAY-FRAME-JUST-3 NIL ((LAMBDA (MOVIE FRAME-NUMBER) (LET ((:SELF (ACTOR-OF 
MOVIE)) (:MESSAGE (CONS (QUOTE STORE) (CONS (QUOTE AWAY) (CONS (QUOTE THE) (CONS (QUOTE 
FRAME) (CONS (QUOTE NUMBER) (CONS FRAME-NUMBER NIL)))))))) (COMPILED-ASK (QUOTE 
|MOVIE(STORE AWAY THE FRAME NUMBER ?)|) (QUOTE MOVIE)))) (CADDR (CDDDDR :MESSAGE)) (FIRST 
(CDDDDR :MESSAGE)))) 
(DEFUN ORIGINAL-METHODS-OF-JUST-STORE-AWAY-FRAME (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE 
(QUOTE (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
JUST-STORE-AWAY-FRAME-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4))) ((AND (EQUAL MESSAGE (QUOTE 
(RECALL YOUR NAME))) JUST-STORE-AWAY-FRAME-RECALL-2)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE 
JUST)) (AND (EQ (CADR MESSAGE) (QUOTE MADE)) (AND (EQ (CADDR MESSAGE) (QUOTE FRAME)) (AND 
(EQ (CADDDR MESSAGE) (QUOTE NUMBER)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE FOR)) (ONE-LONG 
(CDDR (CDDDDR MESSAGE)))))))) JUST-STORE-AWAY-FRAME-JUST-3)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 4 JUST-STORE-AWAY-FRAME-RECALL-1 
(ORIGINAL-METHODS-OF-JUST-STORE-AWAY-FRAME 
JUST-STORE-AWAY-FRAME-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-4 JUST-STORE-AWAY-FRAME-RECALL-2 
JUST-STORE-AWAY-FRAME-JUST-3))) (QUOTE JUST-STORE-AWAY-FRAME)) 
(REMPROP (QUOTE JUST-STORE-AWAY-FRAME) (QUOTE ACTOR-LOAD)) 
(ASK FRAME-HANDLER ADD JUST-STORE-AWAY-FRAME TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL TURTLE-COMMAND-HOLDER-RECALL-1 
TURTLE-COMMAND-HOLDER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
TURTLE-COMMAND-HOLDER-RECALL-2)) 
(SETQ TURTLE-COMMAND-HOLDER-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SOMETHING))) 
(DEFPROP TURTLE-COMMAND-HOLDER-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ TURTLE-COMMAND-HOLDER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE 
(DIRECTOR-SYMBOL-FOR-VALUE (NIL)))) 
(DEFPROP TURTLE-COMMAND-HOLDER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP TURTLE-COMMAND-HOLDER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ TURTLE-COMMAND-HOLDER-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
TURTLE-COMMAND-HOLDER))) 
(DEFPROP TURTLE-COMMAND-HOLDER-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(DEFUN ORIGINAL-METHODS-OF-TURTLE-COMMAND-HOLDER (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE 
(QUOTE (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
TURTLE-COMMAND-HOLDER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (EQUAL MESSAGE (QUOTE 
(RECALL YOUR NAME))) TURTLE-COMMAND-HOLDER-RECALL-2)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 3 TURTLE-COMMAND-HOLDER-RECALL-1 
(ORIGINAL-METHODS-OF-TURTLE-COMMAND-HOLDER 
TURTLE-COMMAND-HOLDER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
TURTLE-COMMAND-HOLDER-RECALL-2))) (QUOTE TURTLE-COMMAND-HOLDER)) 
(REMPROP (QUOTE TURTLE-COMMAND-HOLDER) (QUOTE ACTOR-LOAD)) 
(ASK SOMETHING ADD TURTLE-COMMAND-HOLDER TO YOUR LIST OF OFFSPRING) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE MOVIE) (QUOTE |DSK:KEN;MOVIE DEPEND|)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR COMPILED?)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR COMPILED?)| (RECALL YOUR COMPILED?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR FRAME-COUNT)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR FRAME-COUNT)| (RECALL YOUR FRAME-COUNT) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR SPEED)| (SOMETHING-RECALL-16) MATCHING-METHODS) (DEFPROP 
|MOVIE(RECALL YOUR SPEED)| (RECALL YOUR SPEED) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR NEW-FRAME-ACTION)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |MOVIE(RECALL YOUR NEW-FRAME-ACTION)| (RECALL YOUR 
NEW-FRAME-ACTION) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR (FRAME ?))| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR (FRAME ?))| (RECALL YOUR (FRAME ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR NEW-FRAME-HANDLER)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |MOVIE(RECALL YOUR NEW-FRAME-HANDLER)| (RECALL YOUR 
NEW-FRAME-HANDLER) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR SCREEN-MODE)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR SCREEN-MODE)| (RECALL YOUR SCREEN-MODE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR UNIVERSE)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR UNIVERSE)| (RECALL YOUR UNIVERSE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR TICKS-PER-FRAME)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR TICKS-PER-FRAME)| (RECALL YOUR TICKS-PER-FRAME) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR FRAMES-PER-SECOND)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |MOVIE(RECALL YOUR FRAMES-PER-SECOND)| (RECALL YOUR 
FRAMES-PER-SECOND) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR STOPPED?)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |MOVIE(RECALL YOUR STOPPED?)| (RECALL YOUR STOPPED?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(RECALL YOUR ACTORS-TO-RUN-NEXT)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |MOVIE(RECALL YOUR ACTORS-TO-RUN-NEXT)| (RECALL YOUR 
ACTORS-TO-RUN-NEXT) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(MAKE COPY (TO-BE-COMPILED ?))| (SOMETHING-MAKE-31) MATCHING-METHODS) 
(DEFPROP |MOVIE(MAKE COPY (TO-BE-COMPILED ?))| (MAKE COPY (TO-BE-COMPILED ?)) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(FORGET YOUR (FRAME ?))| (SOMETHING-FORGET-62) MATCHING-METHODS) 
(DEFPROP |MOVIE(FORGET YOUR (FRAME ?))| (FORGET YOUR (FRAME ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR COMPILED? TO SHOULD-BE)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |MOVIE(SET YOUR COMPILED? TO SHOULD-BE)| (SET YOUR COMPILED? TO 
SHOULD-BE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR NAME TO ?)| (SOMETHING-SET-13 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |MOVIE(SET YOUR NAME TO ?)| (SET YOUR NAME TO ?) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR CURRENT-MOVIE TO ?)| (SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |MOVIE(SET YOUR CURRENT-MOVIE TO ?)| (SET YOUR CURRENT-MOVIE TO ?) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR FRAME-COUNT TO ?)| (SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |MOVIE(SET YOUR FRAME-COUNT TO ?)| (SET YOUR FRAME-COUNT TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR NEW-FRAME-HANDLER TO JUST-STORE-AWAY-FRAME)| 
(SOMETHING-SET-14) MATCHING-METHODS) (DEFPROP 
|MOVIE(SET YOUR NEW-FRAME-HANDLER TO JUST-STORE-AWAY-FRAME)| (SET YOUR NEW-FRAME-HANDLER TO 
JUST-STORE-AWAY-FRAME) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR (FRAME ?) TO ?)| (SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |MOVIE(SET YOUR (FRAME ?) TO ?)| (SET YOUR (FRAME ?) TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SET YOUR STOPPED? TO T)| (SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |MOVIE(SET YOUR STOPPED? TO T)| (SET YOUR STOPPED? TO T) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(SAVE %)| (SOMETHING-SAVE-77) MATCHING-METHODS) (DEFPROP 
|MOVIE(SAVE %)| (SAVE %) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(UNMAKE)| (SOMETHING-UNMAKE-34) MATCHING-METHODS) (DEFPROP 
|MOVIE(UNMAKE)| (UNMAKE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(FILM THE NEXT ? TICKS)| (MOVIE-FILM-4) MATCHING-METHODS) (DEFPROP 
|MOVIE(FILM THE NEXT ? TICKS)| (FILM THE NEXT ? TICKS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(MEMORIZE (HAPPENED ? AT FRAME ?))| (SOMETHING-MEMORIZE-35) 
MATCHING-METHODS) (DEFPROP |MOVIE(MEMORIZE (HAPPENED ? AT FRAME ?))| (MEMORIZE (HAPPENED ? 
AT FRAME ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(ASK EACH OF YOUR (FRAME ?) TO PRINT MEMORY)| (SOMETHING-ASK-53 
SOMETHING-ASK-54 SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|MOVIE(ASK EACH OF YOUR (FRAME ?) TO PRINT MEMORY)| (ASK EACH OF YOUR (FRAME ?) TO PRINT 
MEMORY) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |MOVIE(STORE AWAY THE FRAME NUMBER ?)| (MOVIE-STORE-6) MATCHING-METHODS) 
(DEFPROP |MOVIE(STORE AWAY THE FRAME NUMBER ?)| (STORE AWAY THE FRAME NUMBER ?) 
MESSAGE-PATTERN)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE FRAME-HANDLER) (QUOTE |DSK:KEN;MOVIE DEPEND|)) 
(PROGN (DEFPROP |FRAME-HANDLER(JUST MADE FRAME NUMBER ? FOR ?)| (FRAME-HANDLER-JUST-3) 
MATCHING-METHODS) (DEFPROP |FRAME-HANDLER(JUST MADE FRAME NUMBER ? FOR ?)| (JUST MADE FRAME 
NUMBER ? FOR ?) MESSAGE-PATTERN)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE JUST-STORE-AWAY-FRAME) (QUOTE 
|DSK:KEN;MOVIE DEPEND|)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE TURTLE-COMMAND-HOLDER) (QUOTE 
|DSK:KEN;MOVIE DEPEND|)) 
(PROGN (DEFPROP |TURTLE-COMMAND-HOLDER(SET YOUR TURTLE-COMMANDS TO NIL)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |TURTLE-COMMAND-HOLDER(SET YOUR TURTLE-COMMANDS TO NIL)| (SET 
YOUR TURTLE-COMMANDS TO NIL) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |TURTLE-COMMAND-HOLDER(RECALL YOUR TURTLE-COMMANDS)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |TURTLE-COMMAND-HOLDER(RECALL YOUR TURTLE-COMMANDS)| (RECALL YOUR 
TURTLE-COMMANDS) MESSAGE-PATTERN)) 