;; -*-lisp-*- produced by Director (IN MACLISP)

(INCLUDE |ai:ken;declare >|) 
(INCLUDE |ai:ken;declar >|) 
(DEFCOMMENT MOVIE) 
(DEFINE-FORM
 (ERASE+DRAW-FRAME PREVIOUS-FRAME CURRENT-FRAME SPEED LAST-RUNTIME)
 (ERASERDOWN)
 (AND
  PREVIOUS-FRAME
  (RUN-FRAME (SET-MINUS PREVIOUS-FRAME CURRENT-FRAME) -999.9 LAST-RUNTIME '(ERASE)))
 (PENDOWN)
 (RUN-FRAME (SET-MINUS CURRENT-FRAME PREVIOUS-FRAME) SPEED LAST-RUNTIME '(DISPLAY))) 
(DEFINE-FORM (PUT-IN-WHOLINE X) (SSTATUS WHO3 (APPEND-ATOMS 'F= X)) X) 
(DEFINE-FORM
 (PRINT-THE-MOVIE-ARRAY
  FRAMES
  MOVIE-NAME
  ARRAY-NAME
  CLONES-NAME
  FRAME-NUMBER
  FILE-OBJECT)
 (PRINT '(ARRAY ,ARRAY-NAME T ,FRAME-NUMBER) FILE-OBJECT)
 (PRINT '(FILLARRAY (QUOTE ,ARRAY-NAME) (QUOTE ,(NREVERSE FRAMES))) FILE-OBJECT)
 (PRINT '(ASK ,CLONES-NAME SET YOUR FRAMES TO ,ARRAY-NAME) FILE-OBJECT)
 (PRINT '(ASK ,CLONES-NAME MAKE SYNONYM ,MOVIE-NAME) FILE-OBJECT)
 (PRINT '(ASK ,CLONES-NAME SET YOUR NAME TO ,MOVIE-NAME) FILE-OBJECT)
 (PRINT
  '(COND ((BOUNDP '*COMPILED-MOVIES)
          (SETQ *COMPILED-MOVIES (CONS (QUOTE ,ARRAY-NAME) *COMPILED-MOVIES)))
         (T (SETQ *COMPILED-MOVIES (QUOTE (,ARRAY-NAME)))))
  FILE-OBJECT)) 
(DEFINE-SYNONYM EOF EVAL-ON-FRAME) 
(DEFINE-SYNONYM DMAAO DISPLAY-MOVIE-ALL-AT-ONCE) 
(COMMENT HERE COMES THE ACTORS THEMSELVES) 
(OR
 (GET-ACTOR (QUOTE MOVIE))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE MOVIE))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE MOVIE))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME MOVIE PRIVATE)                     (SPEED 999999)
       (NEW-FRAME-ACTION ERASE-OLD)             (NEW-FRAME-HANDLER FRAME-HANDLER)
       (STAGE-MODE SILENT)                      (FRAME-COUNT 0))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0498 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0499 |(FILM THE NEXT ? ?)|))
  (QUOTE (NORMAL-METHOD D0500 |(FILM SECRETLY THE NEXT ? ?)|))
  (QUOTE (NORMAL-METHOD D0501 |(STORE AWAY THE FRAME NUMBER ?)|))
  (QUOTE (NORMAL-METHOD D0502 (STOP FILMING)))
  (QUOTE (NORMAL-METHOD D0503 |(RECORD ?)|))
  (QUOTE (NORMAL-METHOD D0504 (PROJECT)))
  (QUOTE (NORMAL-METHOD D0505 |(PROJECT FRAMES ? TO ? SHOWING EVERY ?)|))
  (QUOTE (NORMAL-METHOD D0506 |(PROJECT FRAMES ? TO ?)|))
  (QUOTE (NORMAL-METHOD D0507 |(PROJECT STARTING AT FRAME ? SHOWING EVERY ?)|))
  (QUOTE (NORMAL-METHOD D0508 |(PROJECT SHOWING EVERY ?)|))
  (QUOTE (NORMAL-METHOD D0509 |(PROJECT FRAME ?)|))
  (QUOTE (NORMAL-METHOD D0510 |(PRINT FRAMES ? TO ?)|))
  (QUOTE (NORMAL-METHOD D0512 |(COMPILE ?)|))
  (QUOTE SOMETHING))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE MOVIE))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE MOVIE))))) 
(REMPROP (QUOTE MOVIE) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE FRAME-HANDLER))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE FRAME-HANDLER))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE FRAME-HANDLER))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME FRAME-HANDLER PRIVATE))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (NORMAL-METHOD D0513 |(JUST MADE FRAME NUMBER ? FOR ?)|))
  (QUOTE SOMETHING))) 
(REMPROP (QUOTE FRAME-HANDLER) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE JUST-STORE-AWAY-FRAME))
 (PLACE-ACTOR-ON-NAME
  (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL)
  (QUOTE JUST-STORE-AWAY-FRAME))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE JUST-STORE-AWAY-FRAME))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME JUST-STORE-AWAY-FRAME PRIVATE))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (NORMAL-METHOD D0514 |(JUST MADE FRAME NUMBER ? FOR ?)|))
  (QUOTE FRAME-HANDLER))) 
(REMPROP (QUOTE JUST-STORE-AWAY-FRAME) (QUOTE ACTOR-LOAD)) 
(COMMENT THE FOLLOWING ARE THE ACTORS NEEDED FOR THE FOLLOWING METHODS) 
(ACTOR-OF (QUOTE STAGE)) 
(COMMENT NOW FOR METHOD HELPERS (IE FUNCTIONS WHICH DO TRANSMISSIONS)) 
(DEFINE-FORM
 (DISPLAY-MOVIE-ALL-AT-ONCE MOVIE DOWN? COLUMNS X-SPACE Y-SPACE X-HOME Y-HOME SCALE)
 (CLEARSCREEN)
 (DO
  ((FRAME 0 (1+ FRAME))
   (LAST-FRAME
    (LET
     ((MYSELF (ACTOR-OF MOVIE)) (*MESSAGE '(RECALL YOUR FRAME-COUNT)))
     (QUICK-COMPILED-ASK
      '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
      '#,(ACTOR-OF (QUOTE MOVIE))))))
  ((> FRAME LAST-FRAME))
  (PENUP)
  (LET
   ((*DIRECTOR-HOME-STATE
     (COND (DOWN?
            (LIST
             (FLOAT (PLUS (TIMES (// FRAME COLUMNS) X-SPACE) X-HOME))
             (FLOAT (PLUS (TIMES (\ FRAME COLUMNS) Y-SPACE -1.0) Y-HOME))))
           (T
            (LIST
             (FLOAT (PLUS (TIMES (\ FRAME COLUMNS) X-SPACE) X-HOME))
             (FLOAT (PLUS (TIMES (// FRAME COLUMNS) Y-SPACE -1.0) Y-HOME))))))
    (*DIRECTOR-TURTLE-SCALING-FACTOR (TIMES *DIRECTOR-TURTLE-SCALING-FACTOR SCALE)))
   (LET
    ((MYSELF (ACTOR-OF MOVIE)) (*MESSAGE '(PROJECT FRAME ,FRAME)))
    (QUICK-COMPILED-ASK
     '#,(METHOD-AT-POSITION (|(PROJECT FRAME ?)| 0) MOVIE)
     '#,(ACTOR-OF (QUOTE MOVIE))))))) 
(DEFINE-FORM
 (EVAL-ON-FRAME MOVIE FORM FRAME-NUMBER)
 (LET
  ((FRAME-HANDLER
    (LET
     ((MYSELF (ACTOR-OF MOVIE)) (*MESSAGE '(RECALL YOUR NEW-FRAME-HANDLER)))
     (QUICK-COMPILED-ASK
      '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
      '#,(ACTOR-OF (QUOTE MOVIE))))))
  (COND (FRAME-HANDLER
         (LET
          ((MYSELF (ACTOR-OF FRAME-HANDLER))
           (*MESSAGE
            '(DO
              WHEN
              RECEIVING
              (JUST MADE FRAME NUMBER ,FRAME-NUMBER FOR ?MOVIE)
              ,FORM
              (COMPILE-USING
               FRAME-HANDLER
               (ASK-OLD MYSELF JUST MADE FRAME NUMBER ,FRAME-NUMBER FOR ,MOVIE)))))
          (QUICK-COMPILED-ASK
           '#,(METHOD-AT-POSITION (|(DO WHEN RECEIVING ? %)| 0) SOMETHING)
           '#,(ACTOR-OF (QUOTE MOVIE)))))
        (T (WARNING 'EVAL-ON-FRAME '(,MOVIE IS NOT A MOVIE)))))) 
(DEFINE-FORM
 (SAVE-COPY-OF-THE-MOVIE MOVIE FILE-NAME)
 (LET
  ((CLONE
    (LET
     ((MYSELF (ACTOR-OF MOVIE))
      (*MESSAGE '(CLONE AND NAME IT ,(ASK ,MOVIE MAKE UP A NAME))))
     (QUICK-COMPILED-ASK
      '#,(METHOD-AT-POSITION (|(CLONE AND NAME IT ?)| 0) SOMETHING)
      '#,(ACTOR-OF (QUOTE MOVIE))))))
  (LET
   ((MYSELF (ACTOR-OF CLONE)) (*MESSAGE '(SET YOUR COMPILED? TO SHOULD-BE)))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE MOVIE))))
  (LET
   ((MYSELF (ACTOR-OF CLONE)) (*MESSAGE '(REMOVE METHOD FOR RECALL YOUR (FRAME X))))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(REMOVE METHOD FOR %)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE MOVIE))))
  (LET
   ((MYSELF (ACTOR-OF CLONE)) (*MESSAGE '(REMOVE METHOD FOR SET YOUR (FRAME X) TO Y)))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(REMOVE METHOD FOR %)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE MOVIE))))
  (LET
   ((MYSELF (ACTOR-OF CLONE)) (*MESSAGE '(FORGET YOUR (ARRAY-FOR (FRAME ?NUMBER)))))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(FORGET YOUR ?)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE MOVIE))))
  (LET
   ((MYSELF (ACTOR-OF CLONE)) (*MESSAGE '(SAVE ,FILE-NAME)))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(SAVE %)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE MOVIE))))
  CLONE)) 
(DEFINE-FORM
 (RUN-FRAME CURRENT-APPEARANCES SPEED LAST-RUNTIME ACTION)
 (MAPC
  (FUNCTION
   (LAMBDA (CURRENT-APPEARANCE)
     (AND
      CURRENT-APPEARANCE
      (LET ((*MESSAGE '(!,ACTION))) (CASES (ACTOR-OF CURRENT-APPEARANCE))))))
  CURRENT-APPEARANCES)
 (SLEEP (-$ SPEED (//$ (FLOAT (- (RUNTIME) LAST-RUNTIME)) 1000000.0)))) 
(DEFINE-FORM
 (SHOW-NORMAL-MOVIE FIRST-FRAME LAST-FRAME SKIP-EVERY)
 (WIPE)
 (LET
  (
   (INCREMENT
    (COND ((< FIRST-FRAME LAST-FRAME) SKIP-EVERY)
          (T (- SKIP-EVERY)))))
  (DO
   ((FRAME-NUMBER FIRST-FRAME (+ FRAME-NUMBER INCREMENT))
    (LAST-RUNTIME (RUNTIME) (RUNTIME))
    (BEGIN-TIME (RUNTIME))
    (SPEED
     (//$
      (FLOAT
       (LET
        ((*MESSAGE '(RECALL YOUR SPEED)))
        (QUICK-COMPILED-ASK
         '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
         '#,(ACTOR-OF (QUOTE MOVIE)))))))
    (NEW-FRAME-ACTION
     (LET
      ((*MESSAGE '(RECALL YOUR NEW-FRAME-ACTION)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
       '#,(ACTOR-OF (QUOTE MOVIE)))))
    (LAST-FRAME
     (MIN
      LAST-FRAME
      (LET
       ((*MESSAGE '(RECALL YOUR FRAME-COUNT)))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
        '#,(ACTOR-OF (QUOTE MOVIE))))))
    (FRAME NIL)
    (PREVIOUS-FRAME NIL FRAME))
   (
    (COND ((> INCREMENT 0) (> FRAME-NUMBER LAST-FRAME))
          (T (< FRAME-NUMBER LAST-FRAME)))
    '(|I did it in| ,(//$ (FLOAT (- (RUNTIME) BEGIN-TIME)) 1000000.0) |cpu seconds.|))
   (SETQ FRAME
         (LET
          ((*MESSAGE '(RECALL YOUR (FRAME ,FRAME-NUMBER))))
          (QUICK-COMPILED-ASK
           '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
           '#,(ACTOR-OF (QUOTE MOVIE)))))
   (PUT-IN-WHOLINE FRAME-NUMBER)
   (COND ((NULL FRAME))
         ((EQ NEW-FRAME-ACTION 'ERASE-OLD)
          (ERASE+DRAW-FRAME PREVIOUS-FRAME FRAME SPEED LAST-RUNTIME))
         ((EQ (FIRST NEW-FRAME-ACTION) 'ERASE-PREVIOUS)
          (ERASE+DRAW-FRAME
           (LET
            ((*MESSAGE
              '(RECALL YOUR (FRAME ,(- FRAME-NUMBER (SECOND NEW-FRAME-ACTION))))))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE))))
           FRAME
           SPEED
           LAST-RUNTIME))
         (T (EVAL NEW-FRAME-ACTION) (RUN-FRAME FRAME SPEED LAST-RUNTIME '(DISPLAY))))))) 
(DEFINE-FORM
 (SHOW-MOVIE FIRST-FRAME LAST-FRAME SKIP-EVERY)
 (COND ((LET
         ((*MESSAGE '(RECALL YOUR COMPILED?)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE MOVIE))))
        (PROJECT-COMPILED-MOVIE
         (LET
          ((*MESSAGE '(RECALL YOUR FRAMES)))
          (QUICK-COMPILED-ASK
           '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
           '#,(ACTOR-OF (QUOTE MOVIE))))
         FIRST-FRAME
         (MIN
          LAST-FRAME
          (LET
           ((*MESSAGE '(RECALL YOUR FRAME-COUNT)))
           (QUICK-COMPILED-ASK
            '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
            '#,(ACTOR-OF (QUOTE MOVIE)))))
         SKIP-EVERY
         (//$
          (FLOAT
           (LET
            ((*MESSAGE '(RECALL YOUR SPEED)))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE))))))
         (LET
          ((*MESSAGE '(RECALL YOUR NEW-FRAME-ACTION)))
          (QUICK-COMPILED-ASK
           '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
           '#,(ACTOR-OF (QUOTE MOVIE))))))
       (T (SHOW-NORMAL-MOVIE FIRST-FRAME LAST-FRAME SKIP-EVERY)))) 
(COMMENT NOW THE DEFINITIONS OF THE METHODS OF THE ABOVE ACTORS) 
(DEFUN D0512 NIL
  ((LAMBDA (FILE-NAME)
     (LET
      ((CLONES-NAME (SAVE-COPY-OF-THE-MOVIE MYSELF FILE-NAME))
       (MOVIE-NAME (NAME-OF MYSELF)))
      (LET-FILES
       ((FILE-OBJECT (OPEN FILE-NAME 'APPEND)))
       (DO
        ((COMPILED-APPEARANCES NIL)
         (FRAMES NIL)
         (FRAME-COUNT
          (LET
           ((*MESSAGE '(RECALL YOUR FRAME-COUNT)))
           (QUICK-COMPILED-ASK
            '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
            '#,(ACTOR-OF (QUOTE MOVIE)))))
         (FRAME-NUMBER 0 (1+ FRAME-NUMBER))
         (ARRAY-NAME (APPEND-ATOMS MOVIE-NAME '-FRAMES))
         (DRAW-PROCEDURES NIL))
        ((> FRAME-NUMBER FRAME-COUNT)
         (MAPC
          (FUNCTION
           (LAMBDA (DRAW-PROCEDURE)
             (DEFUNIZE
              DRAW-PROCEDURE
              (GET-INTERPRETIVE-DEFINITION DRAW-PROCEDURE)
              FILE-OBJECT)))
          DRAW-PROCEDURES)
         (PRINT-THE-MOVIE-ARRAY
          FRAMES
          MOVIE-NAME
          ARRAY-NAME
          CLONES-NAME
          FRAME-NUMBER
          FILE-OBJECT)
         NO-VALUE)
        (DO
         ((APPEARANCES
           (LET
            ((*MESSAGE '(RECALL YOUR (FRAME ,FRAME-NUMBER))))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE))))
           (REST APPEARANCES))
          (FRAME))
         ((NULL APPEARANCES) (PUSH FRAME FRAMES))
         (LET
          ((COMPILED-APPEARANCE
            (LET
             ((MYSELF (ACTOR-OF (FIRST APPEARANCES))) (*MESSAGE '(COMPILE AS FUNCTION)))
             (QUICK-COMPILED-ASK
              '#,(METHOD-AT-POSITION ((COMPILE AS FUNCTION) 0) APPEARANCE)
              '#,(ACTOR-OF (QUOTE APPEARANCE))))))
          (PUSH
           (CONS
            (COND ((SECOND (ASSOC COMPILED-APPEARANCE COMPILED-APPEARANCES)))
                  (T
                   (LET
                    ((APPEARANCE-NAME (GENERATE-SYMBOL MOVIE-NAME)))
                    (SETQ DRAW-PROCEDURES
                          (UNION
                           DRAW-PROCEDURES
                           (LET
                            ((MYSELF (ACTOR-OF (FIRST APPEARANCES)))
                             (*MESSAGE '(RECALL YOUR DRAW-PROCEDURES)))
                            (QUICK-COMPILED-ASK
                             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
                             '#,(ACTOR-OF (QUOTE MOVIE))))))
                    (DEFUNIZE APPEARANCE-NAME COMPILED-APPEARANCE FILE-OBJECT)
                    (PUSH
                     (LIST COMPILED-APPEARANCE APPEARANCE-NAME)
                     COMPILED-APPEARANCES)
                    APPEARANCE-NAME)))
            (LET
             ((MYSELF (ACTOR-OF (FIRST APPEARANCES))) (*MESSAGE '(RECALL YOUR STATE)))
             (QUICK-COMPILED-ASK
              '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
              '#,(ACTOR-OF (QUOTE MOVIE)))))
           FRAME)))))))
   (CADR *MESSAGE))) 
(DEFUN |(COMPILE ?)| (OBJECT)
  (AND (EQ (CAR OBJECT) (QUOTE COMPILE)) (ONE-LONG (CDR OBJECT)))) 
(DEFPROP |(COMPILE ?)| (COMPILE ?) PATTERN) 
(DEFUN D0510 NIL
  ((LAMBDA (END BEGIN)
     (DO
      ((I BEGIN (1+ I)))
      ((> I END))
      (LET
       ((*MESSAGE '(SEQUENTIALLY (ASK EACH OF YOUR (FRAME ,I) TO PRINT MEMORY))))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION (|(SEQUENTIALLY (ASK EACH OF YOUR ? %) %)| 0) SOMETHING)
        '#,(ACTOR-OF (QUOTE MOVIE))))
      (TERPRI)
      (PRINC '|End of frame number |)
      (PRINC I)))
   (CAR (CDDDDR *MESSAGE)) (CADDR *MESSAGE))) 
(DEFUN |(PRINT FRAMES ? TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE PRINT))
   (AND
    (EQ (CADR OBJECT) (QUOTE FRAMES))
    (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT)))))) 
(DEFPROP |(PRINT FRAMES ? TO ?)| (PRINT FRAMES ? TO ?) PATTERN) 
(DEFUN D0509 NIL
  ((LAMBDA (NUMBER)
     (COND ((LET
             ((*MESSAGE '(RECALL YOUR COMPILED?)))
             (QUICK-COMPILED-ASK
              '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
              '#,(ACTOR-OF (QUOTE MOVIE))))
            (RUN-COMPILED-FRAME
             (ARRAYCALL
              T
              (GET
               (LET
                ((*MESSAGE '(RECALL YOUR FRAMES)))
                (QUICK-COMPILED-ASK
                 '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
                 '#,(ACTOR-OF (QUOTE MOVIE))))
               'ARRAY)
              NUMBER)
             0.0
             (RUNTIME)
             'PENDOWN))
           (T
            (RUN-FRAME
             (LET
              ((*MESSAGE '(RECALL YOUR (FRAME ,NUMBER))))
              (QUICK-COMPILED-ASK
               '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
               '#,(ACTOR-OF (QUOTE MOVIE))))
             0.0
             (RUNTIME)
             '(DISPLAY)))))
   (CADDR *MESSAGE))) 
(DEFUN |(PROJECT FRAME ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE PROJECT))
   (AND (EQ (CADR OBJECT) (QUOTE FRAME)) (ONE-LONG (CDDR OBJECT))))) 
(DEFPROP |(PROJECT FRAME ?)| (PROJECT FRAME ?) PATTERN) 
(DEFUN D0508 NIL ((LAMBDA (SO-MANY) (SHOW-MOVIE 0 999999999 SO-MANY)) (CADDDR *MESSAGE))) 
(DEFUN |(PROJECT SHOWING EVERY ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE PROJECT))
   (AND
    (EQ (CADR OBJECT) (QUOTE SHOWING))
    (AND (EQ (CADDR OBJECT) (QUOTE EVERY)) (ONE-LONG (CDDDR OBJECT)))))) 
(DEFPROP |(PROJECT SHOWING EVERY ?)| (PROJECT SHOWING EVERY ?) PATTERN) 
(DEFUN D0507 NIL
  ((LAMBDA (SO-MANY BEGIN) (SHOW-MOVIE BEGIN 999999999 SO-MANY))
   (CADDDR (CDDDDR *MESSAGE)) (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(PROJECT STARTING AT FRAME ? SHOWING EVERY ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE PROJECT))
   (AND
    (EQ (CADR OBJECT) (QUOTE STARTING))
    (AND
     (EQ (CADDR OBJECT) (QUOTE AT))
     (AND
      (EQ (CADDDR OBJECT) (QUOTE FRAME))
      (AND
       (EQ (CADR (CDDDDR OBJECT)) (QUOTE SHOWING))
       (AND
        (EQ (CADDR (CDDDDR OBJECT)) (QUOTE EVERY))
        (ONE-LONG (CDDDR (CDDDDR OBJECT)))))))))) 
(DEFPROP
 |(PROJECT STARTING AT FRAME ? SHOWING EVERY ?)|
 (PROJECT STARTING AT FRAME ? SHOWING EVERY ?)
 PATTERN) 
(DEFUN D0506 NIL
  ((LAMBDA (END BEGIN) (SHOW-MOVIE BEGIN END 1)) (CAR (CDDDDR *MESSAGE)) (CADDR *MESSAGE))) 
(DEFUN |(PROJECT FRAMES ? TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE PROJECT))
   (AND
    (EQ (CADR OBJECT) (QUOTE FRAMES))
    (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT)))))) 
(DEFPROP |(PROJECT FRAMES ? TO ?)| (PROJECT FRAMES ? TO ?) PATTERN) 
(DEFUN D0505 NIL
  ((LAMBDA (SO-MANY END BEGIN) (SHOW-MOVIE BEGIN END SO-MANY))
   (CADDDR (CDDDDR *MESSAGE)) (CAR (CDDDDR *MESSAGE)) (CADDR *MESSAGE))) 
(DEFUN |(PROJECT FRAMES ? TO ? SHOWING EVERY ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE PROJECT))
   (AND
    (EQ (CADR OBJECT) (QUOTE FRAMES))
    (AND
     (EQ (CADDDR OBJECT) (QUOTE TO))
     (AND
      (EQ (CADR (CDDDDR OBJECT)) (QUOTE SHOWING))
      (AND (EQ (CADDR (CDDDDR OBJECT)) (QUOTE EVERY)) (ONE-LONG (CDDDR (CDDDDR OBJECT))))))))
  ) 
(DEFPROP
 |(PROJECT FRAMES ? TO ? SHOWING EVERY ?)|
 (PROJECT FRAMES ? TO ? SHOWING EVERY ?)
 PATTERN) 
(DEFUN D0504 NIL (SHOW-MOVIE 0 999999999 1)) 
(DEFUN D0503 NIL
  ((LAMBDA (EVENT)
     (LET
      ((*MESSAGE
        '(MEMORIZE (HAPPENED ,EVENT AT FRAME ,(ASK MYSELF RECALL YOUR FRAME-COUNT)))))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(MEMORIZE ?)| 0) SOMETHING)
       '#,(ACTOR-OF (QUOTE MOVIE)))))
   (CADR *MESSAGE))) 
(DEFUN |(RECORD ?)| (OBJECT)
  (AND (EQ (CAR OBJECT) (QUOTE RECORD)) (ONE-LONG (CDR OBJECT)))) 
(DEFPROP |(RECORD ?)| (RECORD ?) PATTERN) 
(DEFUN D0502 NIL
  (LET
   ((*MESSAGE '(SET YOUR STOPPED? TO T)))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE MOVIE))))) 
(DEFUN D0501 NIL
  ((LAMBDA (NUMBER)
     (LET
      ((*MESSAGE '(SET YOUR (FRAME ,NUMBER) TO ,(OR (ASK STAGE SAVE STAGE) '(NIL)))))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
       '#,(ACTOR-OF (QUOTE MOVIE)))))
   (CADR (CDDDDR *MESSAGE)))) 
(DEFUN |(STORE AWAY THE FRAME NUMBER ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE STORE))
   (AND
    (EQ (CADR OBJECT) (QUOTE AWAY))
    (AND
     (EQ (CADDR OBJECT) (QUOTE THE))
     (AND
      (EQ (CADDDR OBJECT) (QUOTE FRAME))
      (AND (EQ (CAR (CDDDDR OBJECT)) (QUOTE NUMBER)) (ONE-LONG (CDR (CDDDDR OBJECT))))))))) 
(DEFPROP |(STORE AWAY THE FRAME NUMBER ?)| (STORE AWAY THE FRAME NUMBER ?) PATTERN) 
(DEFUN D0500 NIL
  ((LAMBDA (UNITS LENGTH)
     (LET
      ((*MESSAGE '(SET YOUR NEW-FRAME-HANDLER TO JUST-STORE-AWAY-FRAME)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
       '#,(ACTOR-OF (QUOTE MOVIE))))
     (LET
      ((*MESSAGE '(FILM THE NEXT ,LENGTH ,UNITS)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(FILM THE NEXT ? ?)| 0) MOVIE)
       '#,(ACTOR-OF (QUOTE MOVIE)))))
   (CADR (CDDDDR *MESSAGE)) (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(FILM SECRETLY THE NEXT ? ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE FILM))
   (AND
    (EQ (CADR OBJECT) (QUOTE SECRETLY))
    (AND
     (EQ (CADDR OBJECT) (QUOTE THE))
     (AND (EQ (CADDDR OBJECT) (QUOTE NEXT)) (ONE-LONG (CDR (CDDDDR OBJECT)))))))) 
(DEFPROP |(FILM SECRETLY THE NEXT ? ?)| (FILM SECRETLY THE NEXT ? ?) PATTERN) 
(DEFUN D0499 NIL
  ((LAMBDA (UNITS LENGTH)
     (LET
      ((MYSELF (ACTOR-OF (QUOTE MOVIE)))
       (*MESSAGE '(SET YOUR CURRENT-MOVIE TO ,(NAME-OF MYSELF))))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
       '#,(ACTOR-OF (QUOTE MOVIE))))
     (LET
      ((STAGE-MODE
        (LET
         ((MYSELF (ACTOR-OF (QUOTE STAGE))) (*MESSAGE '(RECALL YOUR MODE)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE STAGE)))))
       (CLOCK
        (LET
         ((*MESSAGE '(RECALL YOUR CLOCK)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE MOVIE)))))
       (MAX-FRAME-NUMBER
        (+
         (LET
          ((*MESSAGE '(RECALL YOUR FRAME-COUNT)))
          (QUICK-COMPILED-ASK
           '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
           '#,(ACTOR-OF (QUOTE MOVIE))))
         (LENGTH-IN-FRAMES LENGTH UNITS))))
      (LET
       ((*MESSAGE
         '(WHEN REPRESENTING (FRAME ?NUMBER) USE AN ARRAY OF SIZE ,(1+ MAX-FRAME-NUMBER))))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION
            (|(WHEN REPRESENTING ? USE AN ARRAY OF SIZE ?)| 0)
            SOMETHING)
        '#,(ACTOR-OF (QUOTE MOVIE))))
      (UNWIND-PROTECT
       (PROGN
        (LET
         ((MYSELF (ACTOR-OF (QUOTE STAGE)))
          (*MESSAGE '(SET YOUR MODE TO ,(ASK MYSELF RECALL YOUR STAGE-MODE))))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE STAGE))))
        (DO
         ((TIME 0 (1+ TIME))
          (FRAME-NUMBER
           (LET
            ((*MESSAGE '(RECALL YOUR FRAME-COUNT)))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE))))
           (1+ FRAME-NUMBER))
          (TICKS-PER-FRAME
           (LET
            ((MYSELF (ACTOR-OF CLOCK)) (*MESSAGE '(RECALL YOUR TICKS-PER-FRAME)))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE)))))
          (NEW-FRAME-HANDLER
           (LET
            ((*MESSAGE '(RECALL YOUR NEW-FRAME-HANDLER)))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE)))))
          (STOPPED?
           NIL
           (LET
            ((*MESSAGE '(RECALL YOUR STOPPED?)))
            (QUICK-COMPILED-ASK
             '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
             '#,(ACTOR-OF (QUOTE MOVIE))))))
         ((OR STOPPED? (> FRAME-NUMBER MAX-FRAME-NUMBER)) NO-VALUE)
         (COND ((= (\ TIME TICKS-PER-FRAME) 0)
                (PUT-IN-WHOLINE FRAME-NUMBER)
                (LET
                 ((MYSELF (ACTOR-OF NEW-FRAME-HANDLER))
                  (*MESSAGE '(JUST MADE FRAME NUMBER ,FRAME-NUMBER FOR ,MYSELF)))
                 (QUICK-COMPILED-ASK
                  '#,(METHOD-AT-POSITION
                      (|(JUST MADE FRAME NUMBER ? FOR ?)| 0)
                      FRAME-HANDLER)
                  '#,(ACTOR-OF (QUOTE FRAME-HANDLER))))
                (LET
                 ((*MESSAGE '(SET YOUR FRAME-COUNT TO ,FRAME-NUMBER)))
                 (QUICK-COMPILED-ASK
                  '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
                  '#,(ACTOR-OF (QUOTE MOVIE))))))
         (COND ((EQ
                 (LET
                  ((MYSELF (ACTOR-OF CLOCK)) (*MESSAGE '(TICK)))
                  (QUICK-COMPILED-ASK
                   '#,(METHOD-AT-POSITION ((TICK) 0) CLOCK)
                   '#,(ACTOR-OF (QUOTE CLOCK))))
                 NO-VALUE)
                (RETURN NO-VALUE)))))
       (LET
        ((MYSELF (ACTOR-OF (QUOTE STAGE))) (*MESSAGE '(SET YOUR MODE TO ,STAGE-MODE)))
        (QUICK-COMPILED-ASK
         '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
         '#,(ACTOR-OF (QUOTE STAGE)))))))
   (CAR (CDDDDR *MESSAGE)) (CADDDR *MESSAGE))) 
(DEFUN |(FILM THE NEXT ? ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE FILM))
   (AND
    (EQ (CADR OBJECT) (QUOTE THE))
    (AND (EQ (CADDR OBJECT) (QUOTE NEXT)) (ONE-LONG (CDDDDR OBJECT)))))) 
(DEFPROP |(FILM THE NEXT ? ?)| (FILM THE NEXT ? ?) PATTERN) 
(DEFUN D0498 (MESSAGE)
  (COND ((AND
          (EQ (CAR MESSAGE) (QUOTE FILM))
          (COND ((AND
                  (AND
                   (EQ (CADR MESSAGE) (QUOTE THE))
                   (AND (EQ (CADDR MESSAGE) (QUOTE NEXT)) (ONE-LONG (CDDDDR MESSAGE))))
                  (METHOD-IF-NOT-HIDDEN
                   '#,(METHOD-AT-POSITION (|(FILM THE NEXT ? ?)| 0) MOVIE))))
                ((AND
                  (AND
                   (EQ (CADR MESSAGE) (QUOTE SECRETLY))
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE THE))
                    (AND
                     (EQ (CADDDR MESSAGE) (QUOTE NEXT))
                     (ONE-LONG (CDR (CDDDDR MESSAGE))))))
                  (METHOD-IF-NOT-HIDDEN
                   '#,(METHOD-AT-POSITION (|(FILM SECRETLY THE NEXT ? ?)| 0) MOVIE)))))))
        ((AND
          (AND
           (EQ (CAR MESSAGE) (QUOTE STORE))
           (AND
            (EQ (CADR MESSAGE) (QUOTE AWAY))
            (AND
             (EQ (CADDR MESSAGE) (QUOTE THE))
             (AND
              (EQ (CADDDR MESSAGE) (QUOTE FRAME))
              (AND
               (EQ (CAR (CDDDDR MESSAGE)) (QUOTE NUMBER))
               (ONE-LONG (CDR (CDDDDR MESSAGE))))))))
          (METHOD-IF-NOT-HIDDEN
           '#,(METHOD-AT-POSITION (|(STORE AWAY THE FRAME NUMBER ?)| 0) MOVIE))))
        ((AND
          (EQUAL MESSAGE (QUOTE (STOP FILMING)))
          (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION ((STOP FILMING) 0) MOVIE))))
        ((AND
          (AND (EQ (CAR MESSAGE) (QUOTE RECORD)) (ONE-LONG (CDR MESSAGE)))
          (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION (|(RECORD ?)| 0) MOVIE))))
        ((AND
          (EQ (CAR MESSAGE) (QUOTE PROJECT))
          (COND ((AND
                  (NULL (CDR MESSAGE))
                  (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION ((PROJECT) 0) MOVIE))))
                ((AND
                  (EQ (CADR MESSAGE) (QUOTE FRAMES))
                  (COND ((AND
                          (EQ (CADDDR MESSAGE) (QUOTE TO))
                          (AND
                           (EQ (CADR (CDDDDR MESSAGE)) (QUOTE SHOWING))
                           (AND
                            (EQ (CADDR (CDDDDR MESSAGE)) (QUOTE EVERY))
                            (ONE-LONG (CDDDR (CDDDDR MESSAGE))))))
                         (METHOD-IF-NOT-HIDDEN
                          '#,(METHOD-AT-POSITION
                              (|(PROJECT FRAMES ? TO ? SHOWING EVERY ?)| 0)
                              MOVIE)))
                        ((AND
                          (EQ (CADDDR MESSAGE) (QUOTE TO))
                          (ONE-LONG (CDDDDR MESSAGE)))
                         (METHOD-IF-NOT-HIDDEN
                          '#,(METHOD-AT-POSITION (|(PROJECT FRAMES ? TO ?)| 0) MOVIE))))))
                ((AND
                  (AND
                   (EQ (CADR MESSAGE) (QUOTE STARTING))
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE AT))
                    (AND
                     (EQ (CADDDR MESSAGE) (QUOTE FRAME))
                     (AND
                      (EQ (CADR (CDDDDR MESSAGE)) (QUOTE SHOWING))
                      (AND
                       (EQ (CADDR (CDDDDR MESSAGE)) (QUOTE EVERY))
                       (ONE-LONG (CDDDR (CDDDDR MESSAGE))))))))
                  (METHOD-IF-NOT-HIDDEN
                   '#,(METHOD-AT-POSITION
                       (|(PROJECT STARTING AT FRAME ? SHOWING EVERY ?)| 0)
                       MOVIE))))
                ((AND
                  (AND
                   (EQ (CADR MESSAGE) (QUOTE SHOWING))
                   (AND (EQ (CADDR MESSAGE) (QUOTE EVERY)) (ONE-LONG (CDDDR MESSAGE))))
                  (METHOD-IF-NOT-HIDDEN
                   '#,(METHOD-AT-POSITION (|(PROJECT SHOWING EVERY ?)| 0) MOVIE))))
                ((AND
                  (AND (EQ (CADR MESSAGE) (QUOTE FRAME)) (ONE-LONG (CDDR MESSAGE)))
                  (METHOD-IF-NOT-HIDDEN
                   '#,(METHOD-AT-POSITION (|(PROJECT FRAME ?)| 0) MOVIE)))))))
        ((AND
          (AND
           (EQ (CAR MESSAGE) (QUOTE PRINT))
           (AND
            (EQ (CADR MESSAGE) (QUOTE FRAMES))
            (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))))
          (METHOD-IF-NOT-HIDDEN
           '#,(METHOD-AT-POSITION (|(PRINT FRAMES ? TO ?)| 0) MOVIE))))
        ((AND
          (AND (EQ (CAR MESSAGE) (QUOTE COMPILE)) (ONE-LONG (CDR MESSAGE)))
          (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION (|(COMPILE ?)| 0) MOVIE)))))) 
(DEFUN D0513 NIL
  ((LAMBDA (MOVIE FRAME-NUMBER)
     (LET
      ((ORIGINAL-MODE
        (LET
         ((MYSELF (ACTOR-OF (QUOTE STAGE))) (*MESSAGE '(RECALL YOUR MODE)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE STAGE))))))
      (COND ((NOT (EQ ORIGINAL-MODE 'NORMAL))
             (LET
              ((MYSELF (ACTOR-OF (QUOTE STAGE))) (*MESSAGE '(SET YOUR MODE TO NORMAL)))
              (QUICK-COMPILED-ASK
               '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
               '#,(ACTOR-OF (QUOTE STAGE))))
             (LET
              ((MYSELF (ACTOR-OF (QUOTE STAGE))) (*MESSAGE '(WIPE)))
              (QUICK-COMPILED-ASK
               '#,(METHOD-AT-POSITION ((WIPE) 0) STAGE)
               '#,(ACTOR-OF (QUOTE STAGE))))
             (LET
              ((MYSELF (ACTOR-OF (QUOTE STAGE)))
               (*MESSAGE '(SET YOUR MODE TO ,ORIGINAL-MODE)))
              (QUICK-COMPILED-ASK
               '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
               '#,(ACTOR-OF (QUOTE STAGE)))))))
     (LET
      ((MYSELF (ACTOR-OF MOVIE))
       (*MESSAGE '(STORE AWAY THE FRAME NUMBER ,FRAME-NUMBER)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(STORE AWAY THE FRAME NUMBER ?)| 0) MOVIE)
       '#,(ACTOR-OF (QUOTE MOVIE)))))
   (CADDR (CDDDDR *MESSAGE)) (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(JUST MADE FRAME NUMBER ? FOR ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE JUST))
   (AND
    (EQ (CADR OBJECT) (QUOTE MADE))
    (AND
     (EQ (CADDR OBJECT) (QUOTE FRAME))
     (AND
      (EQ (CADDDR OBJECT) (QUOTE NUMBER))
      (AND (EQ (CADR (CDDDDR OBJECT)) (QUOTE FOR)) (ONE-LONG (CDDR (CDDDDR OBJECT))))))))) 
(DEFPROP |(JUST MADE FRAME NUMBER ? FOR ?)| (JUST MADE FRAME NUMBER ? FOR ?) PATTERN) 
(DEFUN D0514 NIL
  ((LAMBDA (MOVIE FRAME-NUMBER)
     (LET
      ((MYSELF (ACTOR-OF MOVIE))
       (*MESSAGE '(STORE AWAY THE FRAME NUMBER ,FRAME-NUMBER)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(STORE AWAY THE FRAME NUMBER ?)| 0) MOVIE)
       '#,(ACTOR-OF (QUOTE MOVIE)))))
   (CADDR (CDDDDR *MESSAGE)) (CAR (CDDDDR *MESSAGE)))) 
(COMMENT AND NOW FOR THE ODDS AND ENDS) 
(ASK SOMETHING ADD MOVIE TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE MOVIE))) 
(ASK SOMETHING ADD FRAME-HANDLER TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE FRAME-HANDLER))) 
(ASK FRAME-HANDLER ADD JUST-STORE-AWAY-FRAME TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE JUST-STORE-AWAY-FRAME))) 