
(INCLUDE |ai:ken;declar >|) 
(DEFCOMMENT POLY) 
(DECLARE (SPECIAL ROCKET-RECALL-1 ROCKET-RECALL-2 
ROCKET-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3)) 
(SETQ ROCKET-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE OBJECT))) 
(DEFPROP ROCKET-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ ROCKET-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE ROCKET))) 
(DEFPROP ROCKET-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ ROCKET-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE (NIL 
(STATE 0.0 0.0 0.0) (VISIBILITY) (ARG-WHICH-IS-SIZE-IF-ANY . 1) (DRAW-PROCEDURE . 
DRAW-ROCKET) (DRAWING-ARGS SIZE) (NON-SHAPE-DRAWING-ARGS) (APPEARANCE-VARIABLES HOW-TO-DRAW 
COLORS CENTER-OFFSET) (VARIABLES-TO-COPY-UPON-CREATION HOW-TO-DRAW COLORS CENTER-OFFSET 
STATE VISIBILITY))))) 
(DEFPROP ROCKET-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP ROCKET-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(DEFUN ORIGINAL-METHODS-OF-ROCKET (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE (QUOTE (RECALL 
YOUR NAME))) ROCKET-RECALL-2)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
ROCKET-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 3 ROCKET-RECALL-1 
(ORIGINAL-METHODS-OF-ROCKET ROCKET-RECALL-2 ROCKET-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) 
(QUOTE ROCKET)) 
(REMPROP (QUOTE ROCKET) (QUOTE ACTOR-LOAD)) 
(ASK OBJECT ADD ROCKET TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL POLY-RECALL-1 POLY-RECALL-2 POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
POLY-SET-4)) 
(SETQ POLY-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE OBJECT))) 
(DEFPROP POLY-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ POLY-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE POLY))) 
(DEFPROP POLY-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE (NIL 
(STATE 0.0 0.0 0.0) (VISIBILITY) (ANGLE . 60) (ARG-WHICH-IS-SIZE-IF-ANY . 1) (DRAW-PROCEDURE .
 DRAW-POLY) (DRAWING-ARGS SIZE ANGLE) (NON-SHAPE-DRAWING-ARGS) (APPEARANCE-VARIABLES 
HOW-TO-DRAW COLORS CENTER-OFFSET) (VARIABLES-TO-COPY-UPON-CREATION HOW-TO-DRAW COLORS 
CENTER-OFFSET STATE VISIBILITY))))) 
(DEFPROP POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) 
METHOD-PATTERN) 
(DEFPROP POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ POLY-SET-4 (QUOTE POLY-SET-4)) 
(DEFPROP POLY-SET-4 (SET YOUR ANGLE TO ?) METHOD-PATTERN) 
(DEFUN POLY-SET-4 NIL ((LAMBDA (NEW-VALUE) (LET ((:MESSAGE (QUOTE (SET YOUR HOW-TO-DRAW TO 
NIL)))) (COMPILED-ASK (QUOTE |POLY(SET YOUR HOW-TO-DRAW TO NIL)|) (QUOTE POLY))) (LET 
((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE ANGLE) (CONS (QUOTE TO) (CONS 
NEW-VALUE NIL))))))) (SKIP-TYPE-COMPILED-ASK (QUOTE |POLY(SET YOUR ANGLE TO ?)|) (QUOTE 
POLY) T))) (FIRST (CDDDDR :MESSAGE)))) 
(DEFUN ORIGINAL-METHODS-OF-POLY (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE (QUOTE (RECALL 
YOUR NAME))) POLY-RECALL-2)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE SET)) 
(AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADDR MESSAGE) (QUOTE ANGLE)) (AND (EQ 
(CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))))) POLY-SET-4)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 4 POLY-RECALL-1 
(ORIGINAL-METHODS-OF-POLY POLY-RECALL-2 POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
POLY-SET-4))) (QUOTE POLY)) 
(REMPROP (QUOTE POLY) (QUOTE ACTOR-LOAD)) 
(ASK OBJECT ADD POLY TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL COLOR-POLY-RECALL-1 COLOR-POLY-RECALL-2 
COLOR-POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 COLOR-POLY-SET-4 COLOR-POLY-SET-5)) 
(SETQ COLOR-POLY-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE OBJECT))) 
(DEFPROP COLOR-POLY-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ COLOR-POLY-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE COLOR-POLY))) 
(DEFPROP COLOR-POLY-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ COLOR-POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL (STATE 0.0 0.0 0.0) (VISIBILITY) (ANGLE . 60) (ARG-WHICH-IS-SIZE-IF-ANY . 1) 
(DRAW-PROCEDURE . DRAW-COLOR-POLY) (DRAWING-ARGS SIZE ANGLE) (NON-SHAPE-DRAWING-ARGS COLORS) 
(APPEARANCE-VARIABLES HOW-TO-DRAW CENTER-OFFSET COLORS) (VARIABLES-TO-COPY-UPON-CREATION 
HOW-TO-DRAW CENTER-OFFSET COLORS STATE VISIBILITY))))) 
(DEFPROP COLOR-POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP COLOR-POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ COLOR-POLY-SET-4 (QUOTE COLOR-POLY-SET-4)) 
(DEFPROP COLOR-POLY-SET-4 (SET YOUR ANGLE TO ?) METHOD-PATTERN) 
(DEFUN COLOR-POLY-SET-4 NIL ((LAMBDA (NEW-VALUE) (LET ((:MESSAGE (QUOTE (SET YOUR 
HOW-TO-DRAW TO NIL)))) (COMPILED-ASK (QUOTE |COLOR-POLY(SET YOUR HOW-TO-DRAW TO NIL)|) 
(QUOTE COLOR-POLY))) (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE 
ANGLE) (CONS (QUOTE TO) (CONS NEW-VALUE NIL))))))) (SKIP-TYPE-COMPILED-ASK (QUOTE 
|COLOR-POLY(SET YOUR ANGLE TO ?)|) (QUOTE COLOR-POLY) T))) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ COLOR-POLY-SET-5 (QUOTE COLOR-POLY-SET-5)) 
(DEFPROP COLOR-POLY-SET-5 (SET YOUR COLORS TO ?) METHOD-PATTERN) 
(DEFUN COLOR-POLY-SET-5 NIL ((LAMBDA (NEW-VALUE) (LET ((HOW-TO-DRAW (LET ((:MESSAGE (QUOTE 
(RECALL YOUR HOW-TO-DRAW)))) (COMPILED-ASK (QUOTE |COLOR-POLY(RECALL YOUR HOW-TO-DRAW)|) 
(QUOTE COLOR-POLY))))) (LET ((:MESSAGE (QUOTE (SET YOUR APPEARANCE-CHANGED TO T)))) 
(COMPILED-ASK (QUOTE |COLOR-POLY(SET YOUR APPEARANCE-CHANGED TO T)|) (QUOTE COLOR-POLY))) 
(AND HOW-TO-DRAW (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE 
HOW-TO-DRAW) (CONS (QUOTE TO) (CONS (REPLACE-NTH 2 HOW-TO-DRAW (MAKE-INNER-DRAWER)) 
NIL))))))) (COMPILED-ASK (QUOTE |COLOR-POLY(SET YOUR HOW-TO-DRAW TO ?)|) (QUOTE 
COLOR-POLY))))) (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE COLORS) 
(CONS (QUOTE TO) (CONS NEW-VALUE NIL))))))) (SKIP-TYPE-COMPILED-ASK (QUOTE 
|COLOR-POLY(SET YOUR COLORS TO ?)|) (QUOTE COLOR-POLY) T))) (FIRST (CDDDDR :MESSAGE)))) 
(DEFUN ORIGINAL-METHODS-OF-COLOR-POLY (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE (QUOTE 
(RECALL YOUR NAME))) COLOR-POLY-RECALL-2)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
COLOR-POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (EQ (FIRST MESSAGE) (QUOTE SET)) 
(AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (COND ((AND (AND (EQ (CADDR MESSAGE) (QUOTE ANGLE)) 
(AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))) COLOR-POLY-SET-4)) ((AND 
(AND (EQ (CADDR MESSAGE) (QUOTE COLORS)) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG 
(CDDDDR MESSAGE)))) COLOR-POLY-SET-5)))))))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 5 COLOR-POLY-RECALL-1 
(ORIGINAL-METHODS-OF-COLOR-POLY COLOR-POLY-RECALL-2 
COLOR-POLY-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 COLOR-POLY-SET-4 COLOR-POLY-SET-5))) 
(QUOTE COLOR-POLY)) 
(REMPROP (QUOTE COLOR-POLY) (QUOTE ACTOR-LOAD)) 
(ASK OBJECT ADD COLOR-POLY TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL FLOWER-RECALL-1 FLOWER-RECALL-2 
FLOWER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 FLOWER-ERASE-4 FLOWER-SET-5 FLOWER-SET-6 
FLOWER-SET-7)) 
(SETQ FLOWER-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE OBJECT))) 
(DEFPROP FLOWER-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ FLOWER-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE FLOWER))) 
(DEFPROP FLOWER-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ FLOWER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE (NIL 
(STATE 0.0 0.0 0.0) (VISIBILITY) (NUMBER-OF-PETALS . 3) (PETAL-COLORS GREEN RED PURPLE 
MAGENTA PINK ORANGE) (SHADE-PATTERN) (ERASABILITY) (ARG-WHICH-IS-SIZE-IF-ANY . 1) 
(DRAW-PROCEDURE . DRAW-FLOWER) (DRAWING-ARGS SIZE NUMBER-OF-PETALS (PETAL-COLORS (QUOTE 
(WHITE))) (SHADE-PATTERN NIL)) (NON-SHAPE-DRAWING-ARGS) (APPEARANCE-VARIABLES HOW-TO-DRAW 
COLORS CENTER-OFFSET) (VARIABLES-TO-COPY-UPON-CREATION HOW-TO-DRAW COLORS CENTER-OFFSET 
STATE VISIBILITY))))) 
(DEFPROP FLOWER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP FLOWER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ FLOWER-ERASE-4 (QUOTE FLOWER-ERASE-4)) 
(DEFPROP FLOWER-ERASE-4 (ERASE) METHOD-PATTERN) 
(DEFUN FLOWER-ERASE-4 NIL (LET ((:MESSAGE (QUOTE (ERASE BY CLEARING AREA)))) (COMPILED-ASK 
(QUOTE |FLOWER(ERASE BY CLEARING AREA)|) (QUOTE FLOWER)))) 
(SETQ FLOWER-SET-5 (QUOTE FLOWER-SET-5)) 
(DEFPROP FLOWER-SET-5 (SET YOUR NUMBER-OF-PETALS TO ?) METHOD-PATTERN) 
(DEFUN FLOWER-SET-5 NIL ((LAMBDA (NEW-VALUE) (LET ((:MESSAGE (QUOTE (SET YOUR HOW-TO-DRAW TO 
NIL)))) (COMPILED-ASK (QUOTE |FLOWER(SET YOUR HOW-TO-DRAW TO NIL)|) (QUOTE FLOWER))) (LET 
((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE NUMBER-OF-PETALS) (CONS (QUOTE 
TO) (CONS NEW-VALUE NIL))))))) (SKIP-TYPE-COMPILED-ASK (QUOTE 
|FLOWER(SET YOUR NUMBER-OF-PETALS TO ?)|) (QUOTE FLOWER) T))) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ FLOWER-SET-6 (QUOTE FLOWER-SET-6)) 
(DEFPROP FLOWER-SET-6 (SET YOUR (PETAL-COLORS (QUOTE (WHITE))) TO ?) METHOD-PATTERN) 
(DEFUN FLOWER-SET-6 NIL ((LAMBDA (NEW-VALUE) (LET ((:MESSAGE (QUOTE (SET YOUR HOW-TO-DRAW TO 
NIL)))) (COMPILED-ASK (QUOTE |FLOWER(SET YOUR HOW-TO-DRAW TO NIL)|) (QUOTE FLOWER))) (LET 
((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE (PETAL-COLORS (QUOTE (WHITE)))) 
(CONS (QUOTE TO) (CONS NEW-VALUE NIL))))))) (SKIP-TYPE-COMPILED-ASK (QUOTE 
|FLOWER(SET YOUR (PETAL-COLORS '(WHITE)) TO ?)|) (QUOTE FLOWER) T))) (FIRST (CDDDDR 
:MESSAGE)))) 
(SETQ FLOWER-SET-7 (QUOTE FLOWER-SET-7)) 
(DEFPROP FLOWER-SET-7 (SET YOUR (SHADE-PATTERN NIL) TO ?) METHOD-PATTERN) 
(DEFUN FLOWER-SET-7 NIL ((LAMBDA (NEW-VALUE) (LET ((:MESSAGE (QUOTE (SET YOUR HOW-TO-DRAW TO 
NIL)))) (COMPILED-ASK (QUOTE |FLOWER(SET YOUR HOW-TO-DRAW TO NIL)|) (QUOTE FLOWER))) (LET 
((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE (SHADE-PATTERN NIL)) (CONS 
(QUOTE TO) (CONS NEW-VALUE NIL))))))) (SKIP-TYPE-COMPILED-ASK (QUOTE 
|FLOWER(SET YOUR (SHADE-PATTERN NIL) TO ?)|) (QUOTE FLOWER) T))) (FIRST (CDDDDR :MESSAGE)))) 
(DEFUN ORIGINAL-METHODS-OF-FLOWER (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE (QUOTE (RECALL 
YOUR NAME))) FLOWER-RECALL-2)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
FLOWER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (EQUAL MESSAGE (QUOTE (ERASE))) 
FLOWER-ERASE-4)) ((AND (EQ (FIRST MESSAGE) (QUOTE SET)) (AND (EQ (CADR MESSAGE) (QUOTE 
YOUR)) (COND ((AND (AND (EQ (CADDR MESSAGE) (QUOTE NUMBER-OF-PETALS)) (AND (EQ (CADDDR 
MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))) FLOWER-SET-5)) ((AND (AND (EQUAL (CADDR 
MESSAGE) (QUOTE (PETAL-COLORS (QUOTE (WHITE))))) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) 
(ONE-LONG (CDDDDR MESSAGE)))) FLOWER-SET-6)) ((AND (AND (EQUAL (CADDR MESSAGE) (QUOTE 
(SHADE-PATTERN NIL))) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))) 
FLOWER-SET-7)))))))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 7 FLOWER-RECALL-1 
(ORIGINAL-METHODS-OF-FLOWER FLOWER-RECALL-2 FLOWER-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
FLOWER-ERASE-4 FLOWER-SET-5 FLOWER-SET-6 FLOWER-SET-7))) (QUOTE FLOWER)) 
(REMPROP (QUOTE FLOWER) (QUOTE ACTOR-LOAD)) 
(ASK OBJECT ADD FLOWER TO YOUR LIST OF OFFSPRING) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE ROCKET) (QUOTE |DSK:KEN;POLY DEPEND|)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE POLY) (QUOTE |DSK:KEN;POLY DEPEND|)) 
(PROGN (DEFPROP |POLY(SET YOUR HOW-TO-DRAW TO NIL)| (OBJECT-SET-27 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |POLY(SET YOUR HOW-TO-DRAW TO NIL)| (SET YOUR HOW-TO-DRAW TO NIL) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |POLY(SET YOUR ANGLE TO ?)| (POLY-SET-4 SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |POLY(SET YOUR ANGLE TO ?)| (SET YOUR ANGLE TO ?) MESSAGE-PATTERN)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE COLOR-POLY) (QUOTE |DSK:KEN;POLY DEPEND|)) 
(PROGN (DEFPROP |COLOR-POLY(SET YOUR HOW-TO-DRAW TO NIL)| (OBJECT-SET-27 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |COLOR-POLY(SET YOUR HOW-TO-DRAW TO NIL)| (SET YOUR HOW-TO-DRAW 
TO NIL) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |COLOR-POLY(SET YOUR ANGLE TO ?)| (COLOR-POLY-SET-4 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |COLOR-POLY(SET YOUR ANGLE TO ?)| (SET YOUR ANGLE TO ?) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |COLOR-POLY(SET YOUR APPEARANCE-CHANGED TO T)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |COLOR-POLY(SET YOUR APPEARANCE-CHANGED TO T)| (SET YOUR 
APPEARANCE-CHANGED TO T) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |COLOR-POLY(SET YOUR HOW-TO-DRAW TO ?)| (OBJECT-SET-27 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |COLOR-POLY(SET YOUR HOW-TO-DRAW TO ?)| (SET YOUR HOW-TO-DRAW TO 
?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |COLOR-POLY(SET YOUR COLORS TO ?)| (COLOR-POLY-SET-5 OBJECT-SET-25 
SOMETHING-SET-14) MATCHING-METHODS) (DEFPROP |COLOR-POLY(SET YOUR COLORS TO ?)| (SET YOUR 
COLORS TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |COLOR-POLY(RECALL YOUR HOW-TO-DRAW)| (OBJECT-RECALL-23 SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |COLOR-POLY(RECALL YOUR HOW-TO-DRAW)| (RECALL YOUR HOW-TO-DRAW) 
MESSAGE-PATTERN)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE FLOWER) (QUOTE |DSK:KEN;POLY DEPEND|)) 
(PROGN (DEFPROP |FLOWER(ERASE BY CLEARING AREA)| (OBJECT-ERASE-22) MATCHING-METHODS) 
(DEFPROP |FLOWER(ERASE BY CLEARING AREA)| (ERASE BY CLEARING AREA) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |FLOWER(SET YOUR HOW-TO-DRAW TO NIL)| (OBJECT-SET-27 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |FLOWER(SET YOUR HOW-TO-DRAW TO NIL)| (SET YOUR HOW-TO-DRAW TO 
NIL) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |FLOWER(SET YOUR NUMBER-OF-PETALS TO ?)| (FLOWER-SET-5 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |FLOWER(SET YOUR NUMBER-OF-PETALS TO ?)| (SET YOUR 
NUMBER-OF-PETALS TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |FLOWER(SET YOUR (PETAL-COLORS '(WHITE)) TO ?)| (FLOWER-SET-6 
SOMETHING-SET-14) MATCHING-METHODS) (DEFPROP |FLOWER(SET YOUR (PETAL-COLORS '(WHITE)) TO ?)| 
(SET YOUR (PETAL-COLORS (QUOTE (WHITE))) TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |FLOWER(SET YOUR (SHADE-PATTERN NIL) TO ?)| (FLOWER-SET-7 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |FLOWER(SET YOUR (SHADE-PATTERN NIL) TO ?)| (SET YOUR 
(SHADE-PATTERN NIL) TO ?) MESSAGE-PATTERN)) 