
(INCLUDE |ai:ken;declar >|) 
(DEFCOMMENT SCREEN) 
(DEFINE-FORM (DIRECTOR-WIPE) (ASK SCREEN WIPE)) 
(DEFINE-SYNONYM DWIPE DIRECTOR-WIPE) 
(DEFINE-FORM (DIRECTOR-CLEARSCREEN) (ASK SCREEN ASK EACH OF YOUR VISIBLE-OBJECTS TO SET YOUR 
VISIBILITY TO NIL) (ASK SCREEN SET YOUR VISIBLE-OBJECTS TO NIL) (CLEARSCREEN)) 
(DEFINE-SYNONYM DCS DIRECTOR-CLEARSCREEN) 
(DECLARE (SPECIAL SCREEN-RECALL-1 SCREEN-RECALL-2 
SCREEN-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 SCREEN-RECALL-4 SCREEN-RECALL-5 SCREEN-SET-6 
SCREEN-SET-7 SCREEN-PERFORM-8 SCREEN-SHOWING-9 SCREEN-HIDING-10 SCREEN-SAVE-11 
SCREEN-WIPE-12 SCREEN-CLEAR-13 SCREEN-START-14 SCREEN-RESTART-15)) 
(SETQ SCREEN-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SOMETHING))) 
(DEFPROP SCREEN-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ SCREEN-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SCREEN))) 
(DEFPROP SCREEN-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ SCREEN-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE (NIL 
(MODE . NORMAL))))) 
(DEFPROP SCREEN-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SCREEN-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ SCREEN-RECALL-4 (QUOTE SCREEN-RECALL-4)) 
(DEFPROP SCREEN-RECALL-4 (RECALL YOUR WIDTH) METHOD-PATTERN) 
(DEFUN SCREEN-RECALL-4 NIL (FIRST (TVSIZE))) 
(SETQ SCREEN-RECALL-5 (QUOTE SCREEN-RECALL-5)) 
(DEFPROP SCREEN-RECALL-5 (RECALL YOUR HEIGHT) METHOD-PATTERN) 
(DEFUN SCREEN-RECALL-5 NIL (SECOND (TVSIZE))) 
(SETQ SCREEN-SET-6 (QUOTE SCREEN-SET-6)) 
(DEFPROP SCREEN-SET-6 (SET YOUR HEIGHT TO ?) METHOD-PATTERN) 
(DEFUN SCREEN-SET-6 NIL ((LAMBDA (NEW-HEIGHT) (TVSIZE (LET ((:SELF (ACTOR-OF (QUOTE 
SCREEN))) (:MESSAGE (QUOTE (RECALL YOUR WIDTH)))) (COMPILED-ASK (QUOTE 
|SCREEN(RECALL YOUR WIDTH)|) (QUOTE SCREEN))) NEW-HEIGHT)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SCREEN-SET-7 (QUOTE SCREEN-SET-7)) 
(DEFPROP SCREEN-SET-7 (SET YOUR WIDTH TO ?) METHOD-PATTERN) 
(DEFUN SCREEN-SET-7 NIL ((LAMBDA (NEW-WIDTH) (TVSIZE NEW-WIDTH (LET ((:SELF (ACTOR-OF (QUOTE 
SCREEN))) (:MESSAGE (QUOTE (RECALL YOUR HEIGHT)))) (COMPILED-ASK (QUOTE 
|SCREEN(RECALL YOUR HEIGHT)|) (QUOTE SCREEN))))) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SCREEN-PERFORM-8 (QUOTE SCREEN-PERFORM-8)) 
(DEFPROP SCREEN-PERFORM-8 (PERFORM TURTLE ACTIONS %) METHOD-PATTERN) 
(DEFUN SCREEN-PERFORM-8 NIL ((LAMBDA (TURTLE-COMMANDS) (LET ((MODE (LET ((:MESSAGE (QUOTE 
(RECALL YOUR MODE)))) (COMPILED-ASK (QUOTE |SCREEN(RECALL YOUR MODE)|) (QUOTE SCREEN))))) 
(COND ((EQ MODE (QUOTE NORMAL)) (MAPC (QUOTE EVAL) TURTLE-COMMANDS)) ((EQ MODE (QUOTE 
SILENT)) NIL) ((EQ (FIRST MODE) (QUOTE SILENT-BUT-TELL)) (LET ((:SELF (ACTOR-OF (SECOND 
MODE))) (:MESSAGE (CONS (QUOTE ADD) (CONS (CONS (QUOTE PROGN) TURTLE-COMMANDS) (QUOTE (TO 
YOUR LIST OF TURTLE-COMMANDS)))))) (COMPILED-ASK (QUOTE 
|SCREEN(ADD (PROGN %) TO YOUR LIST OF TURTLE-COMMANDS)|) (QUOTE SCREEN))))))) (CDDDR 
:MESSAGE))) 
(SETQ SCREEN-SHOWING-9 (QUOTE SCREEN-SHOWING-9)) 
(DEFPROP SCREEN-SHOWING-9 (SHOWING ?) METHOD-PATTERN) 
(DEFUN SCREEN-SHOWING-9 NIL ((LAMBDA (OBJECT) (LET ((:MESSAGE (CONS (QUOTE ADD) (CONS OBJECT 
(QUOTE (TO YOUR LIST OF VISIBLE-OBJECTS)))))) (COMPILED-ASK (QUOTE 
|SCREEN(ADD ? TO YOUR LIST OF VISIBLE-OBJECTS)|) (QUOTE SCREEN)))) (CADR :MESSAGE))) 
(SETQ SCREEN-HIDING-10 (QUOTE SCREEN-HIDING-10)) 
(DEFPROP SCREEN-HIDING-10 (HIDING ?) METHOD-PATTERN) 
(DEFUN SCREEN-HIDING-10 NIL ((LAMBDA (OBJECT) (LET ((:MESSAGE (CONS (QUOTE REMOVE) (CONS 
OBJECT (QUOTE (FROM YOUR LIST OF VISIBLE-OBJECTS)))))) (COMPILED-ASK (QUOTE 
|SCREEN(REMOVE ? FROM YOUR LIST OF VISIBLE-OBJECTS)|) (QUOTE SCREEN)))) (CADR :MESSAGE))) 
(SETQ SCREEN-SAVE-11 (QUOTE SCREEN-SAVE-11)) 
(DEFPROP SCREEN-SAVE-11 (SAVE SCREEN) METHOD-PATTERN) 
(DEFUN SCREEN-SAVE-11 NIL (DO ((APPEARANCES NIL) (OBJECTS (LET ((:MESSAGE (QUOTE (RECALL 
YOUR VISIBLE-OBJECTS)))) (COMPILED-ASK (QUOTE |SCREEN(RECALL YOUR VISIBLE-OBJECTS)|) (QUOTE 
SCREEN))) (REST OBJECTS))) ((NULL OBJECTS) APPEARANCES) (LET ((APPEARANCE (LET ((:SELF 
(ACTOR-OF (FIRST OBJECTS))) (:MESSAGE (QUOTE (CREATE NEW APPEARANCE)))) (COMPILED-ASK (QUOTE 
|OBJECT(CREATE NEW APPEARANCE)|) (QUOTE OBJECT))))) (AND APPEARANCE (SETQ APPEARANCES (CONS 
APPEARANCE APPEARANCES)))))) 
(SETQ SCREEN-WIPE-12 (QUOTE SCREEN-WIPE-12)) 
(DEFPROP SCREEN-WIPE-12 (WIPE) METHOD-PATTERN) 
(DEFUN SCREEN-WIPE-12 NIL (WIPE) (LET ((:SELF (ACTOR-OF (QUOTE SCREEN))) (:MESSAGE (QUOTE 
(ASK EACH OF YOUR VISIBLE-OBJECTS TO SHOW)))) (COMPILED-ASK (QUOTE 
|OBJECT(ASK EACH OF YOUR VISIBLE-OBJECTS TO SHOW)|) (QUOTE OBJECT))) NO-VALUE) 
(SETQ SCREEN-CLEAR-13 (QUOTE SCREEN-CLEAR-13)) 
(DEFPROP SCREEN-CLEAR-13 (CLEAR) METHOD-PATTERN) 
(DEFUN SCREEN-CLEAR-13 NIL (DIRECTOR-CLEARSCREEN)) 
(SETQ SCREEN-START-14 (QUOTE SCREEN-START-14)) 
(DEFPROP SCREEN-START-14 (START DISPLAY) METHOD-PATTERN) 
(DEFUN SCREEN-START-14 NIL (DIRECTOR-STARTDISPLAY) (DIRECTOR-CLEARSCREEN)) 
(SETQ SCREEN-RESTART-15 (QUOTE SCREEN-RESTART-15)) 
(DEFPROP SCREEN-RESTART-15 (RESTART DISPLAY) METHOD-PATTERN) 
(DEFUN SCREEN-RESTART-15 NIL (DIRECTOR-STARTDISPLAY) (DIRECTOR-WIPE)) 
(DEFUN ORIGINAL-METHODS-OF-SCREEN (MESSAGE ACTOR) (COND ((AND (EQ (FIRST MESSAGE) (QUOTE 
RECALL)) (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (COND ((AND (EQUAL (CDDR MESSAGE) (QUOTE 
(NAME))) SCREEN-RECALL-2)) ((AND (EQUAL (CDDR MESSAGE) (QUOTE (WIDTH))) SCREEN-RECALL-4)) 
((AND (EQUAL (CDDR MESSAGE) (QUOTE (HEIGHT))) SCREEN-RECALL-5)))))) ((AND (EQUAL MESSAGE 
(QUOTE (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
SCREEN-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (EQ (FIRST MESSAGE) (QUOTE SET)) (AND 
(EQ (CADR MESSAGE) (QUOTE YOUR)) (COND ((AND (AND (EQ (CADDR MESSAGE) (QUOTE HEIGHT)) (AND 
(EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))) SCREEN-SET-6)) ((AND (AND (EQ 
(CADDR MESSAGE) (QUOTE WIDTH)) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR 
MESSAGE)))) SCREEN-SET-7)))))) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE PERFORM)) (AND (EQ 
(CADR MESSAGE) (QUOTE TURTLE)) (EQ (CADDR MESSAGE) (QUOTE ACTIONS)))) SCREEN-PERFORM-8)) 
((AND (AND (EQ (FIRST MESSAGE) (QUOTE SHOWING)) (ONE-LONG (REST MESSAGE))) 
SCREEN-SHOWING-9)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE HIDING)) (ONE-LONG (REST MESSAGE))) 
SCREEN-HIDING-10)) ((AND (EQUAL MESSAGE (QUOTE (SAVE SCREEN))) SCREEN-SAVE-11)) ((AND (EQUAL 
MESSAGE (QUOTE (WIPE))) SCREEN-WIPE-12)) ((AND (EQUAL MESSAGE (QUOTE (CLEAR))) 
SCREEN-CLEAR-13)) ((AND (EQUAL MESSAGE (QUOTE (START DISPLAY))) SCREEN-START-14)) ((AND 
(EQUAL MESSAGE (QUOTE (RESTART DISPLAY))) SCREEN-RESTART-15)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 15 SCREEN-RECALL-1 
(ORIGINAL-METHODS-OF-SCREEN SCREEN-RECALL-2 SCREEN-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
SCREEN-RECALL-4 SCREEN-RECALL-5 SCREEN-SET-6 SCREEN-SET-7 SCREEN-PERFORM-8 SCREEN-SHOWING-9 
SCREEN-HIDING-10 SCREEN-SAVE-11 SCREEN-WIPE-12 SCREEN-CLEAR-13 SCREEN-START-14 
SCREEN-RESTART-15))) (QUOTE SCREEN)) 
(REMPROP (QUOTE SCREEN) (QUOTE ACTOR-LOAD)) 
(ASK SOMETHING ADD SCREEN TO YOUR LIST OF OFFSPRING) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE SCREEN) (QUOTE |DSK:KEN;SCREEN DEPEND|)) 
(PROGN (DEFPROP |SCREEN(SHOWING ?)| (SCREEN-SHOWING-9) MATCHING-METHODS) (DEFPROP 
|SCREEN(SHOWING ?)| (SHOWING ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(RECALL YOUR MODE)| (SOMETHING-RECALL-16) MATCHING-METHODS) (DEFPROP 
|SCREEN(RECALL YOUR MODE)| (RECALL YOUR MODE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(RECALL YOUR WIDTH)| (SCREEN-RECALL-4 SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SCREEN(RECALL YOUR WIDTH)| (RECALL YOUR WIDTH) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(RECALL YOUR HEIGHT)| (SCREEN-RECALL-5 SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SCREEN(RECALL YOUR HEIGHT)| (RECALL YOUR HEIGHT) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(RECALL YOUR VISIBLE-OBJECTS)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SCREEN(RECALL YOUR VISIBLE-OBJECTS)| (RECALL YOUR 
VISIBLE-OBJECTS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(HIDING ?)| (SCREEN-HIDING-10) MATCHING-METHODS) (DEFPROP 
|SCREEN(HIDING ?)| (HIDING ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(PERFORM TURTLE ACTIONS ? (THINGUP) (SETTURTLE '?) (THINGDOWN) ?)| 
(SCREEN-PERFORM-8) MATCHING-METHODS) (DEFPROP 
|SCREEN(PERFORM TURTLE ACTIONS ? (THINGUP) (SETTURTLE '?) (THINGDOWN) ?)| (PERFORM TURTLE 
ACTIONS ? (THINGUP) (SETTURTLE (QUOTE ?)) (THINGDOWN) ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP 
|SCREEN(PERFORM TURTLE ACTIONS (PENUP) (SETTURTLE '?) (ERASERDOWN) (FILLWINDOW (PLUS :TVSTEP (
MIN (DISTANCE-TO-NEAREST-WALL) ?))))| (SCREEN-PERFORM-8) MATCHING-METHODS) (DEFPROP 
|SCREEN(PERFORM TURTLE ACTIONS (PENUP) (SETTURTLE '?) (ERASERDOWN) (FILLWINDOW (PLUS :TVSTEP (
MIN (DISTANCE-TO-NEAREST-WALL) ?))))| (PERFORM TURTLE ACTIONS (PENUP) (SETTURTLE (QUOTE ?)) 
(ERASERDOWN) (FILLWINDOW (PLUS :TVSTEP (MIN (DISTANCE-TO-NEAREST-WALL) ?)))) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(ADD ? TO YOUR LIST OF VISIBLE-OBJECTS)| (SOMETHING-ADD-21) 
MATCHING-METHODS) (DEFPROP |SCREEN(ADD ? TO YOUR LIST OF VISIBLE-OBJECTS)| (ADD ? TO YOUR 
LIST OF VISIBLE-OBJECTS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(ADD (PROGN %) TO YOUR LIST OF TURTLE-COMMANDS)| (SOMETHING-ADD-21) 
MATCHING-METHODS) (DEFPROP |SCREEN(ADD (PROGN %) TO YOUR LIST OF TURTLE-COMMANDS)| (ADD 
(PROGN %) TO YOUR LIST OF TURTLE-COMMANDS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(REMOVE ? FROM YOUR LIST OF VISIBLE-OBJECTS)| (SOMETHING-REMOVE-23) 
MATCHING-METHODS) (DEFPROP |SCREEN(REMOVE ? FROM YOUR LIST OF VISIBLE-OBJECTS)| (REMOVE ? 
FROM YOUR LIST OF VISIBLE-OBJECTS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(SET YOUR MODE TO ?)| (SOMETHING-SET-14) MATCHING-METHODS) (DEFPROP 
|SCREEN(SET YOUR MODE TO ?)| (SET YOUR MODE TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(SET YOUR MODE TO (SILENT-BUT-TELL TURTLE-COMMAND-HOLDER))| 
(SOMETHING-SET-14) MATCHING-METHODS) (DEFPROP 
|SCREEN(SET YOUR MODE TO (SILENT-BUT-TELL TURTLE-COMMAND-HOLDER))| (SET YOUR MODE TO 
(SILENT-BUT-TELL TURTLE-COMMAND-HOLDER)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(SET YOUR MODE TO NORMAL)| (SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |SCREEN(SET YOUR MODE TO NORMAL)| (SET YOUR MODE TO NORMAL) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(SAVE SCREEN)| (SCREEN-SAVE-11 SOMETHING-SAVE-77) MATCHING-METHODS) 
(DEFPROP |SCREEN(SAVE SCREEN)| (SAVE SCREEN) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SCREEN(WIPE)| (SCREEN-WIPE-12) MATCHING-METHODS) (DEFPROP |SCREEN(WIPE)| 
(WIPE) MESSAGE-PATTERN)) 