;; -*-lisp-*- produced by Director (IN MACLISP)

(INCLUDE |ai:ken;declare >|) 
(INCLUDE |ai:ken;declar >|) 
(DEFCOMMENT POLY) 
(COMPILE-ACTORS) 
(COMMENT HERE COMES THE ACTORS THEMSELVES) 
(OR
 (GET-ACTOR (QUOTE ROCKET))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE ROCKET))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE ROCKET))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME ROCKET PRIVATE)      (STATE (0.0 0.0 0.0))      (VISIBILITY NIL)
       (WHOLE THE-CAST PRIVATE)   (ABSOLUTE-SIZE 100.000001) (SIZE 100.000001)
       (POSITION (0.0 0.0))       (XCOR 0.0)                 (YCOR 0.0)
       (HEADING 0.0)              (DISTANCE-FROM-WHOLE 0.0)  (HEADING-FROM-WHOLE 
0.0)
       (RELATIVE-HEADING 0.0)     (ARG-WHICH-IS-SIZE-IF-ANY 1)
       (DRAW-PROCEDURE DRAW-ROCKET)                          (DRAWING-ARGS (SIZE))
       (NON-SHAPE-DRAWING-ARGS NIL)
       (APPEARANCE-VARIABLES (HOW-TO-DRAW COLORS))
       (VARIABLES-TO-COPY-UPON-CREATION (HOW-TO-DRAW COLORS STATE VISIBILITY)))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE PERFORMER))) 
(REMPROP (QUOTE ROCKET) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE POLY))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE POLY))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE POLY))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME POLY PRIVATE)                      (STATE (0.0 0.0 0.0))
       (VISIBILITY NIL)                         (WHOLE THE-CAST PRIVATE)
       (ABSOLUTE-SIZE 100.000001)               (SIZE 100.000001)
       (POSITION (0.0 0.0))                     (XCOR 0.0)
       (YCOR 0.0)                               (HEADING 0.0)
       (DISTANCE-FROM-WHOLE 0.0)                (HEADING-FROM-WHOLE 0.0)
       (RELATIVE-HEADING 0.0)                   (ANGLE 60)
       (ARG-WHICH-IS-SIZE-IF-ANY 1)             (DRAW-PROCEDURE DRAW-POLY)
       (DRAWING-ARGS (SIZE ANGLE NUMBER-OF-SIDES))
       (NON-SHAPE-DRAWING-ARGS NIL)
       (APPEARANCE-VARIABLES (HOW-TO-DRAW COLORS))
       (VARIABLES-TO-COPY-UPON-CREATION (HOW-TO-DRAW COLORS STATE VISIBILITY)))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0466 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0467 |(SET YOUR ANGLE TO ?)|))
  (QUOTE (NORMAL-METHOD D0468 |(SET YOUR NUMBER-OF-SIDES TO ?)|))
  (QUOTE PERFORMER))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE POLY))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE POLY))))) 
(REMPROP (QUOTE POLY) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE COLOR-POLY))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE COLOR-POLY))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE COLOR-POLY))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME COLOR-POLY PRIVATE)                (STATE (0.0 0.0 0.0))
       (VISIBILITY NIL)                         (WHOLE THE-CAST PRIVATE)
       (ABSOLUTE-SIZE 100.000001)               (SIZE 100.000001)
       (POSITION (0.0 0.0))                     (XCOR 0.0)
       (YCOR 0.0)                               (HEADING 0.0)
       (DISTANCE-FROM-WHOLE 0.0)                (HEADING-FROM-WHOLE 0.0)
       (RELATIVE-HEADING 0.0)                   (ANGLE 60)
       (ARG-WHICH-IS-SIZE-IF-ANY 1)             (DRAW-PROCEDURE DRAW-COLOR-POLY)
       (DRAWING-ARGS (SIZE ANGLE (COLORS) NUMBER-OF-SIDES))
       (NON-SHAPE-DRAWING-ARGS (COLORS))
       (APPEARANCE-VARIABLES (HOW-TO-DRAW COLORS))
       (VARIABLES-TO-COPY-UPON-CREATION (HOW-TO-DRAW COLORS STATE VISIBILITY)))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0469 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0470 |(SET YOUR ANGLE TO ?)|))
  (QUOTE (NORMAL-METHOD D0471 |(SET YOUR NUMBER-OF-SIDES TO ?)|))
  (QUOTE (NORMAL-METHOD D0472 |(SET YOUR COLORS TO ?)|))
  (QUOTE PERFORMER))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE COLOR-POLY))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE COLOR-POLY))))) 
(REMPROP (QUOTE COLOR-POLY) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE FLOWER))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE FLOWER))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE FLOWER))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME FLOWER PRIVATE)      (STATE (0.0 0.0 0.0))      (VISIBILITY NIL)
       (WHOLE THE-CAST PRIVATE)   (ABSOLUTE-SIZE 100.000001) (SIZE 100.000001)
       (POSITION (0.0 0.0))       (XCOR 0.0)                 (YCOR 0.0)
       (HEADING 0.0)              (DISTANCE-FROM-WHOLE 0.0)  (HEADING-FROM-WHOLE 
0.0)
       (RELATIVE-HEADING 0.0)     (NUMBER-OF-PETALS 3)       (PETAL-COLORS (WHITE))
       (SHADE-PATTERN NIL)        (ERASABILITY NIL)
       (ARG-WHICH-IS-SIZE-IF-ANY 1)
       (DRAW-PROCEDURE DRAW-FLOWER)
       (DRAWING-ARGS (SIZE NUMBER-OF-PETALS (PETAL-COLORS) (SHADE-PATTERN)))
       (NON-SHAPE-DRAWING-ARGS (PETAL-COLORS SHADE-PATTERN))
       (APPEARANCE-VARIABLES (HOW-TO-DRAW COLORS PETAL-COLORS SHADE-PATTERN))
       (VARIABLES-TO-COPY-UPON-CREATION
        (HOW-TO-DRAW COLORS PETAL-COLORS SHADE-PATTERN STATE VISIBILITY)))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0473 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0474 (ERASE)))
  (QUOTE (NORMAL-METHOD D0475 |(SET YOUR NUMBER-OF-PETALS TO ?)|))
  (QUOTE (NORMAL-METHOD D0476 |(SET YOUR PETAL-COLORS TO ?)|))
  (QUOTE (NORMAL-METHOD D0477 |(SET YOUR SHADE-PATTERN TO ?)|))
  (QUOTE PERFORMER))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE FLOWER))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE FLOWER))))) 
(REMPROP (QUOTE FLOWER) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE WINDOW))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE WINDOW))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE WINDOW))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME WINDOW PRIVATE)      (STATE (0.0 0.0 0.0))      (VISIBILITY NIL)
       (WHOLE THE-CAST PRIVATE)   (ABSOLUTE-SIZE 100.000001) (SIZE 100.000001)
       (POSITION (0.0 0.0))       (XCOR 0.0)                 (YCOR 0.0)
       (HEADING 0.0)              (DISTANCE-FROM-WHOLE 0.0)  (HEADING-FROM-WHOLE 
0.0)
       (RELATIVE-HEADING 0.0)     (WINDOW NO-WINDOW-SET)
       (APPEARANCE-VARIABLES (STATE WINDOW)))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0478 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0479 |({or ERASE DISPLAY})|))
  (QUOTE (NORMAL-METHOD D0480 |(SET YOUR WINDOW TO ?)|))
  (QUOTE PERFORMER))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE WINDOW))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE WINDOW))))) 
(REMPROP (QUOTE WINDOW) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE TEXT))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE TEXT))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE TEXT))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME TEXT PRIVATE)                      (STATE (0.0 0.0 0.0))
       (VISIBILITY NIL)                         (WHOLE THE-CAST PRIVATE)
       (ABSOLUTE-SIZE 100.000001)               (SIZE 100.000001)
       (POSITION (0.0 0.0))                     (XCOR 0.0)
       (YCOR 0.0)                               (HEADING 0.0)
       (DISTANCE-FROM-WHOLE 0.0)                (HEADING-FROM-WHOLE 0.0)
       (RELATIVE-HEADING 0.0)                   (STRING |No string given|)
       (FONT TVFONT)                            (LENGTH 0.0)
       (APPEARANCE-VARIABLES (STRING FONT)))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0481 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0482 |({or DISPLAY ERASE})|))
  (QUOTE (NORMAL-METHOD D0483 |(SET YOUR {or STRING FONT} TO ?)|))
  (QUOTE (NORMAL-METHOD D0484 (RECALL YOUR WIDTH)))
  (QUOTE (NORMAL-METHOD D0486 (RECALL YOUR HEIGHT)))
  (QUOTE PERFORMER))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE TEXT))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE TEXT))))) 
(REMPROP (QUOTE TEXT) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE FONT))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE FONT))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE FONT))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS (QUOTE (((NAME FONT PRIVATE)))) (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0488 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0489 |(RECALL YOUR (LENGTH-FOR ?))|))
  (QUOTE (NORMAL-METHOD D0490 (RECALL YOUR HEIGHT)))
  (QUOTE SOMETHING))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE FONT))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE FONT))))) 
(REMPROP (QUOTE FONT) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE TIMES-ROMAN-FONT))
 (PLACE-ACTOR-ON-NAME
  (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL)
  (QUOTE TIMES-ROMAN-FONT))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE TIMES-ROMAN-FONT))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME TIMES-ROMAN-FONT PRIVATE))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE FONT))) 
(REMPROP (QUOTE TIMES-ROMAN-FONT) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE TVFONT))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE TVFONT))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE TVFONT))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME TVFONT PRIVATE) (SIZE 7.0))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE TIMES-ROMAN-FONT))) 
(REMPROP (QUOTE TVFONT) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE TR12B))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE TR12B))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE TR12B))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME TR12B PRIVATE) (SIZE 12.0))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE TIMES-ROMAN-FONT))) 
(REMPROP (QUOTE TR12B) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE TR18))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE TR18))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE TR18))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME TR18 PRIVATE) (SIZE 18.0))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE TIMES-ROMAN-FONT))) 
(REMPROP (QUOTE TR18) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE FONT-SERIES))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE FONT-SERIES))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE FONT-SERIES))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE (((NAME FONT-SERIES PRIVATE) (SERIES TIMES-ROMAN))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE (METHOD-SELECTOR D0491 TO-BE-FILLED-IN-WITH-SECOND-TO-LAST-CONS))
  (QUOTE (NORMAL-METHOD D0492 |(RECALL YOUR (FONT-OF-SIZE ?))|))
  (QUOTE (NORMAL-METHOD D0493 |(SET YOUR FONTS TO ?)|))
  (QUOTE (NORMAL-METHOD D0494 |(SET YOUR SIZE TO ?)|))
  (QUOTE SOMETHING))) 
(REPLACE-THIRD
 (SECOND (METHODS-OF (ACTOR-OF (QUOTE FONT-SERIES))))
 (SECOND-TO-LAST-CONS (METHODS-OF (ACTOR-OF (QUOTE FONT-SERIES))))) 
(REMPROP (QUOTE FONT-SERIES) (QUOTE ACTOR-LOAD)) 
(OR
 (GET-ACTOR (QUOTE TIMES-ROMAN))
 (PLACE-ACTOR-ON-NAME (LIST (QUOTE DIRECTOR-SYMBOL-FOR-ACTOR) NIL) (QUOTE TIMES-ROMAN))) 
(REPLACE-REST
 (ACTOR-OF (QUOTE TIMES-ROMAN))
 (LIST
  NIL
  (CONS
   (QUOTE VALUE-METHOD)
   (CONS
    (QUOTE
     (((NAME TIMES-ROMAN PRIVATE) (FONTS (TVFONT TR12B TR18)) (FONT TVFONT) (SIZE 7))))
    (QUOTE ((INTERNAL-RECALL-YOUR-VARIABLE)))))
  (QUOTE FONT-SERIES))) 
(REMPROP (QUOTE TIMES-ROMAN) (QUOTE ACTOR-LOAD)) 
(COMMENT THE FOLLOWING ARE THE ACTORS NEEDED FOR THE FOLLOWING METHODS) 
(ACTOR-OF (QUOTE THE-TURTLE)) 
(ACTOR-OF (QUOTE THE-CAST)) 
(COMMENT NOW FOR METHOD HELPERS (IE FUNCTIONS WHICH DO TRANSMISSIONS)) 
(DEFINE-FORM
 (RASTER-TO-RELATIVE-TO-THE-CAST RASTER-SIZE)
 (*$
  RASTER-SIZE
  :TVSTEP
  (//$
   1000.0
   (LET
    ((MYSELF (ACTOR-OF (QUOTE THE-CAST))) (*MESSAGE '(RECALL YOUR SIZE)))
    (QUICK-COMPILED-ASK
     '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
     '#,(ACTOR-OF (QUOTE THE-CAST))))))) 
(DEFINE-FORM
 (DISPLAY-OR-ERASE-TEXT STATE LENGTH FONT STRING TEXT-ACTOR)
 (PENUP)
 (DIRECTOR-SETTURTLE STATE)
 (LEFT 90)
 (FORWARD (*$ LENGTH :TVSTEP 0.5))
 (RIGHT 90)
 (DELY
  (*$
   (OR
    (GET FONT 'HEIGHT)
    (LET
     ((FONT-FILE (GET FONT 'FONT-AUTOLOAD-FILE)))
     (COND (FONT-FILE (DIRECTOR-LOAD FONT-FILE '(TO LOAD IN ,FONT)))
           (T
            (SHOULDNT-HAPPEN
             'DISPLAY-OR-ERASE-TEXT
             '(|dont know where to find winfon file for| ,FONT))))
     (GET FONT 'HEIGHT)))
   :TVSTEP
   0.5))
 (COND ((STATUS FEATURES COLOR)
        (COND ((EQUAL *MESSAGE '(ERASE)) (PENCOLOR :ERASERCOLOR))
              (T
               (PENCOLOR
                (FIRST
                 (LET
                  ((MYSELF (ACTOR-OF TEXT-ACTOR)) (*MESSAGE '(RECALL YOUR COLORS)))
                  (QUICK-COMPILED-ASK
                   '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
                   '#,(ACTOR-OF (QUOTE TEXT))))))))))
 (FONTPRINC STRING FONT)) 
(COMMENT NOW THE DEFINITIONS OF THE METHODS OF THE ABOVE ACTORS) 
(DEFUN D0468 NIL
  ((LAMBDA (NEW-VALUE)
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE '(!,*MESSAGE)))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR NUMBER-OF-SIDES TO ?)| 0) POLY)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE POLY))))
      MYSELF
      *METHOD-BEING-RUN)
     (LET
      ((*MESSAGE '(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO NIL)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO ?)| 0) PERFORMER)
       '#,(ACTOR-OF (QUOTE POLY))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR NUMBER-OF-SIDES TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE NUMBER-OF-SIDES))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR NUMBER-OF-SIDES TO ?)| (SET YOUR NUMBER-OF-SIDES TO ?) PATTERN) 
(DEFUN D0467 NIL
  ((LAMBDA (NEW-VALUE)
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE '(!,*MESSAGE)))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR ANGLE TO ?)| 0) POLY)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE POLY))))
      MYSELF
      *METHOD-BEING-RUN)
     (LET
      ((*MESSAGE '(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO NIL)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO ?)| 0) PERFORMER)
       '#,(ACTOR-OF (QUOTE POLY))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR ANGLE TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE ANGLE))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR ANGLE TO ?)| (SET YOUR ANGLE TO ?) PATTERN) 
(DEFUN D0466 (MESSAGE)
  (AND
   (EQ (CAR MESSAGE) (QUOTE SET))
   (AND
    (EQ (CADR MESSAGE) (QUOTE YOUR))
    (COND ((AND
            (AND
             (EQ (CADDR MESSAGE) (QUOTE ANGLE))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
            (METHOD-IF-NOT-HIDDEN
             '#,(METHOD-AT-POSITION (|(SET YOUR ANGLE TO ?)| 0) POLY))))
          ((AND
            (AND
             (EQ (CADDR MESSAGE) (QUOTE NUMBER-OF-SIDES))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
            (METHOD-IF-NOT-HIDDEN
             '#,(METHOD-AT-POSITION (|(SET YOUR NUMBER-OF-SIDES TO ?)| 0) POLY)))))))) 
(DEFUN D0472 NIL
  ((LAMBDA (NEW-VALUE)
     (LET
      ((HOW-TO-DRAW
        (LET
         ((*MESSAGE '(RECALL YOUR HOW-TO-DRAW)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION ((RECALL YOUR HOW-TO-DRAW) 0) PERFORMER)
          '#,(ACTOR-OF (QUOTE COLOR-POLY))))))
      (RUN-WITH-METHOD-INVISIBLE
       (LET
        ((*MESSAGE '(!,*MESSAGE)))
        (COMPILED-ASK
         '#,(LIST
             (METHOD-AT-POSITION (|(SET YOUR COLORS TO ?)| 0) COLOR-POLY)
             (METHOD-AT-POSITION (|(SET YOUR COLORS TO ?)| 0) PERFORMER))
         '#,(ACTOR-OF (QUOTE COLOR-POLY))))
       MYSELF
       *METHOD-BEING-RUN)
      (LET
       ((*MESSAGE
         '(SET
           YOUR
           HOW-TO-DRAW
           TO
           ,(AND HOW-TO-DRAW (REPLACE-NTH 2 HOW-TO-DRAW (MAKE-INNER-DRAWER))))))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION (|(SET YOUR HOW-TO-DRAW TO ?)| 0) PERFORMER)
        '#,(ACTOR-OF (QUOTE COLOR-POLY)))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN D0471 NIL
  ((LAMBDA (NEW-VALUE)
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE '(!,*MESSAGE)))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR NUMBER-OF-SIDES TO ?)| 0) COLOR-POLY)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE COLOR-POLY))))
      MYSELF
      *METHOD-BEING-RUN)
     (LET
      ((*MESSAGE '(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO NIL)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO ?)| 0) PERFORMER)
       '#,(ACTOR-OF (QUOTE COLOR-POLY))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN D0470 NIL
  ((LAMBDA (NEW-VALUE)
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE '(!,*MESSAGE)))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR ANGLE TO ?)| 0) COLOR-POLY)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE COLOR-POLY))))
      MYSELF
      *METHOD-BEING-RUN)
     (LET
      ((*MESSAGE '(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO NIL)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO ?)| 0) PERFORMER)
       '#,(ACTOR-OF (QUOTE COLOR-POLY))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN D0469 (MESSAGE)
  (AND
   (EQ (CAR MESSAGE) (QUOTE SET))
   (AND
    (EQ (CADR MESSAGE) (QUOTE YOUR))
    (COND ((AND
            (AND
             (EQ (CADDR MESSAGE) (QUOTE ANGLE))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
            (METHOD-IF-NOT-HIDDEN
             '#,(METHOD-AT-POSITION (|(SET YOUR ANGLE TO ?)| 0) COLOR-POLY))))
          ((AND
            (AND
             (EQ (CADDR MESSAGE) (QUOTE NUMBER-OF-SIDES))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
            (METHOD-IF-NOT-HIDDEN
             '#,(METHOD-AT-POSITION (|(SET YOUR NUMBER-OF-SIDES TO ?)| 0) COLOR-POLY))))
          ((AND
            (AND
             (EQ (CADDR MESSAGE) (QUOTE COLORS))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
            (METHOD-IF-NOT-HIDDEN
             '#,(METHOD-AT-POSITION (|(SET YOUR COLORS TO ?)| 0) COLOR-POLY)))))))) 
(DEFUN D0477 NIL
  ((LAMBDA (NEW-VALUE)
     (LET
      ((HOW-TO-DRAW
        (LET
         ((*MESSAGE '(RECALL YOUR HOW-TO-DRAW)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION ((RECALL YOUR HOW-TO-DRAW) 0) PERFORMER)
          '#,(ACTOR-OF (QUOTE FLOWER))))))
      (RUN-WITH-METHOD-INVISIBLE
       (LET
        ((*MESSAGE '(!,*MESSAGE)))
        (COMPILED-ASK
         '#,(LIST
             (METHOD-AT-POSITION (|(SET YOUR SHADE-PATTERN TO ?)| 0) FLOWER)
             (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
         '#,(ACTOR-OF (QUOTE FLOWER))))
       MYSELF
       *METHOD-BEING-RUN)
      (LET
       ((*MESSAGE
         '(SET
           YOUR
           HOW-TO-DRAW
           TO
           ,(AND HOW-TO-DRAW (REPLACE-NTH 2 HOW-TO-DRAW (MAKE-INNER-DRAWER))))))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION (|(SET YOUR HOW-TO-DRAW TO ?)| 0) PERFORMER)
        '#,(ACTOR-OF (QUOTE FLOWER)))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR SHADE-PATTERN TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE SHADE-PATTERN))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR SHADE-PATTERN TO ?)| (SET YOUR SHADE-PATTERN TO ?) PATTERN) 
(DEFUN D0476 NIL
  ((LAMBDA (NEW-VALUE)
     (LET
      ((HOW-TO-DRAW
        (LET
         ((*MESSAGE '(RECALL YOUR HOW-TO-DRAW)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION ((RECALL YOUR HOW-TO-DRAW) 0) PERFORMER)
          '#,(ACTOR-OF (QUOTE FLOWER))))))
      (RUN-WITH-METHOD-INVISIBLE
       (LET
        ((*MESSAGE '(!,*MESSAGE)))
        (COMPILED-ASK
         '#,(LIST
             (METHOD-AT-POSITION (|(SET YOUR PETAL-COLORS TO ?)| 0) FLOWER)
             (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
         '#,(ACTOR-OF (QUOTE FLOWER))))
       MYSELF
       *METHOD-BEING-RUN)
      (LET
       ((*MESSAGE
         '(SET
           YOUR
           HOW-TO-DRAW
           TO
           ,(AND HOW-TO-DRAW (REPLACE-NTH 2 HOW-TO-DRAW (MAKE-INNER-DRAWER))))))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION (|(SET YOUR HOW-TO-DRAW TO ?)| 0) PERFORMER)
        '#,(ACTOR-OF (QUOTE FLOWER)))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR PETAL-COLORS TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE PETAL-COLORS))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR PETAL-COLORS TO ?)| (SET YOUR PETAL-COLORS TO ?) PATTERN) 
(DEFUN D0475 NIL
  ((LAMBDA (NEW-VALUE)
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE '(!,*MESSAGE)))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR NUMBER-OF-PETALS TO ?)| 0) FLOWER)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE FLOWER))))
      MYSELF
      *METHOD-BEING-RUN)
     (LET
      ((*MESSAGE '(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO NIL)))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR VALIDITY-OF-HOW-TO-DRAW TO ?)| 0) PERFORMER)
       '#,(ACTOR-OF (QUOTE FLOWER))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR NUMBER-OF-PETALS TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE NUMBER-OF-PETALS))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR NUMBER-OF-PETALS TO ?)| (SET YOUR NUMBER-OF-PETALS TO ?) PATTERN) 
(DEFUN D0474 NIL
  (LET
   ((*MESSAGE '(ERASE BY CLEARING AREA)))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION ((ERASE BY CLEARING AREA) 0) PERFORMER)
    '#,(ACTOR-OF (QUOTE FLOWER))))) 
(DEFUN D0473 (MESSAGE)
  (COND ((AND
          (EQUAL MESSAGE (QUOTE (ERASE)))
          (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION ((ERASE) 0) FLOWER))))
        ((AND
          (EQ (CAR MESSAGE) (QUOTE SET))
          (AND
           (EQ (CADR MESSAGE) (QUOTE YOUR))
           (COND ((AND
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE NUMBER-OF-PETALS))
                    (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION (|(SET YOUR NUMBER-OF-PETALS TO ?)| 0) FLOWER))))
                 ((AND
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE PETAL-COLORS))
                    (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION (|(SET YOUR PETAL-COLORS TO ?)| 0) FLOWER))))
                 ((AND
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE SHADE-PATTERN))
                    (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION (|(SET YOUR SHADE-PATTERN TO ?)| 0) FLOWER))))))))
        )) 
(DEFUN D0480 NIL
  ((LAMBDA (NEW-WINDOW)
     (LET
      ((VISIBILITY
        (LET
         ((*MESSAGE '(RECALL YOUR VISIBILITY)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE WINDOW))))))
      (COND (VISIBILITY
             (LET
              ((*MESSAGE '(HIDE)))
              (QUICK-COMPILED-ASK
               '#,(METHOD-AT-POSITION ((HIDE) 0) PERFORMER)
               '#,(ACTOR-OF (QUOTE WINDOW))))))
      (RUN-WITH-METHOD-INVISIBLE
       (LET
        ((*MESSAGE '(!,*MESSAGE)))
        (COMPILED-ASK
         '#,(LIST
             (METHOD-AT-POSITION (|(SET YOUR WINDOW TO ?)| 0) WINDOW)
             (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
         '#,(ACTOR-OF (QUOTE WINDOW))))
       MYSELF
       *METHOD-BEING-RUN)
      (COND (VISIBILITY
             (LET
              ((*MESSAGE '(SHOW)))
              (QUICK-COMPILED-ASK
               '#,(METHOD-AT-POSITION ((SHOW) 0) PERFORMER)
               '#,(ACTOR-OF (QUOTE WINDOW))))))
      NEW-WINDOW))
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR WINDOW TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE WINDOW))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR WINDOW TO ?)| (SET YOUR WINDOW TO ?) PATTERN) 
(DEFUN D0479 NIL
  (PENUP)
  (SETTURTLE
   (LET
    ((*MESSAGE '(RECALL YOUR STATE)))
    (QUICK-COMPILED-ASK
     '#,(METHOD-AT-POSITION ((RECALL YOUR STATE) 0) PERFORMER)
     '#,(ACTOR-OF (QUOTE WINDOW)))))
  (XORWINDOW
   (LET
    ((*MESSAGE '(RECALL YOUR WINDOW)))
    (QUICK-COMPILED-ASK
     '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
     '#,(ACTOR-OF (QUOTE WINDOW))))
   :XCOR
   :YCOR)) 
(DEFUN |({or ERASE DISPLAY})| (OBJECT)
  (AND (MEMQ (CAR OBJECT) (QUOTE (ERASE DISPLAY))) (NULL (CDR OBJECT)))) 
(DEFPROP |({or ERASE DISPLAY})| ({or ERASE DISPLAY}) PATTERN) 
(DEFUN D0478 (MESSAGE)
  (COND ((AND
          (AND (MEMQ (CAR MESSAGE) (QUOTE (ERASE DISPLAY))) (NULL (CDR MESSAGE)))
          (METHOD-IF-NOT-HIDDEN
           '#,(METHOD-AT-POSITION (|({or ERASE DISPLAY})| 0) WINDOW))))
        ((AND
          (AND
           (EQ (CAR MESSAGE) (QUOTE SET))
           (AND
            (EQ (CADR MESSAGE) (QUOTE YOUR))
            (AND
             (EQ (CADDR MESSAGE) (QUOTE WINDOW))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))))
          (METHOD-IF-NOT-HIDDEN
           '#,(METHOD-AT-POSITION (|(SET YOUR WINDOW TO ?)| 0) WINDOW)))))) 
(DEFUN D0486 NIL
  (LET
   ((*MESSAGE '(SEQUENTIALLY (ASK YOUR FONT RECALL YOUR HEIGHT))))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(SEQUENTIALLY (ASK YOUR ? %) %)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE TEXT))))) 
(DEFUN D0484 NIL
  (LET
   ((*MESSAGE
     '(SEQUENTIALLY
       (ASK YOUR FONT RECALL YOUR (LENGTH-FOR ,(ASK MYSELF RECALL YOUR STRING))))))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(SEQUENTIALLY (ASK YOUR ? %) %)| 0) SOMETHING)
    '#,(ACTOR-OF (QUOTE TEXT))))) 
(DEFUN D0483 NIL
  ((LAMBDA (NEW-VALUE)
     (LET
      ((VISIBILITY
        (LET
         ((*MESSAGE '(RECALL YOUR VISIBILITY)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE TEXT))))))
      (AND
       VISIBILITY
       (LET
        ((*MESSAGE '(HIDE)))
        (QUICK-COMPILED-ASK
         '#,(METHOD-AT-POSITION ((HIDE) 0) PERFORMER)
         '#,(ACTOR-OF (QUOTE TEXT)))))
      (RUN-WITH-METHOD-INVISIBLE
       (LET
        ((*MESSAGE '(!,*MESSAGE)))
        (COMPILED-ASK
         '#,(LIST
             (METHOD-AT-POSITION (|(SET YOUR {or STRING FONT} TO ?)| 0) TEXT)
             (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
         '#,(ACTOR-OF (QUOTE TEXT))))
       MYSELF
       *METHOD-BEING-RUN)
      (LET
       ((*MESSAGE
         '(SET
           YOUR
           LENGTH
           TO
           ,(FWUSE-TEXT-LENGTH
             (ASK MYSELF RECALL YOUR STRING)
             (ASK MYSELF RECALL YOUR FONT)))))
       (QUICK-COMPILED-ASK
        '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
        '#,(ACTOR-OF (QUOTE TEXT))))
      (AND
       VISIBILITY
       (LET
        ((*MESSAGE '(SHOW)))
        (QUICK-COMPILED-ASK
         '#,(METHOD-AT-POSITION ((SHOW) 0) PERFORMER)
         '#,(ACTOR-OF (QUOTE TEXT))))))
     NEW-VALUE)
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR {or STRING FONT} TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (MEMQ (CADDR OBJECT) (QUOTE (STRING FONT)))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR {or STRING FONT} TO ?)| (SET YOUR {or STRING FONT} TO ?) PATTERN) 
(DEFUN D0482 NIL
  (LET
   ((MYSELF (ACTOR-OF (QUOTE THE-TURTLE)))
    (*MESSAGE
     '(PERFORM
       (DISPLAY-OR-ERASE-TEXT
        (QUOTE ,(ASK MYSELF RECALL YOUR STATE))
        ,(ASK MYSELF RECALL YOUR LENGTH)
        (QUOTE ,(ASK MYSELF RECALL YOUR FONT))
        (QUOTE ,(ASK MYSELF RECALL YOUR STRING))
        (QUOTE ,MYSELF)))))
   (QUICK-COMPILED-ASK
    '#,(METHOD-AT-POSITION (|(PERFORM %)| 0) THE-TURTLE)
    '#,(ACTOR-OF (QUOTE THE-TURTLE))))) 
(DEFUN |({or DISPLAY ERASE})| (OBJECT)
  (AND (MEMQ (CAR OBJECT) (QUOTE (DISPLAY ERASE))) (NULL (CDR OBJECT)))) 
(DEFPROP |({or DISPLAY ERASE})| ({or DISPLAY ERASE}) PATTERN) 
(DEFUN D0481 (MESSAGE)
  (COND ((AND
          (AND (MEMQ (CAR MESSAGE) (QUOTE (DISPLAY ERASE))) (NULL (CDR MESSAGE)))
          (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION (|({or DISPLAY ERASE})| 0) TEXT))))
        ((AND
          (AND
           (EQ (CAR MESSAGE) (QUOTE SET))
           (AND
            (EQ (CADR MESSAGE) (QUOTE YOUR))
            (AND
             (MEMQ (CADDR MESSAGE) (QUOTE (STRING FONT)))
             (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))))
          (METHOD-IF-NOT-HIDDEN
           '#,(METHOD-AT-POSITION (|(SET YOUR {or STRING FONT} TO ?)| 0) TEXT))))
        ((AND
          (EQ (CAR MESSAGE) (QUOTE RECALL))
          (AND
           (EQ (CADR MESSAGE) (QUOTE YOUR))
           (COND ((AND
                   (EQUAL (CDDR MESSAGE) (QUOTE (WIDTH)))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION ((RECALL YOUR WIDTH) 0) TEXT))))
                 ((AND
                   (EQUAL (CDDR MESSAGE) (QUOTE (HEIGHT)))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION ((RECALL YOUR HEIGHT) 0) TEXT)))))))))) 
(DEFUN D0490 NIL
  (RASTER-TO-RELATIVE-TO-THE-CAST
   (LET
    ((*MESSAGE '(RECALL YOUR SIZE)))
    (QUICK-COMPILED-ASK
     '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
     '#,(ACTOR-OF (QUOTE FONT)))))) 
(DEFUN D0489 NIL
  ((LAMBDA (STRING)
     (RASTER-TO-RELATIVE-TO-THE-CAST
      (FWUSE-TEXT-LENGTH
       STRING
       (LET
        ((*MESSAGE '(RECALL YOUR NAME)))
        (QUICK-COMPILED-ASK
         '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
         '#,(ACTOR-OF (QUOTE FONT)))))))
   (CAR (CDADDR *MESSAGE)))) 
(DEFUN |(RECALL YOUR (LENGTH-FOR ?))| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE RECALL))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (AND
      (LISTP (CADDR OBJECT))
      (EQ (CAADDR OBJECT) (QUOTE LENGTH-FOR))
      (ONE-LONG (CDADDR OBJECT)))
     (NULL (CDDDR OBJECT)))))) 
(DEFPROP |(RECALL YOUR (LENGTH-FOR ?))| (RECALL YOUR (LENGTH-FOR ?)) PATTERN) 
(DEFUN D0488 (MESSAGE)
  (AND
   (EQ (CAR MESSAGE) (QUOTE RECALL))
   (AND
    (EQ (CADR MESSAGE) (QUOTE YOUR))
    (COND ((AND
            (AND
             (AND
              (LISTP (CADDR MESSAGE))
              (EQ (CAADDR MESSAGE) (QUOTE LENGTH-FOR))
              (ONE-LONG (CDADDR MESSAGE)))
             (NULL (CDDDR MESSAGE)))
            (METHOD-IF-NOT-HIDDEN
             '#,(METHOD-AT-POSITION (|(RECALL YOUR (LENGTH-FOR ?))| 0) FONT))))
          ((AND
            (EQUAL (CDDR MESSAGE) (QUOTE (HEIGHT)))
            (METHOD-IF-NOT-HIDDEN '#,(METHOD-AT-POSITION ((RECALL YOUR HEIGHT) 0) FONT)))))))
  ) 
(DEFUN D0494 NIL
  ((LAMBDA (NEW-SIZE)
     (LET
      ((*MESSAGE
        '(SET YOUR FONT TO ,(ASK MYSELF RECALL YOUR (FONT-OF-SIZE ,(FLOAT NEW-SIZE))))))
      (QUICK-COMPILED-ASK
       '#,(METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING)
       '#,(ACTOR-OF (QUOTE FONT-SERIES))))
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE '(!,*MESSAGE)))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR SIZE TO ?)| 0) FONT-SERIES)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE FONT-SERIES))))
      MYSELF
      *METHOD-BEING-RUN))
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN D0493 NIL
  ((LAMBDA (NEW-FONTS)
     (RUN-WITH-METHOD-INVISIBLE
      (LET
       ((*MESSAGE
         '(SET
           YOUR
           FONTS
           TO
           ,(SORT
             NEW-FONTS
             (FUNCTION
              (LAMBDA (FONT1 FONT2)
                (< (ASK ,FONT1 RECALL YOUR SIZE) (ASK ,FONT2 RECALL YOUR SIZE))))))))
       (COMPILED-ASK
        '#,(LIST
            (METHOD-AT-POSITION (|(SET YOUR FONTS TO ?)| 0) FONT-SERIES)
            (METHOD-AT-POSITION (|(SET YOUR ? TO ?)| 0) SOMETHING))
        '#,(ACTOR-OF (QUOTE FONT-SERIES))))
      MYSELF
      *METHOD-BEING-RUN))
   (CAR (CDDDDR *MESSAGE)))) 
(DEFUN |(SET YOUR FONTS TO ?)| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE SET))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (EQ (CADDR OBJECT) (QUOTE FONTS))
     (AND (EQ (CADDDR OBJECT) (QUOTE TO)) (ONE-LONG (CDDDDR OBJECT))))))) 
(DEFPROP |(SET YOUR FONTS TO ?)| (SET YOUR FONTS TO ?) PATTERN) 
(DEFUN D0492 NIL
  ((LAMBDA (SIZE)
     (DO
      ((I
        (LET
         ((*MESSAGE '(RECALL YOUR FONTS)))
         (QUICK-COMPILED-ASK
          '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
          '#,(ACTOR-OF (QUOTE FONT-SERIES))))
        (REST I))
       (LAST-FONT NIL)
       (LAST-SIZE -1.0))
      ((NULL I) LAST-FONT)
      (LET*
       ((FONT (FIRST I))
        (FONT-SIZE
         (LET
          ((MYSELF (ACTOR-OF FONT)) (*MESSAGE '(RECALL YOUR SIZE)))
          (QUICK-COMPILED-ASK
           '#,(METHOD-AT-POSITION (|(RECALL YOUR ?)| 0) SOMETHING)
           '#,(ACTOR-OF (QUOTE FONT-SERIES))))))
       (COND ((> FONT-SIZE SIZE)
              (COND ((> (-$ FONT-SIZE SIZE) (-$ SIZE LAST-SIZE)) (RETURN LAST-FONT))
                    (T (RETURN FONT)))))
       (SETQ LAST-FONT FONT
             LAST-SIZE FONT-SIZE))))
   (CAR (CDADDR *MESSAGE)))) 
(DEFUN |(RECALL YOUR (FONT-OF-SIZE ?))| (OBJECT)
  (AND
   (EQ (CAR OBJECT) (QUOTE RECALL))
   (AND
    (EQ (CADR OBJECT) (QUOTE YOUR))
    (AND
     (AND
      (LISTP (CADDR OBJECT))
      (EQ (CAADDR OBJECT) (QUOTE FONT-OF-SIZE))
      (ONE-LONG (CDADDR OBJECT)))
     (NULL (CDDDR OBJECT)))))) 
(DEFPROP |(RECALL YOUR (FONT-OF-SIZE ?))| (RECALL YOUR (FONT-OF-SIZE ?)) PATTERN) 
(DEFUN D0491 (MESSAGE)
  (COND ((AND
          (AND
           (EQ (CAR MESSAGE) (QUOTE RECALL))
           (AND
            (EQ (CADR MESSAGE) (QUOTE YOUR))
            (AND
             (AND
              (LISTP (CADDR MESSAGE))
              (EQ (CAADDR MESSAGE) (QUOTE FONT-OF-SIZE))
              (ONE-LONG (CDADDR MESSAGE)))
             (NULL (CDDDR MESSAGE)))))
          (METHOD-IF-NOT-HIDDEN
           '#,(METHOD-AT-POSITION (|(RECALL YOUR (FONT-OF-SIZE ?))| 0) FONT-SERIES))))
        ((AND
          (EQ (CAR MESSAGE) (QUOTE SET))
          (AND
           (EQ (CADR MESSAGE) (QUOTE YOUR))
           (COND ((AND
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE FONTS))
                    (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION (|(SET YOUR FONTS TO ?)| 0) FONT-SERIES))))
                 ((AND
                   (AND
                    (EQ (CADDR MESSAGE) (QUOTE SIZE))
                    (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))
                   (METHOD-IF-NOT-HIDDEN
                    '#,(METHOD-AT-POSITION (|(SET YOUR SIZE TO ?)| 0) FONT-SERIES)))))))))) 
(COMMENT AND NOW FOR THE ODDS AND ENDS) 
(ASK PERFORMER ADD ROCKET TO YOUR LIST OF OFFSPRING) 
(ASK THE-CAST ADD ROCKET TO YOUR LIST OF PARTS) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE ROCKET))) 
(ASK PERFORMER ADD POLY TO YOUR LIST OF OFFSPRING) 
(ASK THE-CAST ADD POLY TO YOUR LIST OF PARTS) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE POLY))) 
(ASK PERFORMER ADD COLOR-POLY TO YOUR LIST OF OFFSPRING) 
(ASK THE-CAST ADD COLOR-POLY TO YOUR LIST OF PARTS) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE COLOR-POLY))) 
(ASK PERFORMER ADD FLOWER TO YOUR LIST OF OFFSPRING) 
(ASK THE-CAST ADD FLOWER TO YOUR LIST OF PARTS) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE FLOWER))) 
(ASK PERFORMER ADD WINDOW TO YOUR LIST OF OFFSPRING) 
(ASK THE-CAST ADD WINDOW TO YOUR LIST OF PARTS) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE WINDOW))) 
(ASK PERFORMER ADD TEXT TO YOUR LIST OF OFFSPRING) 
(ASK THE-CAST ADD TEXT TO YOUR LIST OF PARTS) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE TEXT))) 
(ASK SOMETHING ADD FONT TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE FONT))) 
(ASK FONT ADD TIMES-ROMAN-FONT TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE TIMES-ROMAN-FONT))) 
(ASK TIMES-ROMAN-FONT ADD TVFONT TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE TVFONT))) 
(ASK TIMES-ROMAN-FONT ADD TR12B TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE TR12B))) 
(ASK TIMES-ROMAN-FONT ADD TR18 TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE TR18))) 
(ASK SOMETHING ADD FONT-SERIES TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE FONT-SERIES))) 
(ASK FONT-SERIES ADD TIMES-ROMAN TO YOUR LIST OF OFFSPRING) 
(REAP-SYMBOLS-IN-ACTOR (ACTOR-OF (QUOTE TIMES-ROMAN))) 