
(INCLUDE |ai:ken;declare >|) 
(DEFCOMMENT SOME) 
(DEFUN PUT-RECEIVE-METHODS-IN-SOMETHING NIL (PUTPROP (INSERT-RECEIVE (QUOTE (DO ONCE WHEN 
RECEIVING ?PATTERN %ACTION)) (QUOTE ((LET ((METHOD-NAME (INSERT-RECEIVE PATTERN (CONS (QUOTE 
(REMOVE-CURRENT-METHOD)) ACTION) :SELF NIL))) (PUTPROP METHOD-NAME 0 (QUOTE 
MAXIMUM-MATCHING-METHODS)) METHOD-NAME))) :SELF) 0 (QUOTE MAXIMUM-MATCHING-METHODS)) 
(PUTPROP (INSERT-RECEIVE (QUOTE (DO ONLY FOR YOURSELF WHEN RECEIVING ?PATTERN %ACTION)) 
(QUOTE ((INSERT-RECEIVE PATTERN ACTION :SELF NIL T))) :SELF) 0 (QUOTE 
MAXIMUM-MATCHING-METHODS)) (PUTPROP (INSERT-RECEIVE (QUOTE (DO WHEN RECEIVING ?PATTERN 
%ACTION)) (QUOTE ((INSERT-RECEIVE PATTERN ACTION :SELF))) :SELF) 0 (QUOTE 
MAXIMUM-MATCHING-METHODS))) 
(DEFINE-FORM (KEEP-SENDING-ITEMS-TIL-MATCH DATABASE-METHOD-NAME ACTOR) (DO ((ACTOR ACTOR 
(PARENT-OF ACTOR)) (METHOD-PREDICATE (METHOD-PATTERN-PREDICATE DATABASE-METHOD-NAME))) 
((NULL ACTOR) NOTHING-FOUND) (LET ((RESULT (DO ((I (ASK (DIRECTOR-SYMBOL-FOR-EVAL ACTOR) 
COLLECT ITEMS) (REST I))) ((NULL I) (QUOTE DIRECTOR-SYMBOL-FOR-NOTHING-FOUND)) (COND 
((FUNCALL METHOD-PREDICATE (FIRST I)) (LET ((:MESSAGE (FIRST I))) (RETURN (RUN-METHOD 
DATABASE-METHOD-NAME)))))))) (COND ((EQ RESULT (QUOTE DIRECTOR-SYMBOL-FOR-NOTHING-FOUND))) 
(T (RETURN RESULT)))))) 
(DEFINE-FORM (KEEP-SENDING-ITEMS-COLLECTING-ALL DATABASE-METHOD-NAME ACTOR) (DO ((ACTOR 
ACTOR (PARENT-OF ACTOR)) (METHOD-PREDICATE (METHOD-PATTERN-PREDICATE DATABASE-METHOD-NAME)) 
(RESULTS NIL)) ((NULL ACTOR) (NREVERSE RESULTS)) (DO ((I (ASK (DIRECTOR-SYMBOL-FOR-EVAL 
ACTOR) COLLECT ITEMS) (REST I))) ((NULL I)) (COND ((FUNCALL METHOD-PREDICATE (FIRST I)) (LET 
((:MESSAGE (FIRST I))) (PUSH (RUN-METHOD DATABASE-METHOD-NAME) RESULTS))))))) 
(DEFINE-FUNCTION IS-ANY-ANCESTOR-OF (ACTOR OTHER) (COND ((NULL ACTOR) NIL) ((EQ ACTOR OTHER) 
ACTOR) (ACTOR (IS-ANY-ANCESTOR-OF (PARENT-OF ACTOR T) OTHER)))) 
(DECLARE (READ)) 
NIL 
(DEFUN ADD-HELP-TO-ACTOR (ACTOR PATTERN COMMENT) (ASK (DIRECTOR-SYMBOL-FOR-EVAL ACTOR) 
MEMORIZE (|When receiving| (DIRECTOR-SYMBOL-FOR-EVAL PATTERN) I (DIRECTOR-SYMBOL-FOR-UNPACK 
(DIRECTOR-SYMBOL-FOR-EVAL COMMENT))))) 
(DEFINE-FORM (CHILDLESS-DESCENDANTS-OF ACTOR) (LET ((OFFSPRING (LET ((:SELF (ACTOR-OF 
ACTOR)) (:MESSAGE (QUOTE (RECALL YOUR OFFSPRING)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR OFFSPRING)|) (QUOTE SOMETHING))))) (COND (OFFSPRING (MAPCAN (QUOTE 
CHILDLESS-DESCENDANTS-OF) OFFSPRING)) (T (LIST ACTOR))))) 
(DEFINE-FORM (DESCENDANTS-OF-INCLUDING-SELF ACTOR) (LET ((OFFSPRING (LET ((:SELF (ACTOR-OF 
ACTOR)) (:MESSAGE (QUOTE (RECALL YOUR OFFSPRING)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR OFFSPRING)|) (QUOTE SOMETHING))))) (COND (OFFSPRING (APPEND (MAPCAN 
(QUOTE DESCENDANTS-OF-INCLUDING-SELF) OFFSPRING) (LIST ACTOR))) (T (LIST ACTOR))))) 
(DEFINE-FORM (BODY-OF-DO-THE-FOLLOWING: MESSAGES) (DO ((M MESSAGES (REST M)) (LAST-VALUE)) 
((NULL M) LAST-VALUE) (LET ((:MESSAGE (FIRST M))) (SETQ LAST-VALUE (CASES :SELF))))) 
(DEFINE-FORM (TELL-OTHERS-NEW-VALUE VARIABLE NEW-VALUE GROUPS-NAME) (LET ((:MESSAGE (CONS 
(QUOTE ASK) (CONS (QUOTE EACH) (CONS (QUOTE OF) (CONS (QUOTE YOUR) (CONS GROUPS-NAME (CONS 
(QUOTE NOTICE) (CONS (QUOTE THAT) (CONS VARIABLE (CONS (QUOTE OF) (CONS (NAME-OF :SELF) 
(CONS (QUOTE IS) (CONS (QUOTE NOW) (CONS NEW-VALUE NIL))))))))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK EACH OF YOUR ? NOTICE THAT ? OF ? IS NOW ?)|) (QUOTE SOMETHING)))) 
(DEFINE-FORM (TELL-OTHER-NEW-VALUE VARIABLE NEW-VALUE GROUPS-NAME) (LET ((:MESSAGE (CONS 
(QUOTE ASK) (CONS (QUOTE YOUR) (CONS GROUPS-NAME (CONS (QUOTE NOTICE) (CONS (QUOTE THAT) 
(CONS VARIABLE (CONS (QUOTE OF) (CONS (NAME-OF :SELF) (CONS (QUOTE IS) (CONS (QUOTE NOW) 
(CONS NEW-VALUE NIL))))))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK YOUR ? NOTICE THAT ? OF ? IS NOW ?)|) (QUOTE SOMETHING)))) 
(DECLARE (SPECIAL SOMETHING-RECALL-1 SOMETHING-SET-84 SOMETHING-RECALL-83 SOMETHING-RECALL-2 
SOMETHING-DO-3 SOMETHING-DO-4 SOMETHING-DO-5 SOMETHING-RECALL-6 SOMETHING-RECALL-7 
SOMETHING-RECALL-8 SOMETHING-RECALL-9 SOMETHING-RECALL-10 SOMETHING-RECALL-11 
SOMETHING-SET-12 SOMETHING-SET-13 SOMETHING-SET-14 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 SOMETHING-RECALL-16 SOMETHING-CHANGE-17 
SOMETHING-TO-18 SOMETHING-INCREMENT-19 SOMETHING-MULTIPLY-20 SOMETHING-ADD-21 
SOMETHING-ADD-22 SOMETHING-REMOVE-23 SOMETHING-LIST-24 SOMETHING-MAKE-25 SOMETHING-MAKE-26 
SOMETHING-MAKE-27 SOMETHING-MAKE-28 SOMETHING-MAKE-29 SOMETHING-IF-30 SOMETHING-MAKE-31 
SOMETHING-MAKE-32 SOMETHING-REMOB-33 SOMETHING-UNMAKE-34 SOMETHING-MEMORIZE-35 
SOMETHING-COLLECT-36 SOMETHING-FORGET-37 SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38 
SOMETHING-RECALL-39 SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40 SOMETHING-COLLECT-41 
SOMETHING-FORGET-42 SOMETHING-TICK-43 SOMETHING-PLAN-44 SOMETHING-PLAN-45 SOMETHING-PLAN-46 
SOMETHING-PLAN-47 SOMETHING-PLAN-48 SOMETHING-REPEAT-49 SOMETHING-REPEAT-50 
SOMETHING-REPEAT-51 SOMETHING-ASK-52 SOMETHING-ASK-53 SOMETHING-ASK-54 SOMETHING-ASK-55 
SOMETHING-KEEP-56 SOMETHING-DO-57 SOMETHING-ARE-58 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59 SOMETHING-RECALL-60 SOMETHING-RECALL-61 
SOMETHING-FORGET-62 SOMETHING-REMOVE-63 SOMETHING-TRACE-64 SOMETHING-UNTRACE-65 
SOMETHING-UNTRACE-66 SOMETHING-TRANSMISSION-67 SOMETHING-TRANSMISSION-68 SOMETHING-TELL-69 
SOMETHING-TELL-70 SOMETHING-NOTICE-71 SOMETHING-ABSORB-72 SOMETHING-PRINT-73 
SOMETHING-COMPARE-74 SOMETHING-COMPILE-75 SOMETHING-COMPILE-76 SOMETHING-SAVE-77 
SOMETHING-HELP-78 SOMETHING-WARNING-79 SOMETHING-SHOULD-80 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93)) 
(SETQ SOMETHING-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE NIL))) 
(DEFPROP SOMETHING-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ SOMETHING-SET-84 (QUOTE SOMETHING-SET-84)) 
(DEFPROP SOMETHING-SET-84 (SET YOUR OFFSPRING TO ?) METHOD-PATTERN) 
(DEFPROP SOMETHING-SET-84 T PRIVATE?) 
(DEFUN SOMETHING-SET-84 NIL ((LAMBDA (THE-NEW-VALUE) (SET-DIRECTOR-SYMBOL-FOR-VALUE 
SOMETHING-RECALL-83 THE-NEW-VALUE)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-RECALL-83 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE NIL))) 
(DEFPROP SOMETHING-RECALL-83 (RECALL YOUR OFFSPRING) METHOD-PATTERN) 
(DEFPROP SOMETHING-RECALL-83 T PRIVATE?) 
(SETQ SOMETHING-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SOMETHING))) 
(DEFPROP SOMETHING-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ SOMETHING-DO-3 (QUOTE SOMETHING-DO-3)) 
(DEFPROP SOMETHING-DO-3 (DO ONCE WHEN RECEIVING ? %) METHOD-PATTERN) 
(DEFPROP SOMETHING-DO-3 0 MAXIMUM-MATCHING-METHODS) 
(DEFUN SOMETHING-DO-3 NIL ((LAMBDA (ACTION PATTERN) (LET ((METHOD-NAME (INSERT-RECEIVE 
PATTERN (CONS (QUOTE (REMOVE-CURRENT-METHOD)) ACTION) :SELF NIL))) (PUTPROP METHOD-NAME 0 
(QUOTE MAXIMUM-MATCHING-METHODS)) METHOD-NAME)) (REST (CDDDDR :MESSAGE)) (FIRST (CDDDDR 
:MESSAGE)))) 
(SETQ SOMETHING-DO-4 (QUOTE SOMETHING-DO-4)) 
(DEFPROP SOMETHING-DO-4 (DO ONLY FOR YOURSELF WHEN RECEIVING ? %) METHOD-PATTERN) 
(DEFPROP SOMETHING-DO-4 0 MAXIMUM-MATCHING-METHODS) 
(DEFUN SOMETHING-DO-4 NIL ((LAMBDA (ACTION PATTERN) (INSERT-RECEIVE PATTERN ACTION :SELF NIL 
T)) (CDDDR (CDDDDR :MESSAGE)) (CADDR (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-DO-5 (QUOTE SOMETHING-DO-5)) 
(DEFPROP SOMETHING-DO-5 (DO WHEN RECEIVING ? %) METHOD-PATTERN) 
(DEFPROP SOMETHING-DO-5 0 MAXIMUM-MATCHING-METHODS) 
(DEFUN SOMETHING-DO-5 NIL ((LAMBDA (ACTION PATTERN) (INSERT-RECEIVE PATTERN ACTION :SELF)) 
(CDDDDR :MESSAGE) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-RECALL-6 (QUOTE SOMETHING-RECALL-6)) 
(DEFPROP SOMETHING-RECALL-6 (RECALL YOUR SIBLINGS) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-6 NIL (SAFE-DELETE (NAME-OF :SELF) (LET ((PARENT (LET ((:MESSAGE 
(QUOTE (RECALL YOUR PARENT)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR PARENT)|) (QUOTE 
SOMETHING))))) (AND PARENT (LET ((:SELF (ACTOR-OF PARENT)) (:MESSAGE (QUOTE (RECALL YOUR 
OFFSPRING)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR OFFSPRING)|) (QUOTE 
SOMETHING))))))) 
(SETQ SOMETHING-RECALL-7 (QUOTE SOMETHING-RECALL-7)) 
(DEFPROP SOMETHING-RECALL-7 (RECALL YOUR DESCENDANTS) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-7 NIL (MAPCAN (QUOTE DESCENDANTS-OF-INCLUDING-SELF) (LET ((:MESSAGE 
(QUOTE (RECALL YOUR OFFSPRING)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR OFFSPRING)|) 
(QUOTE SOMETHING))))) 
(SETQ SOMETHING-RECALL-8 (QUOTE SOMETHING-RECALL-8)) 
(DEFPROP SOMETHING-RECALL-8 (RECALL YOUR CHILDLESS-DESCENDANTS) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-8 NIL (CHILDLESS-DESCENDANTS-OF :SELF)) 
(SETQ SOMETHING-RECALL-9 (QUOTE SOMETHING-RECALL-9)) 
(DEFPROP SOMETHING-RECALL-9 (RECALL YOUR REVERSED-DESCENDANTS) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-9 NIL (REVERSE (LET ((:MESSAGE (QUOTE (RECALL YOUR DESCENDANTS)))) 
(COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR DESCENDANTS)|) (QUOTE SOMETHING))))) 
(SETQ SOMETHING-RECALL-10 (QUOTE SOMETHING-RECALL-10)) 
(DEFPROP SOMETHING-RECALL-10 (RECALL YOUR REVERSED-CHILDLESS-DESCENDANTS) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-10 NIL (REVERSE (LET ((:MESSAGE (QUOTE (RECALL YOUR 
CHILDLESS-DESCENDANTS)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR CHILDLESS-DESCENDANTS)|) (QUOTE SOMETHING))))) 
(SETQ SOMETHING-RECALL-11 (QUOTE SOMETHING-RECALL-11)) 
(DEFPROP SOMETHING-RECALL-11 (RECALL YOUR PRIVATE-VARIABLE-NAMES) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-11 NIL (QUOTE (OFFSPRING THINGS-TO-DO-NEXT NAME SYNONYMS))) 
(SETQ SOMETHING-SET-12 (QUOTE SOMETHING-SET-12)) 
(DEFPROP SOMETHING-SET-12 (SET YOUR PARENT TO ?) METHOD-PATTERN) 
(DEFUN SOMETHING-SET-12 NIL ((LAMBDA (NEW-PARENT) (LET ((:REPLACE-OLD-METHODS T)) (ASK1 
(ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (QUOTE 
(RECALL YOUR PARENT)) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-VALUE) (CONS NEW-PARENT NIL)) 
NIL))))) NIL) NEW-PARENT)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-SET-13 (QUOTE SOMETHING-SET-13)) 
(DEFPROP SOMETHING-SET-13 (SET YOUR NAME TO ?) METHOD-PATTERN) 
(DEFUN SOMETHING-SET-13 NIL ((LAMBDA (NEW-NAME) (LET ((:REPLACE-OLD-METHODS T)) (ASK1 
(ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (QUOTE 
(RECALL YOUR NAME)) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-VALUE) (CONS NEW-NAME NIL)) 
NIL))))) NIL) NEW-NAME)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-SET-14 (QUOTE SOMETHING-SET-14)) 
(DEFPROP SOMETHING-SET-14 (SET YOUR ? TO ?) METHOD-PATTERN) 
(DEFUN SOMETHING-SET-14 NIL ((LAMBDA (VALUE VARIABLE) ((LAMBDA (NON-INHERITABLE) (COND 
(NON-INHERITABLE ((LAMBDA (:REPLACE-OLD-METHODS :INSERT-METHODS-AT-END) ((LAMBDA 
(RECALL-METHOD-NAME) (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE ONLY) (CONS (QUOTE 
FOR) (CONS (QUOTE YOURSELF) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (CONS (QUOTE 
SET) (CONS (QUOTE YOUR) (CONS VARIABLE (QUOTE (TO ?THE-NEW-VALUE))))) (CONS (CONS (QUOTE 
SET-DIRECTOR-SYMBOL-FOR-VALUE) (CONS RECALL-METHOD-NAME (QUOTE (THE-NEW-VALUE)))) 
NIL)))))))) NIL)) (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE ONLY) (CONS (QUOTE 
FOR) (CONS (QUOTE YOURSELF) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (CONS (QUOTE 
RECALL) (CONS (QUOTE YOUR) (CONS VARIABLE NIL))) (CONS (CONS (QUOTE 
DIRECTOR-SYMBOL-FOR-VALUE) (CONS VALUE NIL)) NIL)))))))) NIL))) T NIL)) (T 
(MAINTAIN-VALUE-ASSOC-LIST (LET ((:MESSAGE (QUOTE (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)))) 
(COMPILED-ASK (QUOTE |SOMETHING(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)|) (QUOTE SOMETHING))) 
VARIABLE VALUE)))) (MEMBER VARIABLE (LET ((:MESSAGE (QUOTE (RECALL YOUR 
PRIVATE-VARIABLE-NAMES)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR PRIVATE-VARIABLE-NAMES)|) (QUOTE SOMETHING))))) VALUE) (FIRST (CDDDDR 
:MESSAGE)) (CADDR :MESSAGE))) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 (QUOTE 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15)) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFUN SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 NIL ((LAMBDA (THE-ALIST) (ASK1 
(ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE ONLY) (CONS (QUOTE FOR) (CONS (QUOTE 
YOURSELF) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-VALUE) (CONS 
THE-ALIST NIL)) NIL)))))))) NIL) THE-ALIST) (LIST NIL))) 
(SETQ SOMETHING-RECALL-16 (QUOTE SOMETHING-RECALL-16)) 
(DEFPROP SOMETHING-RECALL-16 (RECALL YOUR ?) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-16 NIL ((LAMBDA (VARIABLE) (DO ((ACTOR :SELF (PARENT-OF ACTOR T))) 
((NULL ACTOR) NIL) ((LAMBDA (PAIR) (AND PAIR (RETURN (REST PAIR)))) (ASSOC VARIABLE (LET 
((:SELF (ACTOR-OF ACTOR)) (:MESSAGE (QUOTE (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)))) 
(COMPILED-ASK (QUOTE |SOMETHING(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)|) (QUOTE 
SOMETHING))))))) (CADDR :MESSAGE))) 
(SETQ SOMETHING-CHANGE-17 (QUOTE SOMETHING-CHANGE-17)) 
(DEFPROP SOMETHING-CHANGE-17 (CHANGE YOUR ? TO ?) METHOD-PATTERN) 
(DEFPROP SOMETHING-CHANGE-17 SOMETHING-CHANGE-17-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-CHANGE-17 NIL ((LAMBDA (VALUE VARIABLE) (LET ((:MESSAGE (CONS (QUOTE SET) 
(CONS (QUOTE YOUR) (CONS VARIABLE (CONS (QUOTE TO) (CONS VALUE NIL))))))) (COMPILED-ASK 
(QUOTE |SOMETHING(SET YOUR ? TO ?)|) (QUOTE SOMETHING)))) (FIRST (CDDDDR :MESSAGE)) (CADDR 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-CHANGE-17-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-CHANGE-17-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-TO-18 (QUOTE SOMETHING-TO-18)) 
(DEFPROP SOMETHING-TO-18 (TO %) METHOD-PATTERN) 
(DEFPROP SOMETHING-TO-18 SOMETHING-TO-18-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-TO-18 NIL ((LAMBDA (MESSAGE) (ASK1 (ACTOR-OF :SELF) MESSAGE NIL)) (REST 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-TO-18-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-TO-18-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-INCREMENT-19 (QUOTE SOMETHING-INCREMENT-19)) 
(DEFPROP SOMETHING-INCREMENT-19 (INCREMENT YOUR ? BY ?) METHOD-PATTERN) 
(DEFPROP SOMETHING-INCREMENT-19 SOMETHING-INCREMENT-19-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-INCREMENT-19 NIL ((LAMBDA (AMOUNT VARIABLE) (LET ((:MESSAGE (CONS (QUOTE 
SET) (CONS (QUOTE YOUR) (CONS VARIABLE (CONS (QUOTE TO) (CONS (PLUS (OR (LET ((:MESSAGE 
(CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS VARIABLE NIL))))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING))) 0) (QUOTE-IF-NEED-BE 
(DIRECTOR-SYMBOL-FOR-EVAL AMOUNT))) NIL))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(SET YOUR ? TO ?)|) (QUOTE SOMETHING)))) (FIRST (CDDDDR :MESSAGE)) (CADDR 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-INCREMENT-19-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-INCREMENT-19-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-MULTIPLY-20 (QUOTE SOMETHING-MULTIPLY-20)) 
(DEFPROP SOMETHING-MULTIPLY-20 (MULTIPLY YOUR ? BY ?) METHOD-PATTERN) 
(DEFPROP SOMETHING-MULTIPLY-20 SOMETHING-MULTIPLY-20-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-MULTIPLY-20 NIL ((LAMBDA (FACTOR VARIABLE) (LET ((:MESSAGE (CONS (QUOTE 
SET) (CONS (QUOTE YOUR) (CONS VARIABLE (CONS (QUOTE TO) (CONS (*$ (OR (LET ((:MESSAGE (CONS 
(QUOTE RECALL) (CONS (QUOTE YOUR) (CONS VARIABLE NIL))))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING))) 1.0) (QUOTE-IF-NEED-BE 
(DIRECTOR-SYMBOL-FOR-EVAL FACTOR))) NIL))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(SET YOUR ? TO ?)|) (QUOTE SOMETHING)))) (FIRST (CDDDDR :MESSAGE)) (CADDR 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-MULTIPLY-20-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-MULTIPLY-20-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-ADD-21 (QUOTE SOMETHING-ADD-21)) 
(DEFPROP SOMETHING-ADD-21 (ADD ? TO YOUR LIST OF ?) METHOD-PATTERN) 
(DEFPROP SOMETHING-ADD-21 SOMETHING-ADD-21-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-ADD-21 NIL ((LAMBDA (LIST-NAME VALUE) (LET ((:MESSAGE (CONS (QUOTE SET) 
(CONS (QUOTE YOUR) (CONS LIST-NAME (CONS (QUOTE TO) (CONS (CONS-IF-NOT-MEMBER 
(QUOTE-IF-NEED-BE (DIRECTOR-SYMBOL-FOR-EVAL VALUE)) (LET ((:MESSAGE (CONS (QUOTE RECALL) 
(CONS (QUOTE YOUR) (CONS LIST-NAME NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) 
(QUOTE SOMETHING)))) NIL))))))) (COMPILED-ASK (QUOTE |SOMETHING(SET YOUR ? TO ?)|) (QUOTE 
SOMETHING)))) (CADDR (CDDDDR :MESSAGE)) (CADR :MESSAGE))) 
(PROGN (DEFPROP SOMETHING-ADD-21-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-ADD-21-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-ADD-22 (QUOTE SOMETHING-ADD-22)) 
(DEFPROP SOMETHING-ADD-22 (ADD ? TO YOUR LIST OF ? REGARDLESS) METHOD-PATTERN) 
(DEFPROP SOMETHING-ADD-22 SOMETHING-ADD-22-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-ADD-22 NIL ((LAMBDA (VARIABLE VALUE) (LET ((:MESSAGE (CONS (QUOTE SET) 
(CONS (QUOTE YOUR) (CONS VARIABLE (CONS (QUOTE TO) (CONS (CONS (QUOTE-IF-NEED-BE 
(DIRECTOR-SYMBOL-FOR-EVAL VALUE)) (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE YOUR) 
(CONS VARIABLE NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) (QUOTE 
SOMETHING)))) NIL))))))) (COMPILED-ASK (QUOTE |SOMETHING(SET YOUR ? TO ?)|) (QUOTE 
SOMETHING)))) (CADDR (CDDDDR :MESSAGE)) (CADR :MESSAGE))) 
(PROGN (DEFPROP SOMETHING-ADD-22-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-ADD-22-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-REMOVE-23 (QUOTE SOMETHING-REMOVE-23)) 
(DEFPROP SOMETHING-REMOVE-23 (REMOVE ? FROM YOUR LIST OF ?) METHOD-PATTERN) 
(DEFPROP SOMETHING-REMOVE-23 SOMETHING-REMOVE-23-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-REMOVE-23 NIL ((LAMBDA (LIST-NAME VALUE-PATTERN) (LET ((:MESSAGE (CONS 
(QUOTE SET) (CONS (QUOTE YOUR) (CONS LIST-NAME (CONS (QUOTE TO) (CONS (MATCH-SAFE-DELETE 
(QUOTE-IF-NEED-BE (DIRECTOR-SYMBOL-FOR-EVAL VALUE-PATTERN)) (LET ((:MESSAGE (CONS (QUOTE 
RECALL) (CONS (QUOTE YOUR) (CONS LIST-NAME NIL))))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING)))) NIL))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(SET YOUR ? TO ?)|) (QUOTE SOMETHING)))) (CADDR (CDDDDR :MESSAGE)) (CADR 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-REMOVE-23-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-REMOVE-23-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-LIST-24 (QUOTE SOMETHING-LIST-24)) 
(DEFPROP SOMETHING-LIST-24 (LIST ALL YOUR VARIABLE NAMES) METHOD-PATTERN) 
(DEFUN SOMETHING-LIST-24 NIL (COLLECT-ALL-VARIABLE-NAMES :SELF)) 
(SETQ SOMETHING-MAKE-25 (QUOTE SOMETHING-MAKE-25)) 
(DEFPROP SOMETHING-MAKE-25 (MAKE AN INSTANCE NAMED ? COPYING ?) METHOD-PATTERN) 
(DEFUN SOMETHING-MAKE-25 NIL ((LAMBDA (VARIABLES-TO-COPY NAME) (COND (VARIABLES-TO-COPY (LET 
((NEW-ACTOR (MAKE-ACTOR (QUOTE SOMETHING) NAME))) (MAPC (FUNCTION (LAMBDA (VARIABLE-TO-COPY) 
(LET ((:SELF (ACTOR-OF NEW-ACTOR)) (:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS 
VARIABLE-TO-COPY (CONS (QUOTE TO) (CONS (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE 
YOUR) (CONS VARIABLE-TO-COPY NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) 
(QUOTE SOMETHING))) NIL))))))) (COMPILED-ASK (QUOTE |SOMETHING(SET YOUR ? TO ?)|) (QUOTE 
SOMETHING))))) VARIABLES-TO-COPY) (LET ((:SELF (ACTOR-OF NEW-ACTOR)) (:MESSAGE (CONS (QUOTE 
SET) (CONS (QUOTE YOUR) (CONS (QUOTE PARENT) (CONS (QUOTE TO) (CONS (OR (NAME-OF :SELF) 
:SELF) NIL))))))) (COMPILED-ASK (QUOTE |SOMETHING(SET YOUR PARENT TO ?)|) (QUOTE 
SOMETHING))) NEW-ACTOR)) (T (MAKE-ACTOR (OR (NAME-OF :SELF) :SELF) NAME)))) (CADDR (CDDDDR 
:MESSAGE)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-MAKE-26 (QUOTE SOMETHING-MAKE-26)) 
(DEFPROP SOMETHING-MAKE-26 (MAKE) METHOD-PATTERN) 
(DEFPROP SOMETHING-MAKE-26 SOMETHING-MAKE-26-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-MAKE-26 NIL (LET ((:MESSAGE (CONS (QUOTE MAKE) (CONS (QUOTE AN) (CONS 
(QUOTE INSTANCE) (CONS (QUOTE NAMED) (CONS (QUOTE NIL) (CONS (QUOTE COPYING) (CONS (LET 
((:MESSAGE (QUOTE (RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)|) (QUOTE SOMETHING))) NIL))))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(MAKE AN INSTANCE NAMED NIL COPYING ?)|) (QUOTE SOMETHING)))) 
(PROGN (DEFPROP SOMETHING-MAKE-26-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-MAKE-26-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-MAKE-27 (QUOTE SOMETHING-MAKE-27)) 
(DEFPROP SOMETHING-MAKE-27 (MAKE ?) METHOD-PATTERN) 
(DEFUN SOMETHING-MAKE-27 NIL ((LAMBDA (NAME) (COND (NAME (COND ((ACTOR-OF NAME 
DONT-AUTOLOAD) (AND (LET ((:SELF (ACTOR-OF NAME)) (:MESSAGE (QUOTE (UNMAKE)))) (COMPILED-ASK 
(QUOTE |SOMETHING(UNMAKE)|) (QUOTE SOMETHING))) (PLACE-ACTOR-ON-NAME (LET ((:MESSAGE (CONS 
(QUOTE MAKE) (CONS (QUOTE AN) (CONS (QUOTE INSTANCE) (CONS (QUOTE NAMED) (CONS NAME (CONS 
(QUOTE COPYING) (CONS (LET ((:MESSAGE (QUOTE (RECALL YOUR 
VARIABLES-TO-COPY-UPON-CREATION)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)|) (QUOTE SOMETHING))) NIL))))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(MAKE AN INSTANCE NAMED ? COPYING ?)|) (QUOTE SOMETHING))) 
NAME))) (T (PLACE-ACTOR-ON-NAME (LET ((:MESSAGE (CONS (QUOTE MAKE) (CONS (QUOTE AN) (CONS 
(QUOTE INSTANCE) (CONS (QUOTE NAMED) (CONS NAME (CONS (QUOTE COPYING) (CONS (LET ((:MESSAGE 
(QUOTE (RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)|) (QUOTE SOMETHING))) NIL))))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(MAKE AN INSTANCE NAMED ? COPYING ?)|) (QUOTE SOMETHING))) 
NAME)))) (T (SHOULDNT-HAPPEN (QUOTE MAKE-INSTANCE) (QUOTE 
(|cant make an actor named nil sorry|))))) (AND (INTERNEDP NAME) (LET ((:MESSAGE (CONS 
(QUOTE ADD) (CONS NAME (QUOTE (TO YOUR LIST OF OFFSPRING)))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ADD ? TO YOUR LIST OF OFFSPRING)|) (QUOTE SOMETHING)))) 
(DECOMPILE-ALL-DEPENDENT-SELECTORS NAME) (UPDATE-ALL-DEPENDENT-SELECTORS NAME (QUOTE ?)) 
NAME) (CADR :MESSAGE))) 
(SETQ SOMETHING-MAKE-28 (QUOTE SOMETHING-MAKE-28)) 
(DEFPROP SOMETHING-MAKE-28 (MAKE UNINTERNED OFFSPRING) METHOD-PATTERN) 
(DEFUN SOMETHING-MAKE-28 NIL (LET ((ACTORS-NAME (NAME-OF :SELF))) (LET ((:MESSAGE (CONS 
(QUOTE MAKE) (CONS (APPEND-ATOMS ACTORS-NAME (QUOTE -) (GEN-NUMBER ACTORS-NAME)) NIL)))) 
(COMPILED-ASK (QUOTE |SOMETHING(MAKE ?)|) (QUOTE SOMETHING))))) 
(SETQ SOMETHING-MAKE-29 (QUOTE SOMETHING-MAKE-29)) 
(DEFPROP SOMETHING-MAKE-29 (MAKE INTERNED OFFSPRING) METHOD-PATTERN) 
(DEFUN SOMETHING-MAKE-29 NIL (LET ((ACTORS-NAME (NAME-OF :SELF))) (LET ((:MESSAGE (CONS 
(QUOTE MAKE) (CONS (INTERN-APPEND-ATOMS ACTORS-NAME (QUOTE -) (GEN-NUMBER ACTORS-NAME)) 
NIL)))) (COMPILED-ASK (QUOTE |SOMETHING(MAKE ?)|) (QUOTE SOMETHING))))) 
(SETQ SOMETHING-IF-30 (QUOTE SOMETHING-IF-30)) 
(DEFPROP SOMETHING-IF-30 (IF NEW MAKE ?) METHOD-PATTERN) 
(DEFUN SOMETHING-IF-30 NIL ((LAMBDA (NAME) (COND ((EXISTS? NAME) NAME) (T (LET ((:MESSAGE 
(CONS (QUOTE MAKE) (CONS NAME NIL)))) (COMPILED-ASK (QUOTE |SOMETHING(MAKE ?)|) (QUOTE 
SOMETHING)))))) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-MAKE-31 (QUOTE SOMETHING-MAKE-31)) 
(DEFPROP SOMETHING-MAKE-31 (MAKE COPY ?) METHOD-PATTERN) 
(DEFUN SOMETHING-MAKE-31 NIL ((LAMBDA (SIBLING) (LET ((:MESSAGE (CONS (QUOTE ASK) (CONS 
(QUOTE YOUR) (CONS (QUOTE PARENT) (CONS (QUOTE TO) (CONS (QUOTE MAKE) (CONS SIBLING 
NIL)))))))) (COMPILED-ASK (QUOTE |SOMETHING(ASK YOUR PARENT TO MAKE ?)|) (QUOTE SOMETHING))) 
(DISPLACE (ACTOR-OF SIBLING) (LET ((NAME (NAME-OF :SELF))) (COPY :SELF (CONS (CONS NAME 
SIBLING) NIL)))) SIBLING) (CADDR :MESSAGE))) 
(SETQ SOMETHING-MAKE-32 (QUOTE SOMETHING-MAKE-32)) 
(DEFPROP SOMETHING-MAKE-32 (MAKE SYNONYM ?) METHOD-PATTERN) 
(DEFUN SOMETHING-MAKE-32 NIL ((LAMBDA (NAME) (LET ((:MESSAGE (CONS (QUOTE ADD) (CONS NAME 
(QUOTE (TO YOUR LIST OF SYNONYMS)))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ADD ? TO YOUR LIST OF SYNONYMS)|) (QUOTE SOMETHING))) (SYNONYM-FOR :SELF NAME)) 
(CADDR :MESSAGE))) 
(SETQ SOMETHING-REMOB-33 (QUOTE SOMETHING-REMOB-33)) 
(DEFPROP SOMETHING-REMOB-33 (REMOB) METHOD-PATTERN) 
(DEFUN SOMETHING-REMOB-33 NIL (LET ((:MESSAGE (CONS (QUOTE ASK) (CONS (QUOTE YOUR) (CONS 
(QUOTE PARENT) (CONS (QUOTE REMOVE) (CONS (NAME-OF :SELF) (QUOTE (FROM YOUR LIST OF 
OFFSPRING))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK YOUR PARENT REMOVE ? FROM YOUR LIST OF OFFSPRING)|) (QUOTE SOMETHING))) 
(GENERAL-REMPROP (NAME-OF :SELF) (QUOTE ACTOR) (QUOTE NON-ATOMIC-ACTORS)) (LET ((NEW-NAME 
(LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE NAME) (CONS (QUOTE TO) 
(CONS (GENERATE-SYMBOL (OR (NAME-OF :SELF) (QUOTE |unnamed-actor|))) NIL))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(SET YOUR NAME TO ?)|) (QUOTE SOMETHING))))) 
(PLACE-ACTOR-ON-NAME :SELF NEW-NAME) NEW-NAME)) 
(SETQ SOMETHING-UNMAKE-34 (QUOTE SOMETHING-UNMAKE-34)) 
(DEFPROP SOMETHING-UNMAKE-34 (UNMAKE) METHOD-PATTERN) 
(DEFUN SOMETHING-UNMAKE-34 NIL ((LAMBDA (NAME) (COND ((AND (MEMBER NAME :PROTECTED-ACTORS) 
(SHOULDNT-HAPPEN NAME (QUOTE 
(|You are trying to unmake me and I'm protected so type "p " and I'll ignored this./
If you really want to kill me then remove my name from the variable :protected-actors/
and then type "(return t)"|))))) (T (OR (EQ NAME (QUOTE SOMETHING)) (LET ((:MESSAGE (CONS 
(QUOTE ASK) (CONS (QUOTE YOUR) (CONS (QUOTE PARENT) (CONS (QUOTE TO) (CONS (QUOTE REMOVE) 
(CONS NAME (QUOTE (FROM YOUR LIST OF OFFSPRING)))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK YOUR PARENT TO REMOVE ? FROM YOUR LIST OF OFFSPRING)|) (QUOTE SOMETHING)))) 
(AND (LET ((:MESSAGE (QUOTE (RECALL YOUR THINGS-TO-DO-NEXT)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR THINGS-TO-DO-NEXT)|) (QUOTE SOMETHING))) (LET ((:MESSAGE (CONS (QUOTE 
ASK) (CONS (QUOTE YOUR) (CONS (QUOTE UNIVERSE) (CONS (QUOTE TO) (CONS (QUOTE REMOVE) (CONS 
NAME (QUOTE (FROM YOUR LIST OF ACTORS-TO-RUN-NEXT)))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK YOUR UNIVERSE TO REMOVE ? FROM YOUR LIST OF ACTORS-TO-RUN-NEXT)|) (QUOTE 
SOMETHING)))) ((LAMBDA (WHOLE) (AND WHOLE (LET ((:SELF (ACTOR-OF WHOLE)) (:MESSAGE (CONS 
(QUOTE REMOVE) (CONS NAME (QUOTE (FROM YOUR LIST OF PARTS)))))) (COMPILED-ASK (QUOTE 
|SOMETHING(REMOVE ? FROM YOUR LIST OF PARTS)|) (QUOTE SOMETHING))))) (LET ((:MESSAGE (QUOTE 
(RECALL YOUR WHOLE)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR WHOLE)|) (QUOTE 
SOMETHING)))) (LET ((:MESSAGE (QUOTE (ASK EACH OF YOUR PARTS TO UNMAKE)))) (COMPILED-ASK 
(QUOTE |SOMETHING(ASK EACH OF YOUR PARTS TO UNMAKE)|) (QUOTE SOMETHING))) (LET ((:MESSAGE 
(QUOTE (UNTRACE)))) (COMPILED-ASK (QUOTE |SOMETHING(UNTRACE)|) (QUOTE SOMETHING))) (COND 
((ATOM NAME) (REMPROP NAME (QUOTE ACTOR))) (T (REMOVE-PROPERTY (GET (FIRST NAME) (QUOTE 
NON-ATOMIC-ACTORS)) (REST NAME)))) NAME))) (NAME-OF :SELF))) 
(SETQ SOMETHING-MEMORIZE-35 (QUOTE SOMETHING-MEMORIZE-35)) 
(DEFPROP SOMETHING-MEMORIZE-35 (MEMORIZE ?) METHOD-PATTERN) 
(DEFUN SOMETHING-MEMORIZE-35 NIL ((LAMBDA (ITEM) (LET ((:INSERT-METHODS-AT-END NIL)) (LET 
((COLLECT-METHOD-NAME (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE ONLY) (CONS 
(QUOTE FOR) (CONS (QUOTE YOURSELF) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (QUOTE 
(COLLECT ITEMS)) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-VALUE) (CONS (CONS ITEM NIL) NIL)) 
NIL)))))))) NIL))) (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE ONLY) (CONS (QUOTE 
FOR) (CONS (QUOTE YOURSELF) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (QUOTE (FORGET 
ITEM ?ITEM)) (CONS (CONS (QUOTE REPLACE-SECOND) (CONS COLLECT-METHOD-NAME (CONS (CONS (QUOTE 
DELETE) (CONS (QUOTE ITEM) (CONS (CONS (QUOTE SECOND) (CONS COLLECT-METHOD-NAME NIL)) NIL))) 
NIL))) (QUOTE (NIL)))))))))) NIL) (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE ONLY) 
(CONS (QUOTE FOR) (CONS (QUOTE YOURSELF) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS 
(QUOTE (MEMORIZE ?ITEM)) (CONS (CONS (QUOTE REPLACE-SECOND) (CONS COLLECT-METHOD-NAME (CONS 
(CONS (QUOTE CONS-IF-NOT-MEMBER) (CONS (QUOTE ITEM) (CONS (CONS (QUOTE SECOND) (CONS 
COLLECT-METHOD-NAME NIL)) NIL))) NIL))) (QUOTE (NO-VALUE)))))))))) NIL))) NO-VALUE) (CADR 
:MESSAGE))) 
(SETQ SOMETHING-COLLECT-36 (QUOTE SOMETHING-COLLECT-36)) 
(DEFPROP SOMETHING-COLLECT-36 (COLLECT ITEMS) METHOD-PATTERN) 
(DEFUN SOMETHING-COLLECT-36 NIL NIL) 
(SETQ SOMETHING-FORGET-37 (QUOTE SOMETHING-FORGET-37)) 
(DEFPROP SOMETHING-FORGET-37 (FORGET ITEM ?) METHOD-PATTERN) 
(DEFUN SOMETHING-FORGET-37 NIL NIL) 
(SETQ SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38 (QUOTE 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38)) 
(DEFPROP SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38 (DIRECTOR-SYMBOL-FOR-AND-PATTERN ? 
(RECALL AN ITEM MATCHING ? THEN ?)) METHOD-PATTERN) 
(DEFUN SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38 NIL ((LAMBDA (ACTION PATTERN 
THE-WHOLE-MESSAGE) (LET ((NEW-ACTOR (LET ((:MESSAGE (QUOTE (MAKE)))) (COMPILED-ASK (QUOTE 
|SOMETHING(MAKE)|) (QUOTE SOMETHING))))) (LET ((DATABASE-METHOD-NAME (ASK1 (ACTOR-OF 
NEW-ACTOR) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS PATTERN (CONS 
ACTION NIL))))) NIL))) (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS 
(QUOTE RECEIVING) (CONS THE-WHOLE-MESSAGE (CONS (CONS (QUOTE KEEP-SENDING-ITEMS-TIL-MATCH) 
(CONS (CONS (QUOTE QUOTE) (CONS DATABASE-METHOD-NAME NIL)) (QUOTE (:SELF)))) NIL))))) NIL) 
(ASK1 (ACTOR-OF :SELF) THE-WHOLE-MESSAGE NIL)))) (CADDR (CDDDDR :MESSAGE)) (FIRST (CDDDDR 
:MESSAGE)) :MESSAGE)) 
(SETQ SOMETHING-RECALL-39 (QUOTE SOMETHING-RECALL-39)) 
(DEFPROP SOMETHING-RECALL-39 (RECALL IF ANY ITEMS MATCH ?) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-39 NIL ((LAMBDA (PATTERN) (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS 
(QUOTE AN) (CONS (QUOTE ITEM) (CONS (QUOTE MATCHING) (CONS PATTERN (QUOTE (THEN T))))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(RECALL AN ITEM MATCHING ? THEN T)|) (QUOTE SOMETHING)))) 
(CADR (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40 (QUOTE 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40)) 
(DEFPROP SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40 (DIRECTOR-SYMBOL-FOR-AND-PATTERN ? 
(RECALL EACH ITEM MATCHING ? THEN ?)) METHOD-PATTERN) 
(DEFUN SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40 NIL ((LAMBDA (ACTION PATTERN 
THE-WHOLE-MESSAGE) (LET ((NEW-ACTOR (LET ((:MESSAGE (QUOTE (MAKE)))) (COMPILED-ASK (QUOTE 
|SOMETHING(MAKE)|) (QUOTE SOMETHING))))) (LET ((DATABASE-METHOD-NAME (ASK1 (ACTOR-OF 
NEW-ACTOR) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS PATTERN (CONS 
ACTION NIL))))) NIL))) (ASK1 (ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS 
(QUOTE RECEIVING) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-QUOTED-PATTERN) (CONS 
THE-WHOLE-MESSAGE NIL)) (CONS (CONS (QUOTE KEEP-SENDING-ITEMS-COLLECTING-ALL) (CONS (CONS 
(QUOTE QUOTE) (CONS DATABASE-METHOD-NAME NIL)) (QUOTE (:SELF)))) NIL))))) NIL) (ASK1 
(ACTOR-OF :SELF) THE-WHOLE-MESSAGE NIL)))) (CADDR (CDDDDR :MESSAGE)) (FIRST (CDDDDR 
:MESSAGE)) :MESSAGE)) 
(SETQ SOMETHING-COLLECT-41 (QUOTE SOMETHING-COLLECT-41)) 
(DEFPROP SOMETHING-COLLECT-41 (COLLECT ITEMS MEMORIZED MATCHING ?) METHOD-PATTERN) 
(DEFUN SOMETHING-COLLECT-41 NIL ((LAMBDA (PATTERN) (LET ((:MESSAGE (CONS (QUOTE RECALL) 
(CONS (QUOTE EACH) (CONS (QUOTE ITEM) (CONS (QUOTE MATCHING) (CONS (CONS (QUOTE 
DIRECTOR-SYMBOL-FOR-AND-PATTERN) (CONS (QUOTE ?THE-ITEM) (CONS PATTERN NIL))) (QUOTE (THEN 
THE-ITEM))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL EACH ITEM MATCHING {and ?THE-ITEM ?} THEN THE-ITEM)|) (QUOTE SOMETHING)))) 
(FIRST (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-FORGET-42 (QUOTE SOMETHING-FORGET-42)) 
(DEFPROP SOMETHING-FORGET-42 (FORGET ITEMS MATCHING ?) METHOD-PATTERN) 
(DEFUN SOMETHING-FORGET-42 NIL ((LAMBDA (PATTERN) (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS 
(QUOTE EACH) (CONS (QUOTE ITEM) (CONS (QUOTE MATCHING) (CONS (CONS (QUOTE 
DIRECTOR-SYMBOL-FOR-AND-PATTERN) (CONS (QUOTE ?THE-ITEM) (CONS PATTERN NIL))) (CONS (QUOTE 
THEN) (CONS (QUOTE (SCRIPT: (ASK :SELF FORGET ITEM (DIRECTOR-SYMBOL-FOR-EVAL THE-ITEM)))) 
NIL))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL EACH ITEM MATCHING {and ?THE-ITEM ?} THEN (SCRIPT: (ASK :SELF FORGET ITEM ?)
))|) (QUOTE SOMETHING)))) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-TICK-43 (QUOTE SOMETHING-TICK-43)) 
(DEFPROP SOMETHING-TICK-43 (TICK) METHOD-PATTERN) 
(DEFPROP SOMETHING-TICK-43 SOMETHING-TICK-43-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-TICK-43 NIL (LET ((THINGS (LET ((:MESSAGE (QUOTE (RECALL YOUR 
THINGS-TO-DO-NEXT)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR THINGS-TO-DO-NEXT)|) 
(QUOTE SOMETHING))))) (LET ((:MESSAGE (QUOTE (SET YOUR THINGS-TO-DO-NEXT TO NIL)))) 
(COMPILED-ASK (QUOTE |SOMETHING(SET YOUR THINGS-TO-DO-NEXT TO NIL)|) (QUOTE SOMETHING))) 
(LET ((:MESSAGE (CONS (QUOTE DO) (CONS (QUOTE THE) (CONS (QUOTE FOLLOWING:) THINGS))))) 
(COMPILED-ASK (QUOTE |SOMETHING(DO THE FOLLOWING: %)|) (QUOTE SOMETHING))) THINGS)) 
(PROGN (DEFPROP SOMETHING-TICK-43-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-TICK-43-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-PLAN-44 (QUOTE SOMETHING-PLAN-44)) 
(DEFPROP SOMETHING-PLAN-44 (PLAN AFTER ? TICKS %) METHOD-PATTERN) 
(DEFUN SOMETHING-PLAN-44 NIL ((LAMBDA (MESSAGE NUMBER) (LET ((WHATS-PLANNED-ALREADY (LET 
((:MESSAGE (QUOTE (RECALL YOUR THINGS-TO-DO-NEXT)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR THINGS-TO-DO-NEXT)|) (QUOTE SOMETHING)))) (NEW-COMMAND (COND ((= 
NUMBER 1) MESSAGE) (T (CONS (QUOTE PLAN) (CONS (QUOTE AFTER) (CONS (1- NUMBER) (CONS (QUOTE 
TICKS) MESSAGE)))))))) (COND (WHATS-PLANNED-ALREADY (NCONC WHATS-PLANNED-ALREADY (LIST 
NEW-COMMAND))) (T (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS (QUOTE 
THINGS-TO-DO-NEXT) (CONS (QUOTE TO) (CONS (CONS NEW-COMMAND NIL) NIL))))))) (COMPILED-ASK 
(QUOTE |SOMETHING(SET YOUR THINGS-TO-DO-NEXT TO (?))|) (QUOTE SOMETHING))) (LET ((UNIVERSE 
(LET ((:MESSAGE (QUOTE (RECALL YOUR UNIVERSE)))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR UNIVERSE)|) (QUOTE SOMETHING)))) (NAME (NAME-OF :SELF))) (OR (EQ NAME 
UNIVERSE) (LET ((:SELF (ACTOR-OF UNIVERSE)) (:MESSAGE (CONS (QUOTE ADD) (CONS NAME (QUOTE 
(TO YOUR LIST OF ACTORS-TO-RUN-NEXT)))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ADD ? TO YOUR LIST OF ACTORS-TO-RUN-NEXT)|) (QUOTE SOMETHING)))))))) NO-VALUE) 
(CDDDDR :MESSAGE) (CADDR :MESSAGE))) 
(SETQ SOMETHING-PLAN-45 (QUOTE SOMETHING-PLAN-45)) 
(DEFPROP SOMETHING-PLAN-45 (PLAN NEXT %) METHOD-PATTERN) 
(DEFPROP SOMETHING-PLAN-45 SOMETHING-PLAN-45-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-PLAN-45 NIL ((LAMBDA (MESSAGE) (LET ((:MESSAGE (CONS (QUOTE PLAN) (CONS 
(QUOTE AFTER) (CONS (QUOTE 1) (CONS (QUOTE TICKS) MESSAGE)))))) (COMPILED-ASK (QUOTE 
|SOMETHING(PLAN AFTER 1 TICKS DIRECTOR-SYMBOL-FOR-EVAL MESSAGE)|) (QUOTE SOMETHING)))) (CDDR 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-PLAN-45-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-PLAN-45-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-PLAN-46 (QUOTE SOMETHING-PLAN-46)) 
(DEFPROP SOMETHING-PLAN-46 (PLAN AFTER ? SECONDS %) METHOD-PATTERN) 
(DEFUN SOMETHING-PLAN-46 NIL ((LAMBDA (MESSAGE NUMBER) (COND ((= NUMBER 0.0) (ASK1 (ACTOR-OF 
:SELF) MESSAGE NIL)) ((LESSP NUMBER 0.0) (SHOULDNT-HAPPEN (QUOTE SOMETHING) (CONS (QUOTE 
CANT) (CONS (QUOTE PLAN) (APPEND MESSAGE (CONS (QUOTE FOR) (CONS NUMBER (QUOTE 
(SECONDS))))))))) (T (LET ((:MESSAGE (CONS (QUOTE PLAN) (CONS (QUOTE AFTER) (CONS (MAX 1 
(ROUND (TIMES (FLOAT NUMBER) :FRAMES-PER-SECOND :TICKS-PER-FRAME))) (CONS (QUOTE TICKS) 
MESSAGE)))))) (COMPILED-ASK (QUOTE |SOMETHING(PLAN AFTER ? TICKS %)|) (QUOTE SOMETHING)))))) 
(CDDDDR :MESSAGE) (CADDR :MESSAGE))) 
(SETQ SOMETHING-PLAN-47 (QUOTE SOMETHING-PLAN-47)) 
(DEFPROP SOMETHING-PLAN-47 (PLAN AFTER RECEIVING ? TO ?) METHOD-PATTERN) 
(DEFUN SOMETHING-PLAN-47 NIL ((LAMBDA (MESSAGE-FORM EVENT-PATTERN) (ASK1 (ACTOR-OF :SELF) 
(CONS (QUOTE DO) (CONS (QUOTE ONCE) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (CONS 
(QUOTE DIRECTOR-SYMBOL-FOR-AND-PATTERN) (CONS (QUOTE ?THE-WHOLE-MESSAGE) (CONS EVENT-PATTERN 
NIL))) (CONS (CONS (QUOTE LET) (CONS (CONS (CONS (QUOTE MESSAGE) (CONS MESSAGE-FORM NIL)) 
NIL) (CONS (CONS (QUOTE LET) (CONS (CONS (CONS (QUOTE RESULT) (CONS (CONS (QUOTE 
ASK-IF-UNDERSTOOD) (CONS (QUOTE :SELF) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-UNPACK) (CONS 
(CONS (QUOTE DIRECTOR-SYMBOL-FOR-EVAL) (QUOTE (THE-WHOLE-MESSAGE))) NIL)) NIL))) NIL)) NIL) 
(CONS (CONS (QUOTE AND) (CONS (QUOTE MESSAGE) (CONS (CONS (QUOTE ASK-OLD) (CONS (QUOTE 
:SELF) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-UNPACK) (CONS (CONS (QUOTE 
DIRECTOR-SYMBOL-FOR-EVAL) (QUOTE (MESSAGE))) NIL)) NIL))) NIL))) (QUOTE (RESULT))))) NIL))) 
NIL)))))) NIL)) (CADR (CDDDDR :MESSAGE)) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-PLAN-48 (QUOTE SOMETHING-PLAN-48)) 
(DEFPROP SOMETHING-PLAN-48 (PLAN AFTER RECEIVING ? TO ALWAYS ?) METHOD-PATTERN) 
(DEFUN SOMETHING-PLAN-48 NIL ((LAMBDA (MESSAGE-FORM EVENT-PATTERN) (ASK1 (ACTOR-OF :SELF) 
(CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (CONS (QUOTE 
DIRECTOR-SYMBOL-FOR-AND-PATTERN) (CONS (QUOTE ?THE-WHOLE-MESSAGE) (CONS EVENT-PATTERN NIL))) 
(CONS (CONS (QUOTE LET) (CONS (CONS (CONS (QUOTE MESSAGE) (CONS MESSAGE-FORM NIL)) NIL) 
(CONS (CONS (QUOTE LET) (CONS (CONS (CONS (QUOTE RESULT) (CONS (CONS (QUOTE 
ASK-IF-UNDERSTOOD) (CONS (QUOTE :SELF) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-UNPACK) (CONS 
(CONS (QUOTE DIRECTOR-SYMBOL-FOR-EVAL) (QUOTE (THE-WHOLE-MESSAGE))) NIL)) NIL))) NIL)) NIL) 
(CONS (CONS (QUOTE AND) (CONS (QUOTE MESSAGE) (CONS (CONS (QUOTE ASK-OLD) (CONS (QUOTE 
:SELF) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-UNPACK) (CONS (CONS (QUOTE 
DIRECTOR-SYMBOL-FOR-EVAL) (QUOTE (MESSAGE))) NIL)) NIL))) NIL))) (QUOTE (RESULT))))) NIL))) 
NIL))))) NIL)) (CADDR (CDDDDR :MESSAGE)) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-REPEAT-49 (QUOTE SOMETHING-REPEAT-49)) 
(DEFPROP SOMETHING-REPEAT-49 (REPEAT ? FOREVER) METHOD-PATTERN) 
(DEFUN SOMETHING-REPEAT-49 NIL ((LAMBDA (MESSAGE) (ASK1 (ACTOR-OF :SELF) MESSAGE NIL) (LET 
((:MESSAGE (CONS (QUOTE PLAN) (CONS (QUOTE NEXT) (CONS (QUOTE REPEAT) (CONS MESSAGE (QUOTE 
(FOREVER)))))))) (COMPILED-ASK (QUOTE |SOMETHING(PLAN NEXT REPEAT ? FOREVER)|) (QUOTE 
SOMETHING)))) (CADR :MESSAGE))) 
(SETQ SOMETHING-REPEAT-50 (QUOTE SOMETHING-REPEAT-50)) 
(DEFPROP SOMETHING-REPEAT-50 (REPEAT ? ? TIMES EVERY ? TICKS %) METHOD-PATTERN) 
(DEFUN SOMETHING-REPEAT-50 NIL ((LAMBDA (FOLLOWUP SO-MANY NUMBER MESSAGE) (ASK1 (ACTOR-OF 
:SELF) MESSAGE NIL) (COND ((> NUMBER 1) (LET ((:MESSAGE (CONS (QUOTE PLAN) (CONS (QUOTE 
AFTER) (CONS SO-MANY (CONS (QUOTE TICKS) (CONS (QUOTE REPEAT) (CONS MESSAGE (CONS (1- 
NUMBER) (CONS (QUOTE TIMES) (CONS (QUOTE EVERY) (CONS SO-MANY (CONS (QUOTE TICKS) 
FOLLOWUP))))))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(PLAN AFTER ? TICKS REPEAT ? ? TIMES EVERY ? TICKS %)|) (QUOTE SOMETHING)))) (T 
(COND ((EQ (FIRST FOLLOWUP) (QUOTE THEN)) (LET ((:MESSAGE (CONS (QUOTE PLAN) (CONS (QUOTE 
AFTER) (CONS SO-MANY (CONS (QUOTE TICKS) (REST FOLLOWUP))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(PLAN AFTER ? TICKS %)|) (QUOTE SOMETHING)))))))) (CDDDR (CDDDDR :MESSAGE)) (CADR 
(CDDDDR :MESSAGE)) (CADDR :MESSAGE) (CADR :MESSAGE))) 
(SETQ SOMETHING-REPEAT-51 (QUOTE SOMETHING-REPEAT-51)) 
(DEFPROP SOMETHING-REPEAT-51 (REPEAT ? ? TIMES %) METHOD-PATTERN) 
(DEFUN SOMETHING-REPEAT-51 NIL ((LAMBDA (FOLLOWUP NUMBER MESSAGE) (COND ((> NUMBER 1) (ASK1 
(ACTOR-OF :SELF) MESSAGE NIL) (LET ((:MESSAGE (CONS (QUOTE PLAN) (CONS (QUOTE NEXT) (CONS 
(QUOTE REPEAT) (CONS MESSAGE (CONS (1- NUMBER) (CONS (QUOTE TIMES) FOLLOWUP)))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(PLAN NEXT REPEAT ? ? TIMES %)|) (QUOTE SOMETHING)))) (T 
(COND ((EQ (FIRST FOLLOWUP) (QUOTE THEN)) (ASK1 (ACTOR-OF :SELF) (REST FOLLOWUP) NIL)))))) 
(CDDDDR :MESSAGE) (CADDR :MESSAGE) (CADR :MESSAGE))) 
(SETQ SOMETHING-ASK-52 (QUOTE SOMETHING-ASK-52)) 
(DEFPROP SOMETHING-ASK-52 (ASK YOUR ? %) METHOD-PATTERN) 
(DEFPROP SOMETHING-ASK-52 SOMETHING-ASK-52-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-ASK-52 NIL ((LAMBDA (MESSAGE VARIABLE) (ASK1 (ACTOR-OF (LET ((:MESSAGE 
(CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS VARIABLE NIL))))) (COMPILED-ASK (QUOTE 
|SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING)))) MESSAGE NIL)) (CDDDR :MESSAGE) (CADDR 
:MESSAGE))) 
(PROGN (DEFPROP SOMETHING-ASK-52-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-ASK-52-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-ASK-53 (QUOTE SOMETHING-ASK-53)) 
(DEFPROP SOMETHING-ASK-53 (ASK EACH OF YOUR ? %) METHOD-PATTERN) 
(DEFPROP SOMETHING-ASK-53 SOMETHING-ASK-53-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-ASK-53 NIL ((LAMBDA (MESSAGE VARIABLE) (MAPCAR (FUNCTION (LAMBDA (ACTOR) 
(ASK1 (ACTOR-OF ACTOR) MESSAGE NIL))) (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE 
YOUR) (CONS VARIABLE NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) (QUOTE 
SOMETHING))))) (REST (CDDDDR :MESSAGE)) (FIRST (CDDDDR :MESSAGE)))) 
(PROGN (DEFPROP SOMETHING-ASK-53-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-ASK-53-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-ASK-54 (QUOTE SOMETHING-ASK-54)) 
(DEFPROP SOMETHING-ASK-54 (ASK EACH OF ? %) METHOD-PATTERN) 
(DEFUN SOMETHING-ASK-54 NIL ((LAMBDA (MESSAGE OTHERS) (MAPCAR (FUNCTION (LAMBDA (ACTOR) 
(ASK1 (ACTOR-OF ACTOR) MESSAGE NIL))) OTHERS)) (CDDDDR :MESSAGE) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-ASK-55 (QUOTE SOMETHING-ASK-55)) 
(DEFPROP SOMETHING-ASK-55 (ASK ? %) METHOD-PATTERN) 
(DEFPROP SOMETHING-ASK-55 SOMETHING-ASK-55-MACRO MACRO-VERSION) 
(DEFUN SOMETHING-ASK-55 NIL ((LAMBDA (MESSAGE ANOTHER) (ASK1 (ACTOR-OF ANOTHER) MESSAGE 
NIL)) (CDDR :MESSAGE) (CADR :MESSAGE))) 
(PROGN (DEFPROP SOMETHING-ASK-55-MACRO |DSK:KEN;SOME MACROS| AUTOLOAD) (DEFPROP 
SOMETHING-ASK-55-MACRO T DIRECTOR-MACRO?)) 
(SETQ SOMETHING-KEEP-56 (QUOTE SOMETHING-KEEP-56)) 
(DEFPROP SOMETHING-KEEP-56 (KEEP DOING UNTIL ? %) METHOD-PATTERN) 
(DEFUN SOMETHING-KEEP-56 NIL ((LAMBDA (MESSAGE PREDICATE) (DO ((RESULT (ASK1 (ACTOR-OF 
:SELF) MESSAGE NIL) (ASK1 (ACTOR-OF :SELF) MESSAGE NIL))) ((FUNCALL PREDICATE RESULT) 
RESULT))) (CDDDDR :MESSAGE) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-DO-57 (QUOTE SOMETHING-DO-57)) 
(DEFPROP SOMETHING-DO-57 (DO THE FOLLOWING: %) METHOD-PATTERN) 
(DEFUN SOMETHING-DO-57 NIL ((LAMBDA (MESSAGES) (BODY-OF-DO-THE-FOLLOWING: MESSAGES)) (CDDDR 
:MESSAGE))) 
(SETQ SOMETHING-ARE-58 (QUOTE SOMETHING-ARE-58)) 
(DEFPROP SOMETHING-ARE-58 (ARE YOU (DIRECTOR-SYMBOL-FOR-OR-PATTERN A AN) ?) METHOD-PATTERN) 
(DEFUN SOMETHING-ARE-58 NIL ((LAMBDA (TYPE) (IS-ANY-ANCESTOR-OF :SELF (ACTOR-OF TYPE))) 
(CADDDR :MESSAGE))) 
(SETQ SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59 (QUOTE 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59)) 
(DEFPROP SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59 (DIRECTOR-SYMBOL-FOR-AND-PATTERN ? 
(FIND ANCESTOR MATCHING ?)) METHOD-PATTERN) 
(DEFUN SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59 NIL ((LAMBDA (NAME-PATTERN 
THE-WHOLE-MESSAGE) (LET ((NAME (NAME-OF :SELF))) (COND ((EQ NAME (QUOTE SOMETHING)) NIL) 
((MATCH NAME NAME-PATTERN) :SELF) (T (LET ((:MESSAGE (CONS (QUOTE ASK) (CONS (QUOTE YOUR) 
(CONS (QUOTE PARENT) THE-WHOLE-MESSAGE))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK YOUR PARENT %)|) (QUOTE SOMETHING))))))) (CADDDR :MESSAGE) :MESSAGE)) 
(SETQ SOMETHING-RECALL-60 (QUOTE SOMETHING-RECALL-60)) 
(DEFPROP SOMETHING-RECALL-60 (RECALL INTERNAL (DIRECTOR-SYMBOL-FOR-OR-PATTERN METHOD CLAUSE) 
FOR %) METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-60 NIL ((LAMBDA (MESSAGE) (METHOD-NAME-THAT-MATCHES :SELF MESSAGE)) 
(CDDDDR :MESSAGE))) 
(SETQ SOMETHING-RECALL-61 (QUOTE SOMETHING-RECALL-61)) 
(DEFPROP SOMETHING-RECALL-61 (RECALL (DIRECTOR-SYMBOL-FOR-OR-PATTERN METHOD CLAUSE) FOR %) 
METHOD-PATTERN) 
(DEFUN SOMETHING-RECALL-61 NIL ((LAMBDA (MESSAGE) (HUMANIFY-METHOD (METHOD-NAME-THAT-MATCHES 
:SELF MESSAGE))) (CDDDR :MESSAGE))) 
(SETQ SOMETHING-FORGET-62 (QUOTE SOMETHING-FORGET-62)) 
(DEFPROP SOMETHING-FORGET-62 (FORGET YOUR ?) METHOD-PATTERN) 
(DEFUN SOMETHING-FORGET-62 NIL ((LAMBDA (VARIABLE) (COND ((EQ VARIABLE (QUOTE ?)) (DO ((I 
(LET ((:MESSAGE (QUOTE (LIST ALL YOUR VARIABLE NAMES)))) (COMPILED-ASK (QUOTE 
|SOMETHING(LIST ALL YOUR VARIABLE NAMES)|) (QUOTE SOMETHING))) (REST I))) ((NULL I)) (LET 
((VARIABLE-NAME (FIRST I))) (COND ((MEMQ VARIABLE-NAME (QUOTE (PARENT NAME)))) ((= (GETCHARN 
VARIABLE-NAME 1) 63)) ((= (GETCHARN VARIABLE-NAME 1) 37)) (T (LET ((:MESSAGE (CONS (QUOTE 
FORGET) (CONS (QUOTE YOUR) (CONS VARIABLE-NAME NIL))))) (COMPILED-ASK (QUOTE 
|SOMETHING(FORGET YOUR ?)|) (QUOTE SOMETHING)))))))) (T (LET ((:MESSAGE (CONS (QUOTE REMOVE) 
(CONS (QUOTE CLAUSE) (CONS (QUOTE FOR) (CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS 
VARIABLE NIL)))))))) (COMPILED-ASK (QUOTE |SOMETHING(REMOVE CLAUSE FOR RECALL YOUR ?)|) 
(QUOTE SOMETHING))) (LET ((:MESSAGE (CONS (QUOTE REMOVE) (CONS (QUOTE CLAUSE) (CONS (QUOTE 
FOR) (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS VARIABLE (QUOTE (TO ANYTHING)))))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(REMOVE CLAUSE FOR SET YOUR ? TO ANYTHING)|) (QUOTE 
SOMETHING))))) NO-VALUE) (CADDR :MESSAGE))) 
(SETQ SOMETHING-REMOVE-63 (QUOTE SOMETHING-REMOVE-63)) 
(DEFPROP SOMETHING-REMOVE-63 (REMOVE (DIRECTOR-SYMBOL-FOR-OR-PATTERN METHOD CLAUSE) FOR %) 
METHOD-PATTERN) 
(DEFUN SOMETHING-REMOVE-63 NIL ((LAMBDA (MESSAGE) (REMOVE-METHOD-NAMED 
(METHOD-NAME-THAT-MATCHES-JUST-ACTOR :SELF (METHODS-OF :SELF) MESSAGE) :SELF)) (CDDDR 
:MESSAGE))) 
(SETQ SOMETHING-TRACE-64 (QUOTE SOMETHING-TRACE-64)) 
(DEFPROP SOMETHING-TRACE-64 (TRACE %) METHOD-PATTERN) 
(DEFUN SOMETHING-TRACE-64 NIL ((LAMBDA (PATTERN+ACTION) (DIRECTOR-TRACE :SELF (FIRST 
PATTERN+ACTION) (REST PATTERN+ACTION))) (REST :MESSAGE))) 
(SETQ SOMETHING-UNTRACE-65 (QUOTE SOMETHING-UNTRACE-65)) 
(DEFPROP SOMETHING-UNTRACE-65 (UNTRACE ?) METHOD-PATTERN) 
(DEFUN SOMETHING-UNTRACE-65 NIL ((LAMBDA (PATTERN) (DIRECTOR-UNTRACE :SELF PATTERN)) (CADR 
:MESSAGE))) 
(SETQ SOMETHING-UNTRACE-66 (QUOTE SOMETHING-UNTRACE-66)) 
(DEFPROP SOMETHING-UNTRACE-66 (UNTRACE) METHOD-PATTERN) 
(DEFUN SOMETHING-UNTRACE-66 NIL ((LAMBDA (TRACER) (AND (EXISTS? TRACER) 
(DIRECTOR-UNTRACE-ALL :SELF TRACER))) (CONS (QUOTE TRACER-OF) (CONS (NAME-OF :SELF) NIL)))) 
(SETQ SOMETHING-TRANSMISSION-67 (QUOTE SOMETHING-TRANSMISSION-67)) 
(DEFPROP SOMETHING-TRANSMISSION-67 (TRANSMISSION ? BEGINNING) METHOD-PATTERN) 
(DEFUN SOMETHING-TRANSMISSION-67 NIL NIL) 
(SETQ SOMETHING-TRANSMISSION-68 (QUOTE SOMETHING-TRANSMISSION-68)) 
(DEFPROP SOMETHING-TRANSMISSION-68 (TRANSMISSION ? RETURNING ?) METHOD-PATTERN) 
(DEFUN SOMETHING-TRANSMISSION-68 NIL ((LAMBDA (RESULT) RESULT) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-TELL-69 (QUOTE SOMETHING-TELL-69)) 
(DEFPROP SOMETHING-TELL-69 (TELL EACH OF YOUR ? WHENEVER YOUR ? IS CHANGED) METHOD-PATTERN) 
(DEFUN SOMETHING-TELL-69 NIL ((LAMBDA (VARIABLE OTHERS) (LET ((:MESSAGE (CONS (QUOTE ASK) 
(CONS (QUOTE EACH) (CONS (QUOTE OF) (CONS (QUOTE YOUR) (CONS OTHERS (CONS (QUOTE NOTICE) 
(CONS (QUOTE THAT) (CONS VARIABLE (CONS (QUOTE OF) (CONS (NAME-OF :SELF) (CONS (QUOTE IS) 
(CONS (QUOTE NOW) (CONS (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS 
VARIABLE NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING))) 
NIL))))))))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ASK EACH OF YOUR ? NOTICE THAT ? OF ? IS NOW ?)|) (QUOTE SOMETHING))) (LET 
((:MESSAGE (CONS (QUOTE ADD) (CONS VARIABLE (CONS (QUOTE TO) (CONS (QUOTE YOUR) (CONS (QUOTE 
LIST) (CONS (QUOTE OF) (CONS (CONS (QUOTE VARIABLES-DEPENDED-UPON-BY) (CONS OTHERS NIL)) 
NIL))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ADD ? TO YOUR LIST OF (VARIABLES-DEPENDED-UPON-BY ?))|) (QUOTE SOMETHING))) (ASK1 
(ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (CONS 
(QUOTE SET) (CONS (QUOTE YOUR) (CONS VARIABLE (QUOTE (TO ?NEW-VALUE))))) (CONS (CONS (QUOTE 
ASK-OLD) (CONS (QUOTE :SELF) (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS VARIABLE (CONS 
(QUOTE TO) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-EVAL) (QUOTE (NEW-VALUE))) NIL))))))) 
(CONS (CONS (QUOTE TELL-OTHERS-NEW-VALUE) (CONS (CONS (QUOTE QUOTE) (CONS VARIABLE NIL)) 
(CONS (QUOTE NEW-VALUE) (CONS (CONS (QUOTE QUOTE) (CONS OTHERS NIL)) NIL)))) (QUOTE 
(NEW-VALUE)))))))) NIL)) (CADDDR (CDDDDR :MESSAGE)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ SOMETHING-TELL-70 (QUOTE SOMETHING-TELL-70)) 
(DEFPROP SOMETHING-TELL-70 (TELL YOUR ? WHENEVER YOUR ? IS CHANGED) METHOD-PATTERN) 
(DEFUN SOMETHING-TELL-70 NIL ((LAMBDA (VARIABLE OTHER) (LET ((:MESSAGE (CONS (QUOTE ASK) 
(CONS (QUOTE YOUR) (CONS OTHER (CONS (QUOTE TO) (CONS (QUOTE NOTICE) (CONS (QUOTE THAT) 
(CONS VARIABLE (CONS (QUOTE OF) (CONS (NAME-OF :SELF) (CONS (QUOTE IS) (CONS (QUOTE NOW) 
(CONS (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS VARIABLE NIL))))) 
(COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING))) NIL)))))))))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(ASK YOUR ? TO NOTICE THAT ? OF ? IS NOW ?)|) (QUOTE 
SOMETHING))) (LET ((:MESSAGE (CONS (QUOTE ADD) (CONS VARIABLE (CONS (QUOTE TO) (CONS (QUOTE 
YOUR) (CONS (QUOTE LIST) (CONS (QUOTE OF) (CONS (CONS (QUOTE VARIABLES-DEPENDED-UPON-BY) 
(CONS OTHER NIL)) NIL))))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(ADD ? TO YOUR LIST OF (VARIABLES-DEPENDED-UPON-BY ?))|) (QUOTE SOMETHING))) (ASK1 
(ACTOR-OF :SELF) (CONS (QUOTE DO) (CONS (QUOTE WHEN) (CONS (QUOTE RECEIVING) (CONS (CONS 
(QUOTE SET) (CONS (QUOTE YOUR) (CONS VARIABLE (QUOTE (TO ?NEW-VALUE))))) (CONS (CONS (QUOTE 
ASK-OLD) (CONS (QUOTE :SELF) (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS VARIABLE (CONS 
(QUOTE TO) (CONS (CONS (QUOTE DIRECTOR-SYMBOL-FOR-EVAL) (QUOTE (NEW-VALUE))) NIL))))))) 
(CONS (CONS (QUOTE TELL-OTHER-NEW-VALUE) (CONS (CONS (QUOTE QUOTE) (CONS VARIABLE NIL)) 
(CONS (QUOTE NEW-VALUE) (CONS (CONS (QUOTE QUOTE) (CONS OTHER NIL)) NIL)))) (QUOTE 
(NEW-VALUE)))))))) NIL)) (CADR (CDDDDR :MESSAGE)) (CADDR :MESSAGE))) 
(SETQ SOMETHING-NOTICE-71 (QUOTE SOMETHING-NOTICE-71)) 
(DEFPROP SOMETHING-NOTICE-71 (NOTICE THAT ? OF ? IS NOW ?) METHOD-PATTERN) 
(DEFUN SOMETHING-NOTICE-71 NIL NIL) 
(SETQ SOMETHING-ABSORB-72 (QUOTE SOMETHING-ABSORB-72)) 
(DEFPROP SOMETHING-ABSORB-72 (ABSORB YOUR PARTS) METHOD-PATTERN) 
(DEFUN SOMETHING-ABSORB-72 NIL (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE YOUR) (CONS 
(QUOTE PARTS) (CONS (QUOTE TO) (CONS (MAPCAR (FUNCTION (LAMBDA (PART-NAME) (LET ((PART (LET 
((:SELF (ACTOR-OF PART-NAME)) (:MESSAGE (QUOTE (REMOB)))) (COMPILED-ASK (QUOTE 
|SOMETHING(REMOB)|) (QUOTE SOMETHING))))) (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE 
YOUR) (CONS PART-NAME (CONS (QUOTE TO) (CONS PART NIL))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(SET YOUR ? TO ?)|) (QUOTE SOMETHING))) PART))) (LET ((:MESSAGE (QUOTE (RECALL 
YOUR PARTS)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR PARTS)|) (QUOTE SOMETHING)))) 
NIL))))))) (COMPILED-ASK (QUOTE |SOMETHING(SET YOUR PARTS TO ?)|) (QUOTE SOMETHING))) 
NO-VALUE) 
(SETQ SOMETHING-PRINT-73 (QUOTE SOMETHING-PRINT-73)) 
(DEFPROP SOMETHING-PRINT-73 (PRINT %) METHOD-PATTERN) 
(DEFUN SOMETHING-PRINT-73 NIL ((LAMBDA (OPTION) (FANCY-PRINT OPTION)) (REST :MESSAGE))) 
(SETQ SOMETHING-COMPARE-74 (QUOTE SOMETHING-COMPARE-74)) 
(DEFPROP SOMETHING-COMPARE-74 (COMPARE YOURSELF WITH ?) METHOD-PATTERN) 
(DEFUN SOMETHING-COMPARE-74 NIL ((LAMBDA (OTHER) (LET ((NAME (ACTOR-OF :SELF))) (LET 
((COMPARISON (LET ((:SELF (ACTOR-OF (QUOTE SOMETHING))) (:MESSAGE (CONS (QUOTE MAKE) (CONS 
(CONS (QUOTE COMPARISON-BETWEEN) (CONS NAME (CONS OTHER NIL))) NIL)))) (COMPILED-ASK (QUOTE 
|SOMETHING(MAKE (COMPARISON-BETWEEN ? ?))|) (QUOTE SOMETHING))))) (COND ((EXISTS? OTHER) 
(LET ((MY-VARIABLES (LET ((:MESSAGE (QUOTE (LIST ALL YOUR VARIABLE NAMES)))) (COMPILED-ASK 
(QUOTE |SOMETHING(LIST ALL YOUR VARIABLE NAMES)|) (QUOTE SOMETHING)))) (OTHERS-VARIABLES 
(LET ((:SELF (ACTOR-OF OTHER)) (:MESSAGE (QUOTE (LIST ALL YOUR VARIABLE NAMES)))) 
(COMPILED-ASK (QUOTE |SOMETHING(LIST ALL YOUR VARIABLE NAMES)|) (QUOTE SOMETHING))))) (DO 
((I (UNION MY-VARIABLES OTHERS-VARIABLES) (REST I))) ((NULL I)) (OR (EQ (FIRST I) (QUOTE 
NAME)) (LET ((MY-VALUE (LET ((:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE YOUR) (CONS (FIRST 
I) NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) (QUOTE SOMETHING)))) 
(OTHERS-VALUE (LET ((:SELF (ACTOR-OF OTHER)) (:MESSAGE (CONS (QUOTE RECALL) (CONS (QUOTE 
YOUR) (CONS (FIRST I) NIL))))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR ?)|) (QUOTE 
SOMETHING))))) (COND ((NOT (EQUAL MY-VALUE OTHERS-VALUE)) (LET ((:SELF (ACTOR-OF 
COMPARISON)) (:MESSAGE (CONS (QUOTE MEMORIZE) (CONS (CONS (QUOTE DIFFERENCE:) (CONS (QUOTE 
TYPE) (CONS (QUOTE VARIABLE) (CONS (QUOTE VARIABLE) (CONS (FIRST I) (CONS (CONS OTHER (QUOTE 
(VALUE))) (CONS OTHERS-VALUE (CONS (CONS NAME (QUOTE (VALUE))) (CONS MY-VALUE NIL))))))))) 
NIL)))) (COMPILED-ASK (QUOTE 
|SOMETHING(MEMORIZE (DIFFERENCE: TYPE VARIABLE VARIABLE ? (? VALUE) ? (? VALUE) ?))|) (QUOTE 
SOMETHING)))))))))) (T (LET ((:SELF (ACTOR-OF COMPARISON)) (:MESSAGE (CONS (QUOTE MEMORIZE) 
(CONS (CONS (QUOTE DIFFERENCE:) (CONS (QUOTE TYPE) (CONS (QUOTE EXISTENCE) (CONS (QUOTE 
WHO-EXISTS) (CONS NAME (CONS (QUOTE WHO-DOESNT) (CONS OTHER NIL))))))) NIL)))) (COMPILED-ASK 
(QUOTE |SOMETHING(MEMORIZE (DIFFERENCE: TYPE EXISTENCE WHO-EXISTS ? WHO-DOESNT ?))|) (QUOTE 
SOMETHING))))) COMPARISON))) (CADDDR :MESSAGE))) 
(SETQ SOMETHING-COMPILE-75 (QUOTE SOMETHING-COMPILE-75)) 
(DEFPROP SOMETHING-COMPILE-75 (COMPILE MESSAGE %) METHOD-PATTERN) 
(DEFUN SOMETHING-COMPILE-75 NIL ((LAMBDA (MESSAGE) (LISPIFY-TRANSMISSION :SELF MESSAGE 
(NAME-OF :SELF) NIL)) (CDDR :MESSAGE))) 
(SETQ SOMETHING-COMPILE-76 (QUOTE SOMETHING-COMPILE-76)) 
(DEFPROP SOMETHING-COMPILE-76 (COMPILE %) METHOD-PATTERN) 
(DEFUN SOMETHING-COMPILE-76 NIL ((LAMBDA (FILE-NAME) (COMPILE-AND-PRINT-ACTOR (NAME-OF 
:SELF) FILE-NAME)) (REST :MESSAGE))) 
(SETQ SOMETHING-SAVE-77 (QUOTE SOMETHING-SAVE-77)) 
(DEFPROP SOMETHING-SAVE-77 (SAVE %) METHOD-PATTERN) 
(DEFUN SOMETHING-SAVE-77 NIL ((LAMBDA (FILE-NAME) (SAVE-ACTOR-ON-FILE :SELF FILE-NAME)) 
(REST :MESSAGE))) 
(SETQ SOMETHING-HELP-78 (QUOTE SOMETHING-HELP-78)) 
(DEFPROP SOMETHING-HELP-78 (HELP %) METHOD-PATTERN) 
(DEFUN SOMETHING-HELP-78 NIL ((LAMBDA (PATTERN) (LET ((OLD-CRUNIT (CRUNIT)) (HELP-FILE (CONS 
:HELP-STORAGE-PLACE (GET (NAME-OF :SELF) (QUOTE HELP-FILE)))) (PARENT (LET ((:MESSAGE (QUOTE 
(RECALL YOUR PARENT)))) (COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR PARENT)|) (QUOTE 
SOMETHING))))) (COND ((COND ((EQ (LET ((:MESSAGE (QUOTE (RECALL YOUR HELP-LOADED-FOR)))) 
(COMPILED-ASK (QUOTE |SOMETHING(RECALL YOUR HELP-LOADED-FOR)|) (QUOTE SOMETHING))) :SELF)) 
((PROBEF HELP-FILE) (DIRECTOR-LOAD HELP-FILE (CONS (QUOTE TO) (CONS (QUOTE GET) (CONS (QUOTE 
HELP) (CONS (QUOTE FOR) (CONS :SELF NIL)))))) (LET ((:MESSAGE (CONS (QUOTE SET) (CONS (QUOTE 
YOUR) (CONS (QUOTE HELP-LOADED-FOR) (CONS (QUOTE TO) (CONS (NAME-OF :SELF) NIL))))))) 
(COMPILED-ASK (QUOTE |SOMETHING(SET YOUR HELP-LOADED-FOR TO ?)|) (QUOTE SOMETHING))) (APPLY 
(QUOTE CRUNIT) OLD-CRUNIT))) (MAPC (FUNCTION (LAMBDA (HELP) (TERPRI) (TERPRI) (PRINC (FIRST 
HELP)) (PRINC (QUOTE | |)) (PRINC-OR-PRINT (SECOND HELP) NIL (QUOTE GRIND)) (PRINC (QUOTE 
| |)) (PRINC (THIRD HELP)) (MAPC (FUNCTION (LAMBDA (LINE) (TYPE LINE))) (NTH-REST 3 HELP)))) 
(LET ((:MESSAGE (CONS (QUOTE COLLECT) (CONS (QUOTE ITEMS) (CONS (QUOTE MEMORIZED) (CONS 
(QUOTE MATCHING) (CONS (CONS (QUOTE |When receiving|) (CONS (OR PATTERN (QUOTE ?)) (QUOTE (I 
%)))) NIL))))))) (COMPILED-ASK (QUOTE 
|SOMETHING(COLLECT ITEMS MEMORIZED MATCHING (When receiving ? I %))|) (QUOTE SOMETHING))))) 
(T (TYPE (QUOTE |Sorry no help available|)))) (COND (PARENT (TERPRI) (TYPE (CONS (QUOTE 
|More help can be gotten by asking my parent|) (CONS PARENT (QUOTE (|for help|)))))))) 
NO-VALUE) (REST :MESSAGE))) 
(SETQ SOMETHING-WARNING-79 (QUOTE SOMETHING-WARNING-79)) 
(DEFPROP SOMETHING-WARNING-79 (WARNING %) METHOD-PATTERN) 
(DEFUN SOMETHING-WARNING-79 NIL ((LAMBDA (SOME-WARNING) (LET ((:MESSAGE (CONS (QUOTE 
MEMORIZE) (CONS SOME-WARNING NIL)))) (COMPILED-ASK (QUOTE |SOMETHING(MEMORIZE ?)|) (QUOTE 
SOMETHING))) (WARNING (NAME-OF :SELF) SOME-WARNING)) (REST :MESSAGE))) 
(SETQ SOMETHING-SHOULD-80 (QUOTE SOMETHING-SHOULD-80)) 
(DEFPROP SOMETHING-SHOULD-80 (SHOULD NOT HAPPEN %) METHOD-PATTERN) 
(DEFUN SOMETHING-SHOULD-80 NIL ((LAMBDA (WARNING) (LET ((:MESSAGE (CONS (QUOTE MEMORIZE) 
(CONS WARNING NIL)))) (COMPILED-ASK (QUOTE |SOMETHING(MEMORIZE ?)|) (QUOTE SOMETHING))) 
(SHOULDNT-HAPPEN (NAME-OF :SELF) WARNING)) (CDDDR :MESSAGE))) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL (UNIVERSE . DEFAULT-UNIVERSE))))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92 T PRIVATE?) 
(SETQ SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93 T PRIVATE?) 
(DEFUN ORIGINAL-METHODS-OF-SOMETHING (MESSAGE ACTOR) (COND ((AND (EQ (FIRST MESSAGE) (QUOTE 
SET)) (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (COND ((AND (EQ (CADDR MESSAGE) (QUOTE 
OFFSPRING)) (AND (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))) (OR (AND 
(EQ ACTOR :SELF) SOMETHING-SET-84) SOMETHING-SET-14)))) ((AND (EQ (CADDR MESSAGE) (QUOTE 
PARENT)) (AND (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))) (OR 
SOMETHING-SET-12 SOMETHING-SET-14)))) ((AND (EQ (CADDR MESSAGE) (QUOTE NAME)) (AND (AND (EQ 
(CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))) (OR SOMETHING-SET-13 
SOMETHING-SET-14)))) ((AND (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR 
MESSAGE))) SOMETHING-SET-14)))))) ((AND (EQ (FIRST MESSAGE) (QUOTE RECALL)) (COND ((AND (EQ 
(CADR MESSAGE) (QUOTE YOUR)) (COND ((AND (EQ (CADDR MESSAGE) (QUOTE OFFSPRING)) (AND (NULL 
(CDDDR MESSAGE)) (OR (AND (EQ ACTOR :SELF) SOMETHING-RECALL-83) SOMETHING-RECALL-16)))) 
((AND (EQ (CADDR MESSAGE) (QUOTE NAME)) (AND (NULL (CDDDR MESSAGE)) (OR SOMETHING-RECALL-2 
SOMETHING-RECALL-16)))) ((AND (EQ (CADDR MESSAGE) (QUOTE SIBLINGS)) (AND (NULL (CDDDR 
MESSAGE)) (OR SOMETHING-RECALL-6 SOMETHING-RECALL-16)))) ((AND (EQ (CADDR MESSAGE) (QUOTE 
DESCENDANTS)) (AND (NULL (CDDDR MESSAGE)) (OR SOMETHING-RECALL-7 SOMETHING-RECALL-16)))) 
((AND (EQ (CADDR MESSAGE) (QUOTE CHILDLESS-DESCENDANTS)) (AND (NULL (CDDDR MESSAGE)) (OR 
SOMETHING-RECALL-8 SOMETHING-RECALL-16)))) ((AND (EQ (CADDR MESSAGE) (QUOTE 
REVERSED-DESCENDANTS)) (AND (NULL (CDDDR MESSAGE)) (OR SOMETHING-RECALL-9 
SOMETHING-RECALL-16)))) ((AND (EQ (CADDR MESSAGE) (QUOTE REVERSED-CHILDLESS-DESCENDANTS)) 
(AND (NULL (CDDDR MESSAGE)) (OR SOMETHING-RECALL-10 SOMETHING-RECALL-16)))) ((AND (EQ (CADDR 
MESSAGE) (QUOTE PRIVATE-VARIABLE-NAMES)) (AND (NULL (CDDDR MESSAGE)) (OR SOMETHING-RECALL-11 
SOMETHING-RECALL-16)))) ((AND (ONE-LONG (CDDR MESSAGE)) SOMETHING-RECALL-16))))) ((AND (AND 
(EQ (CADR MESSAGE) (QUOTE AN)) (AND (EQ (CADDR MESSAGE) (QUOTE ITEM)) (AND (EQ (CADDDR 
MESSAGE) (QUOTE MATCHING)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE THEN)) (ONE-LONG (CDDR 
(CDDDDR MESSAGE))))))) SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38)) ((AND (AND (EQ (CADR 
MESSAGE) (QUOTE IF)) (AND (EQ (CADDR MESSAGE) (QUOTE ANY)) (AND (EQ (CADDDR MESSAGE) (QUOTE 
ITEMS)) (AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE MATCH)) (ONE-LONG (REST (CDDDDR 
MESSAGE))))))) SOMETHING-RECALL-39)) ((AND (AND (EQ (CADR MESSAGE) (QUOTE EACH)) (AND (EQ 
(CADDR MESSAGE) (QUOTE ITEM)) (AND (EQ (CADDDR MESSAGE) (QUOTE MATCHING)) (AND (EQ (CADR 
(CDDDDR MESSAGE)) (QUOTE THEN)) (ONE-LONG (CDDR (CDDDDR MESSAGE))))))) 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40)) ((AND (AND (EQ (CADR MESSAGE) (QUOTE 
INTERNAL)) (AND (MEMQ (CADDR MESSAGE) (QUOTE (METHOD CLAUSE))) (EQ (CADDDR MESSAGE) (QUOTE 
FOR)))) SOMETHING-RECALL-60)) ((AND (AND (MEMQ (CADR MESSAGE) (QUOTE (METHOD CLAUSE))) (EQ 
(CADDR MESSAGE) (QUOTE FOR))) SOMETHING-RECALL-61))))) ((AND (EQ (FIRST MESSAGE) (QUOTE DO)) 
(COND ((AND (AND (EQ (CADR MESSAGE) (QUOTE ONCE)) (AND (EQ (CADDR MESSAGE) (QUOTE WHEN)) 
(AND (EQ (CADDDR MESSAGE) (QUOTE RECEIVING)) (CDDDDR MESSAGE)))) SOMETHING-DO-3)) ((AND (AND 
(EQ (CADR MESSAGE) (QUOTE ONLY)) (AND (EQ (CADDR MESSAGE) (QUOTE FOR)) (AND (EQ (CADDDR 
MESSAGE) (QUOTE YOURSELF)) (AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE WHEN)) (AND (EQ (CADR 
(CDDDDR MESSAGE)) (QUOTE RECEIVING)) (CDDR (CDDDDR MESSAGE))))))) SOMETHING-DO-4)) ((AND 
(AND (EQ (CADR MESSAGE) (QUOTE WHEN)) (AND (EQ (CADDR MESSAGE) (QUOTE RECEIVING)) (CDDDR 
MESSAGE))) SOMETHING-DO-5)) ((AND (AND (EQ (CADR MESSAGE) (QUOTE THE)) (EQ (CADDR MESSAGE) 
(QUOTE FOLLOWING:))) SOMETHING-DO-57))))) ((AND (EQ (FIRST MESSAGE) (QUOTE 
INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)) (AND (NULL (REST MESSAGE)) (OR 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91) (OR (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92) (AND (EQ ACTOR :SELF) 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93))))))))))))))) ((AND (AND (EQ (FIRST 
MESSAGE) (QUOTE CHANGE)) (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADDDR MESSAGE) 
(QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE))))) SOMETHING-CHANGE-17)) ((AND (EQ (FIRST MESSAGE) 
(QUOTE TO)) SOMETHING-TO-18)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE INCREMENT)) (AND (EQ 
(CADR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADDDR MESSAGE) (QUOTE BY)) (ONE-LONG (CDDDDR 
MESSAGE))))) SOMETHING-INCREMENT-19)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE MULTIPLY)) (AND 
(EQ (CADR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADDDR MESSAGE) (QUOTE BY)) (ONE-LONG (CDDDDR 
MESSAGE))))) SOMETHING-MULTIPLY-20)) ((AND (EQ (FIRST MESSAGE) (QUOTE ADD)) (COND ((AND (EQ 
(CADDR MESSAGE) (QUOTE TO)) (AND (EQ (CADDDR MESSAGE) (QUOTE YOUR)) (AND (EQ (FIRST (CDDDDR 
MESSAGE)) (QUOTE LIST)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE OF)) (EQUAL (CDDDR (CDDDDR 
MESSAGE)) (QUOTE (REGARDLESS))))))) SOMETHING-ADD-22) ((AND (EQ (CADDR MESSAGE) (QUOTE TO)) 
(AND (EQ (CADDDR MESSAGE) (QUOTE YOUR)) (AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE LIST)) (AND 
(EQ (CADR (CDDDDR MESSAGE)) (QUOTE OF)) (ONE-LONG (CDDR (CDDDDR MESSAGE))))))) 
SOMETHING-ADD-21)))) ((AND (EQ (FIRST MESSAGE) (QUOTE REMOVE)) (COND ((AND (AND (EQ (CADDR 
MESSAGE) (QUOTE FROM)) (AND (EQ (CADDDR MESSAGE) (QUOTE YOUR)) (AND (EQ (FIRST (CDDDDR 
MESSAGE)) (QUOTE LIST)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE OF)) (ONE-LONG (CDDR (CDDDDR 
MESSAGE))))))) SOMETHING-REMOVE-23)) ((AND (AND (MEMQ (CADR MESSAGE) (QUOTE (METHOD 
CLAUSE))) (EQ (CADDR MESSAGE) (QUOTE FOR))) SOMETHING-REMOVE-63))))) ((AND (EQUAL MESSAGE 
(QUOTE (LIST ALL YOUR VARIABLE NAMES))) SOMETHING-LIST-24)) ((AND (EQ (FIRST MESSAGE) (QUOTE 
MAKE)) (COND ((AND (EQ (CADR MESSAGE) (QUOTE AN)) (COND ((AND (AND (EQ (CADDR MESSAGE) 
(QUOTE INSTANCE)) (AND (EQ (CADDDR MESSAGE) (QUOTE NAMED)) (AND (EQ (CADR (CDDDDR MESSAGE)) 
(QUOTE COPYING)) (ONE-LONG (CDDR (CDDDDR MESSAGE)))))) SOMETHING-MAKE-25)) ((AND (NULL (CDDR 
MESSAGE)) SOMETHING-MAKE-27))))) ((AND (NULL (REST MESSAGE)) SOMETHING-MAKE-26)) ((COND 
((AND (EQ (CADR MESSAGE) (QUOTE SYNONYM)) (ONE-LONG (CDDR MESSAGE))) SOMETHING-MAKE-32) 
((ONE-LONG (REST MESSAGE)) SOMETHING-MAKE-27))) ((AND (EQ (CADR MESSAGE) (QUOTE UNINTERNED)) 
(COND ((AND (EQ (CADDR MESSAGE) (QUOTE OFFSPRING)) (AND (NULL (CDDDR MESSAGE)) (OR 
SOMETHING-MAKE-28 SOMETHING-MAKE-32)))) ((AND (NULL (CDDR MESSAGE)) SOMETHING-MAKE-27)) 
((AND (ONE-LONG (CDDR MESSAGE)) SOMETHING-MAKE-32))))) ((AND (EQ (CADR MESSAGE) (QUOTE 
INTERNED)) (COND ((AND (EQ (CADDR MESSAGE) (QUOTE OFFSPRING)) (AND (NULL (CDDDR MESSAGE)) 
(OR SOMETHING-MAKE-29 SOMETHING-MAKE-32)))) ((AND (NULL (CDDR MESSAGE)) SOMETHING-MAKE-27)) 
((AND (ONE-LONG (CDDR MESSAGE)) SOMETHING-MAKE-32))))) ((AND (EQ (CADR MESSAGE) (QUOTE 
COPY)) (COND ((AND (ONE-LONG (CDDR MESSAGE)) (OR SOMETHING-MAKE-31 SOMETHING-MAKE-32))) 
((AND (NULL (CDDR MESSAGE)) SOMETHING-MAKE-27)))))))) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE 
IF)) (AND (EQ (CADR MESSAGE) (QUOTE NEW)) (AND (EQ (CADDR MESSAGE) (QUOTE MAKE)) (ONE-LONG 
(CDDDR MESSAGE))))) SOMETHING-IF-30)) ((AND (EQUAL MESSAGE (QUOTE (REMOB))) 
SOMETHING-REMOB-33)) ((AND (EQUAL MESSAGE (QUOTE (UNMAKE))) SOMETHING-UNMAKE-34)) ((AND (AND 
(EQ (FIRST MESSAGE) (QUOTE MEMORIZE)) (ONE-LONG (REST MESSAGE))) SOMETHING-MEMORIZE-35)) 
((AND (EQ (FIRST MESSAGE) (QUOTE COLLECT)) (AND (EQ (CADR MESSAGE) (QUOTE ITEMS)) (COND 
((AND (NULL (CDDR MESSAGE)) SOMETHING-COLLECT-36)) ((AND (AND (EQ (CADDR MESSAGE) (QUOTE 
MEMORIZED)) (AND (EQ (CADDDR MESSAGE) (QUOTE MATCHING)) (ONE-LONG (CDDDDR MESSAGE)))) 
SOMETHING-COLLECT-41)))))) ((AND (EQ (FIRST MESSAGE) (QUOTE FORGET)) (COND ((AND (AND (EQ 
(CADR MESSAGE) (QUOTE ITEM)) (ONE-LONG (CDDR MESSAGE))) SOMETHING-FORGET-37)) ((AND (AND (EQ 
(CADR MESSAGE) (QUOTE ITEMS)) (AND (EQ (CADDR MESSAGE) (QUOTE MATCHING)) (ONE-LONG (CDDDR 
MESSAGE)))) SOMETHING-FORGET-42)) ((AND (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (ONE-LONG 
(CDDR MESSAGE))) SOMETHING-FORGET-62))))) ((AND (EQUAL MESSAGE (QUOTE (TICK))) 
SOMETHING-TICK-43)) ((AND (EQ (FIRST MESSAGE) (QUOTE PLAN)) (COND ((AND (EQ (CADR MESSAGE) 
(QUOTE AFTER)) (COND ((COND ((AND (EQ (CADDR MESSAGE) (QUOTE RECEIVING)) (AND (EQ (FIRST 
(CDDDDR MESSAGE)) (QUOTE TO)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE ALWAYS)) (ONE-LONG 
(CDDR (CDDDDR MESSAGE)))))) SOMETHING-PLAN-48) ((AND (EQ (CADDR MESSAGE) (QUOTE RECEIVING)) 
(AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE TO)) (ONE-LONG (REST (CDDDDR MESSAGE))))) 
SOMETHING-PLAN-47) ((EQ (CADDDR MESSAGE) (QUOTE SECONDS)) SOMETHING-PLAN-46) ((EQ (CADDDR 
MESSAGE) (QUOTE TICKS)) SOMETHING-PLAN-44))) ((COND ((AND (EQ (CADDR MESSAGE) (QUOTE 
RECEIVING)) (AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE TO)) (AND (EQ (CADR (CDDDDR MESSAGE)) 
(QUOTE ALWAYS)) (ONE-LONG (CDDR (CDDDDR MESSAGE)))))) SOMETHING-PLAN-48) ((AND (EQ (CADDR 
MESSAGE) (QUOTE RECEIVING)) (AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE TO)) (ONE-LONG (REST 
(CDDDDR MESSAGE))))) SOMETHING-PLAN-47) ((EQ (CADDDR MESSAGE) (QUOTE SECONDS)) 
SOMETHING-PLAN-46)))))) ((AND (EQ (CADR MESSAGE) (QUOTE NEXT)) SOMETHING-PLAN-45))))) ((AND 
(EQ (FIRST MESSAGE) (QUOTE REPEAT)) (COND ((EQ (CADDDR MESSAGE) (QUOTE TIMES)) 
SOMETHING-REPEAT-51) ((AND (EQ (CADDDR MESSAGE) (QUOTE TIMES)) (AND (EQ (FIRST (CDDDDR 
MESSAGE)) (QUOTE EVERY)) (EQ (CADDR (CDDDDR MESSAGE)) (QUOTE TICKS)))) SOMETHING-REPEAT-50) 
((EQUAL (CDDR MESSAGE) (QUOTE (FOREVER))) SOMETHING-REPEAT-49)))) ((AND (EQ (FIRST MESSAGE) 
(QUOTE ASK)) (COND ((AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (COND ((CDDR MESSAGE) 
SOMETHING-ASK-52) (T SOMETHING-ASK-55)))) ((AND (EQ (CADR MESSAGE) (QUOTE EACH)) (COND ((AND 
(EQ (CADDR MESSAGE) (QUOTE OF)) (COND ((AND (EQ (CADDDR MESSAGE) (QUOTE YOUR)) (COND 
((CDDDDR MESSAGE) SOMETHING-ASK-53) (T SOMETHING-ASK-54)))) ((AND (CDDDR MESSAGE) 
SOMETHING-ASK-54))))) ((AND T SOMETHING-ASK-55))))) ((AND (REST MESSAGE) 
SOMETHING-ASK-55))))) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE KEEP)) (AND (EQ (CADR MESSAGE) 
(QUOTE DOING)) (AND (EQ (CADDR MESSAGE) (QUOTE UNTIL)) (CDDDR MESSAGE)))) 
SOMETHING-KEEP-56)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE ARE)) (AND (EQ (CADR MESSAGE) 
(QUOTE YOU)) (AND (MEMQ (CADDR MESSAGE) (QUOTE (A AN))) (ONE-LONG (CDDDR MESSAGE))))) 
SOMETHING-ARE-58)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE FIND)) (AND (EQ (CADR MESSAGE) 
(QUOTE ANCESTOR)) (AND (EQ (CADDR MESSAGE) (QUOTE MATCHING)) (ONE-LONG (CDDDR MESSAGE))))) 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59)) ((AND (EQ (FIRST MESSAGE) (QUOTE TRACE)) 
SOMETHING-TRACE-64)) ((AND (EQ (FIRST MESSAGE) (QUOTE UNTRACE)) (COND ((AND (ONE-LONG (REST 
MESSAGE)) SOMETHING-UNTRACE-65)) ((AND (NULL (REST MESSAGE)) SOMETHING-UNTRACE-66))))) ((AND 
(EQ (FIRST MESSAGE) (QUOTE TRANSMISSION)) (COND ((AND (EQ (CADDR MESSAGE) (QUOTE RETURNING)) 
(ONE-LONG (CDDDR MESSAGE))) SOMETHING-TRANSMISSION-68) ((EQUAL (CDDR MESSAGE) (QUOTE 
(BEGINNING))) SOMETHING-TRANSMISSION-67)))) ((AND (EQ (FIRST MESSAGE) (QUOTE TELL)) (COND 
((AND (AND (EQ (CADR MESSAGE) (QUOTE EACH)) (AND (EQ (CADDR MESSAGE) (QUOTE OF)) (AND (EQ 
(CADDDR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE WHENEVER)) (AND (EQ 
(CADDR (CDDDDR MESSAGE)) (QUOTE YOUR)) (EQUAL (CDDDDR (CDDDDR MESSAGE)) (QUOTE (IS 
CHANGED)))))))) SOMETHING-TELL-69)) ((AND (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (AND (EQ 
(CADDDR MESSAGE) (QUOTE WHENEVER)) (AND (EQ (FIRST (CDDDDR MESSAGE)) (QUOTE YOUR)) (EQUAL 
(CDDR (CDDDDR MESSAGE)) (QUOTE (IS CHANGED)))))) SOMETHING-TELL-70))))) ((AND (AND (EQ 
(FIRST MESSAGE) (QUOTE NOTICE)) (AND (EQ (CADR MESSAGE) (QUOTE THAT)) (AND (EQ (CADDDR 
MESSAGE) (QUOTE OF)) (AND (EQ (CADR (CDDDDR MESSAGE)) (QUOTE IS)) (AND (EQ (CADDR (CDDDDR 
MESSAGE)) (QUOTE NOW)) (ONE-LONG (CDDDR (CDDDDR MESSAGE)))))))) SOMETHING-NOTICE-71)) ((AND 
(EQUAL MESSAGE (QUOTE (ABSORB YOUR PARTS))) SOMETHING-ABSORB-72)) ((AND (EQ (FIRST MESSAGE) 
(QUOTE PRINT)) SOMETHING-PRINT-73)) ((AND (AND (EQ (FIRST MESSAGE) (QUOTE COMPARE)) (AND (EQ 
(CADR MESSAGE) (QUOTE YOURSELF)) (AND (EQ (CADDR MESSAGE) (QUOTE WITH)) (ONE-LONG (CDDDR 
MESSAGE))))) SOMETHING-COMPARE-74)) ((AND (EQ (FIRST MESSAGE) (QUOTE COMPILE)) (COND ((AND 
(EQ (CADR MESSAGE) (QUOTE MESSAGE)) SOMETHING-COMPILE-75)) ((AND T SOMETHING-COMPILE-76))))) 
((AND (EQ (FIRST MESSAGE) (QUOTE SAVE)) SOMETHING-SAVE-77)) ((AND (EQ (FIRST MESSAGE) (QUOTE 
HELP)) SOMETHING-HELP-78)) ((AND (EQ (FIRST MESSAGE) (QUOTE WARNING)) SOMETHING-WARNING-79)) 
((AND (AND (EQ (FIRST MESSAGE) (QUOTE SHOULD)) (AND (EQ (CADR MESSAGE) (QUOTE NOT)) (EQ 
(CADDR MESSAGE) (QUOTE HAPPEN)))) SOMETHING-SHOULD-80)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 93 SOMETHING-RECALL-1 
(ORIGINAL-METHODS-OF-SOMETHING SOMETHING-SET-84 SOMETHING-RECALL-83 SOMETHING-RECALL-2 
SOMETHING-DO-3 SOMETHING-DO-4 SOMETHING-DO-5 SOMETHING-RECALL-6 SOMETHING-RECALL-7 
SOMETHING-RECALL-8 SOMETHING-RECALL-9 SOMETHING-RECALL-10 SOMETHING-RECALL-11 
SOMETHING-SET-12 SOMETHING-SET-13 SOMETHING-SET-14 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 SOMETHING-RECALL-16 SOMETHING-CHANGE-17 
SOMETHING-TO-18 SOMETHING-INCREMENT-19 SOMETHING-MULTIPLY-20 SOMETHING-ADD-21 
SOMETHING-ADD-22 SOMETHING-REMOVE-23 SOMETHING-LIST-24 SOMETHING-MAKE-25 SOMETHING-MAKE-26 
SOMETHING-MAKE-27 SOMETHING-MAKE-28 SOMETHING-MAKE-29 SOMETHING-IF-30 SOMETHING-MAKE-31 
SOMETHING-MAKE-32 SOMETHING-REMOB-33 SOMETHING-UNMAKE-34 SOMETHING-MEMORIZE-35 
SOMETHING-COLLECT-36 SOMETHING-FORGET-37 SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38 
SOMETHING-RECALL-39 SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40 SOMETHING-COLLECT-41 
SOMETHING-FORGET-42 SOMETHING-TICK-43 SOMETHING-PLAN-44 SOMETHING-PLAN-45 SOMETHING-PLAN-46 
SOMETHING-PLAN-47 SOMETHING-PLAN-48 SOMETHING-REPEAT-49 SOMETHING-REPEAT-50 
SOMETHING-REPEAT-51 SOMETHING-ASK-52 SOMETHING-ASK-53 SOMETHING-ASK-54 SOMETHING-ASK-55 
SOMETHING-KEEP-56 SOMETHING-DO-57 SOMETHING-ARE-58 
SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-59 SOMETHING-RECALL-60 SOMETHING-RECALL-61 
SOMETHING-FORGET-62 SOMETHING-REMOVE-63 SOMETHING-TRACE-64 SOMETHING-UNTRACE-65 
SOMETHING-UNTRACE-66 SOMETHING-TRANSMISSION-67 SOMETHING-TRANSMISSION-68 SOMETHING-TELL-69 
SOMETHING-TELL-70 SOMETHING-NOTICE-71 SOMETHING-ABSORB-72 SOMETHING-PRINT-73 
SOMETHING-COMPARE-74 SOMETHING-COMPILE-75 SOMETHING-COMPILE-76 SOMETHING-SAVE-77 
SOMETHING-HELP-78 SOMETHING-WARNING-79 SOMETHING-SHOULD-80 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93))) (QUOTE SOMETHING)) 
(REMPROP (QUOTE SOMETHING) (QUOTE ACTOR-LOAD)) 
(DECLARE (SPECIAL UNIVERSE-RECALL-1 UNIVERSE-SET-7 UNIVERSE-RECALL-6 UNIVERSE-RECALL-2 
UNIVERSE-TICK-3 UNIVERSE-RUN-4 UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-5)) 
(SETQ UNIVERSE-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE SOMETHING))) 
(DEFPROP UNIVERSE-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ UNIVERSE-SET-7 (QUOTE UNIVERSE-SET-7)) 
(DEFPROP UNIVERSE-SET-7 (SET YOUR OFFSPRING TO ?) METHOD-PATTERN) 
(DEFPROP UNIVERSE-SET-7 T PRIVATE?) 
(DEFUN UNIVERSE-SET-7 NIL ((LAMBDA (THE-NEW-VALUE) (SET-DIRECTOR-SYMBOL-FOR-VALUE 
UNIVERSE-RECALL-6 THE-NEW-VALUE)) (FIRST (CDDDDR :MESSAGE)))) 
(SETQ UNIVERSE-RECALL-6 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE NIL))) 
(DEFPROP UNIVERSE-RECALL-6 (RECALL YOUR OFFSPRING) METHOD-PATTERN) 
(DEFPROP UNIVERSE-RECALL-6 T PRIVATE?) 
(SETQ UNIVERSE-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE UNIVERSE))) 
(DEFPROP UNIVERSE-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(SETQ UNIVERSE-TICK-3 (QUOTE UNIVERSE-TICK-3)) 
(DEFPROP UNIVERSE-TICK-3 (TICK) METHOD-PATTERN) 
(DEFUN UNIVERSE-TICK-3 NIL (LET ((:MESSAGE (QUOTE (TICK)))) (SKIP-TYPE-COMPILED-ASK (QUOTE 
|UNIVERSE(TICK)|) (QUOTE UNIVERSE) T)) (LET ((ACTORS-TO-RUN (LET ((:MESSAGE (QUOTE (RECALL 
YOUR ACTORS-TO-RUN-NEXT)))) (COMPILED-ASK (QUOTE |UNIVERSE(RECALL YOUR ACTORS-TO-RUN-NEXT)|) 
(QUOTE UNIVERSE))))) (UNWIND-PROTECT (PROGN (LET ((:MESSAGE (QUOTE (SET YOUR 
ACTORS-TO-RUN-NEXT TO NIL)))) (COMPILED-ASK (QUOTE 
|UNIVERSE(SET YOUR ACTORS-TO-RUN-NEXT TO NIL)|) (QUOTE UNIVERSE))) (MAPCAR (FUNCTION (LAMBDA 
(ACTOR) (LET ((:SELF (ACTOR-OF ACTOR)) (:MESSAGE (QUOTE (TICK)))) (COMPILED-ASK (QUOTE 
|UNIVERSE(TICK)|) (QUOTE UNIVERSE))))) ACTORS-TO-RUN)) (LET ((:MESSAGE (CONS (QUOTE SET) 
(CONS (QUOTE YOUR) (CONS (QUOTE ACTORS-TO-RUN-NEXT) (CONS (QUOTE TO) (CONS ACTORS-TO-RUN 
NIL))))))) (COMPILED-ASK (QUOTE |UNIVERSE(SET YOUR ACTORS-TO-RUN-NEXT TO ?)|) (QUOTE 
UNIVERSE)))))) 
(SETQ UNIVERSE-RUN-4 (QUOTE UNIVERSE-RUN-4)) 
(DEFPROP UNIVERSE-RUN-4 (RUN FOR ? TICKS) METHOD-PATTERN) 
(DEFUN UNIVERSE-RUN-4 NIL ((LAMBDA (NUMBER) (LET ((:MESSAGE (QUOTE (TICK)))) (COMPILED-ASK 
(QUOTE |UNIVERSE(TICK)|) (QUOTE UNIVERSE))) (COND ((AND (FIXP NUMBER) (> NUMBER 1)) (LET 
((:MESSAGE (CONS (QUOTE RUN) (CONS (QUOTE FOR) (CONS (1- NUMBER) (QUOTE (TICKS))))))) 
(COMPILED-ASK (QUOTE |UNIVERSE(RUN FOR ? TICKS)|) (QUOTE UNIVERSE)))))) (CADDR :MESSAGE))) 
(SETQ UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-5 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE 
(NIL)))) 
(DEFPROP UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-5 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-5 T PRIVATE?) 
(DEFUN ORIGINAL-METHODS-OF-UNIVERSE (MESSAGE ACTOR) (COND ((AND (AND (EQ (FIRST MESSAGE) 
(QUOTE SET)) (AND (EQ (CADR MESSAGE) (QUOTE YOUR)) (AND (EQ (CADDR MESSAGE) (QUOTE 
OFFSPRING)) (AND (EQ (CADDDR MESSAGE) (QUOTE TO)) (ONE-LONG (CDDDDR MESSAGE)))))) (AND (EQ 
ACTOR :SELF) UNIVERSE-SET-7))) ((AND (EQ (FIRST MESSAGE) (QUOTE RECALL)) (AND (EQ (CADR 
MESSAGE) (QUOTE YOUR)) (COND ((AND (EQUAL (CDDR MESSAGE) (QUOTE (OFFSPRING))) (AND (EQ ACTOR 
:SELF) UNIVERSE-RECALL-6))) ((AND (EQUAL (CDDR MESSAGE) (QUOTE (NAME))) 
UNIVERSE-RECALL-2)))))) ((AND (EQUAL MESSAGE (QUOTE (TICK))) UNIVERSE-TICK-3)) ((AND (AND 
(EQ (FIRST MESSAGE) (QUOTE RUN)) (AND (EQ (CADR MESSAGE) (QUOTE FOR)) (EQUAL (CDDDR MESSAGE) 
(QUOTE (TICKS))))) UNIVERSE-RUN-4)) ((AND (EQUAL MESSAGE (QUOTE 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-5))))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 7 UNIVERSE-RECALL-1 
(ORIGINAL-METHODS-OF-UNIVERSE UNIVERSE-SET-7 UNIVERSE-RECALL-6 UNIVERSE-RECALL-2 
UNIVERSE-TICK-3 UNIVERSE-RUN-4 UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-5))) (QUOTE 
UNIVERSE)) 
(REMPROP (QUOTE UNIVERSE) (QUOTE ACTOR-LOAD)) 
(ASK SOMETHING ADD UNIVERSE TO YOUR LIST OF OFFSPRING) 
(DECLARE (SPECIAL DEFAULT-UNIVERSE-RECALL-1 
DEFAULT-UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 DEFAULT-UNIVERSE-RECALL-2)) 
(SETQ DEFAULT-UNIVERSE-RECALL-1 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE UNIVERSE))) 
(DEFPROP DEFAULT-UNIVERSE-RECALL-1 (RECALL YOUR PARENT) METHOD-PATTERN) 
(SETQ DEFAULT-UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 (QUOTE 
(DIRECTOR-SYMBOL-FOR-VALUE (NIL)))) 
(DEFPROP DEFAULT-UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 
(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) METHOD-PATTERN) 
(DEFPROP DEFAULT-UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 T PRIVATE?) 
(SETQ DEFAULT-UNIVERSE-RECALL-2 (QUOTE (DIRECTOR-SYMBOL-FOR-VALUE DEFAULT-UNIVERSE))) 
(DEFPROP DEFAULT-UNIVERSE-RECALL-2 (RECALL YOUR NAME) METHOD-PATTERN) 
(DEFUN ORIGINAL-METHODS-OF-DEFAULT-UNIVERSE (MESSAGE ACTOR) (COND ((AND (EQUAL MESSAGE 
(QUOTE (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE))) (AND (EQ ACTOR :SELF) 
DEFAULT-UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3))) ((AND (EQUAL MESSAGE (QUOTE 
(RECALL YOUR NAME))) DEFAULT-UNIVERSE-RECALL-2)))) 
(PLACE-ACTOR-ON-NAME (QUOTE (DIRECTOR-SYMBOL-FOR-ACTOR 3 DEFAULT-UNIVERSE-RECALL-1 
(ORIGINAL-METHODS-OF-DEFAULT-UNIVERSE 
DEFAULT-UNIVERSE-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-3 DEFAULT-UNIVERSE-RECALL-2))) (QUOTE 
DEFAULT-UNIVERSE)) 
(REMPROP (QUOTE DEFAULT-UNIVERSE) (QUOTE ACTOR-LOAD)) 
(ASK UNIVERSE ADD DEFAULT-UNIVERSE TO YOUR LIST OF OFFSPRING) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE SOMETHING) (QUOTE |DSK:KEN;SOME DEPEND|)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR OFFSPRING)| (SOMETHING-RECALL-83 SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SOMETHING(RECALL YOUR OFFSPRING)| (RECALL YOUR OFFSPRING) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR PARENT)| (SOMETHING-RECALL-1 SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SOMETHING(RECALL YOUR PARENT)| (RECALL YOUR PARENT) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR DESCENDANTS)| (SOMETHING-RECALL-7 
SOMETHING-RECALL-16) MATCHING-METHODS) (DEFPROP |SOMETHING(RECALL YOUR DESCENDANTS)| (RECALL 
YOUR DESCENDANTS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR CHILDLESS-DESCENDANTS)| (SOMETHING-RECALL-8 
SOMETHING-RECALL-16) MATCHING-METHODS) (DEFPROP 
|SOMETHING(RECALL YOUR CHILDLESS-DESCENDANTS)| (RECALL YOUR CHILDLESS-DESCENDANTS) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR PRIVATE-VARIABLE-NAMES)| (SOMETHING-RECALL-11 
SOMETHING-RECALL-16) MATCHING-METHODS) (DEFPROP 
|SOMETHING(RECALL YOUR PRIVATE-VARIABLE-NAMES)| (RECALL YOUR PRIVATE-VARIABLE-NAMES) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR ?)| (SOMETHING-RECALL-1 SOMETHING-RECALL-83 
SOMETHING-RECALL-2 SOMETHING-RECALL-6 SOMETHING-RECALL-7 SOMETHING-RECALL-8 
SOMETHING-RECALL-9 SOMETHING-RECALL-10 SOMETHING-RECALL-11 SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SOMETHING(RECALL YOUR ?)| (RECALL YOUR ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)| 
(SOMETHING-RECALL-16) MATCHING-METHODS) (DEFPROP 
|SOMETHING(RECALL YOUR VARIABLES-TO-COPY-UPON-CREATION)| (RECALL YOUR 
VARIABLES-TO-COPY-UPON-CREATION) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR THINGS-TO-DO-NEXT)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SOMETHING(RECALL YOUR THINGS-TO-DO-NEXT)| (RECALL YOUR 
THINGS-TO-DO-NEXT) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR WHOLE)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |SOMETHING(RECALL YOUR WHOLE)| (RECALL YOUR WHOLE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL AN ITEM MATCHING ? THEN T)| 
(SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-38) MATCHING-METHODS) (DEFPROP 
|SOMETHING(RECALL AN ITEM MATCHING ? THEN T)| (RECALL AN ITEM MATCHING ? THEN T) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL EACH ITEM MATCHING {and ?THE-ITEM ?} THEN THE-ITEM)| 
(SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40) MATCHING-METHODS) (DEFPROP 
|SOMETHING(RECALL EACH ITEM MATCHING {and ?THE-ITEM ?} THEN THE-ITEM)| (RECALL EACH ITEM 
MATCHING (DIRECTOR-SYMBOL-FOR-AND-PATTERN ?THE-ITEM ?) THEN THE-ITEM) MESSAGE-PATTERN)) 
(PROGN (DEFPROP 
|SOMETHING(RECALL EACH ITEM MATCHING {and ?THE-ITEM ?} THEN (SCRIPT: (ASK :SELF FORGET ITEM ?)
))| (SOMETHING-DIRECTOR-SYMBOL-FOR-AND-PATTERN-40) MATCHING-METHODS) (DEFPROP 
|SOMETHING(RECALL EACH ITEM MATCHING {and ?THE-ITEM ?} THEN (SCRIPT: (ASK :SELF FORGET ITEM ?)
))| (RECALL EACH ITEM MATCHING (DIRECTOR-SYMBOL-FOR-AND-PATTERN ?THE-ITEM ?) THEN (SCRIPT: 
(ASK :SELF FORGET ITEM ?))) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR UNIVERSE)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |SOMETHING(RECALL YOUR UNIVERSE)| (RECALL YOUR UNIVERSE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR PARTS)| (SOMETHING-RECALL-16) MATCHING-METHODS) 
(DEFPROP |SOMETHING(RECALL YOUR PARTS)| (RECALL YOUR PARTS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(RECALL YOUR HELP-LOADED-FOR)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |SOMETHING(RECALL YOUR HELP-LOADED-FOR)| (RECALL YOUR 
HELP-LOADED-FOR) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK EACH OF YOUR ? NOTICE THAT ? OF ? IS NOW ?)| 
(SOMETHING-ASK-53 SOMETHING-ASK-54 SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK EACH OF YOUR ? NOTICE THAT ? OF ? IS NOW ?)| (ASK EACH OF YOUR ? NOTICE THAT 
? OF ? IS NOW ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK YOUR ? NOTICE THAT ? OF ? IS NOW ?)| (SOMETHING-ASK-52 
SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK YOUR ? NOTICE THAT ? OF ? IS NOW ?)| (ASK YOUR ? NOTICE THAT ? OF ? IS NOW ?) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK YOUR PARENT TO MAKE ?)| (SOMETHING-ASK-52 SOMETHING-ASK-55) 
MATCHING-METHODS) (DEFPROP |SOMETHING(ASK YOUR PARENT TO MAKE ?)| (ASK YOUR PARENT TO MAKE 
?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK YOUR PARENT REMOVE ? FROM YOUR LIST OF OFFSPRING)| 
(SOMETHING-ASK-52 SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK YOUR PARENT REMOVE ? FROM YOUR LIST OF OFFSPRING)| (ASK YOUR PARENT REMOVE ? 
FROM YOUR LIST OF OFFSPRING) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK YOUR PARENT TO REMOVE ? FROM YOUR LIST OF OFFSPRING)| 
(SOMETHING-ASK-52 SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK YOUR PARENT TO REMOVE ? FROM YOUR LIST OF OFFSPRING)| (ASK YOUR PARENT TO 
REMOVE ? FROM YOUR LIST OF OFFSPRING) MESSAGE-PATTERN)) 
(PROGN (DEFPROP 
|SOMETHING(ASK YOUR UNIVERSE TO REMOVE ? FROM YOUR LIST OF ACTORS-TO-RUN-NEXT)| 
(SOMETHING-ASK-52 SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK YOUR UNIVERSE TO REMOVE ? FROM YOUR LIST OF ACTORS-TO-RUN-NEXT)| (ASK YOUR 
UNIVERSE TO REMOVE ? FROM YOUR LIST OF ACTORS-TO-RUN-NEXT) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK EACH OF YOUR PARTS TO UNMAKE)| (SOMETHING-ASK-53 
SOMETHING-ASK-54 SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK EACH OF YOUR PARTS TO UNMAKE)| (ASK EACH OF YOUR PARTS TO UNMAKE) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK YOUR PARENT %)| (SOMETHING-ASK-52 SOMETHING-ASK-55) 
MATCHING-METHODS) (DEFPROP |SOMETHING(ASK YOUR PARENT %)| (ASK YOUR PARENT %) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ASK YOUR ? TO NOTICE THAT ? OF ? IS NOW ?)| (SOMETHING-ASK-52 
SOMETHING-ASK-55) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ASK YOUR ? TO NOTICE THAT ? OF ? IS NOW ?)| (ASK YOUR ? TO NOTICE THAT ? OF ? IS 
NOW ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)| 
(SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-15 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-81 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-82 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-85 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-86 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-87 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-88 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-89 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-90 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-91 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-92 
SOMETHING-INTERNAL-RECALL-YOUR-NORMAL-VARIABLE-93) MATCHING-METHODS) (DEFPROP 
|SOMETHING(INTERNAL-RECALL-YOUR-NORMAL-VARIABLE)| (INTERNAL-RECALL-YOUR-NORMAL-VARIABLE) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR ? TO ?)| (SOMETHING-SET-84 SOMETHING-SET-12 
SOMETHING-SET-13 SOMETHING-SET-14) MATCHING-METHODS) (DEFPROP |SOMETHING(SET YOUR ? TO ?)| 
(SET YOUR ? TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR PARENT TO ?)| (SOMETHING-SET-12 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |SOMETHING(SET YOUR PARENT TO ?)| (SET YOUR PARENT TO ?) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR NAME TO ?)| (SOMETHING-SET-13 SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |SOMETHING(SET YOUR NAME TO ?)| (SET YOUR NAME TO ?) 
MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR THINGS-TO-DO-NEXT TO NIL)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |SOMETHING(SET YOUR THINGS-TO-DO-NEXT TO NIL)| (SET YOUR 
THINGS-TO-DO-NEXT TO NIL) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR THINGS-TO-DO-NEXT TO (?))| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |SOMETHING(SET YOUR THINGS-TO-DO-NEXT TO (?))| (SET YOUR 
THINGS-TO-DO-NEXT TO (?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR PARTS TO ?)| (SOMETHING-SET-14) MATCHING-METHODS) 
(DEFPROP |SOMETHING(SET YOUR PARTS TO ?)| (SET YOUR PARTS TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(SET YOUR HELP-LOADED-FOR TO ?)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |SOMETHING(SET YOUR HELP-LOADED-FOR TO ?)| (SET YOUR 
HELP-LOADED-FOR TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MAKE AN INSTANCE NAMED NIL COPYING ?)| (SOMETHING-MAKE-25) 
MATCHING-METHODS) (DEFPROP |SOMETHING(MAKE AN INSTANCE NAMED NIL COPYING ?)| (MAKE AN 
INSTANCE NAMED NIL COPYING ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MAKE AN INSTANCE NAMED ? COPYING ?)| (SOMETHING-MAKE-25) 
MATCHING-METHODS) (DEFPROP |SOMETHING(MAKE AN INSTANCE NAMED ? COPYING ?)| (MAKE AN INSTANCE 
NAMED ? COPYING ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MAKE ?)| (SOMETHING-MAKE-27) MATCHING-METHODS) (DEFPROP 
|SOMETHING(MAKE ?)| (MAKE ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MAKE)| (SOMETHING-MAKE-26) MATCHING-METHODS) (DEFPROP 
|SOMETHING(MAKE)| (MAKE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MAKE (COMPARISON-BETWEEN ? ?))| (SOMETHING-MAKE-27) 
MATCHING-METHODS) (DEFPROP |SOMETHING(MAKE (COMPARISON-BETWEEN ? ?))| (MAKE 
(COMPARISON-BETWEEN ? ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(UNMAKE)| (SOMETHING-UNMAKE-34) MATCHING-METHODS) (DEFPROP 
|SOMETHING(UNMAKE)| (UNMAKE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF OFFSPRING)| (SOMETHING-ADD-21) 
MATCHING-METHODS) (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF OFFSPRING)| (ADD ? TO YOUR LIST 
OF OFFSPRING) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF SYNONYMS)| (SOMETHING-ADD-21) 
MATCHING-METHODS) (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF SYNONYMS)| (ADD ? TO YOUR LIST 
OF SYNONYMS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF ACTORS-TO-RUN-NEXT)| (SOMETHING-ADD-21) 
MATCHING-METHODS) (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF ACTORS-TO-RUN-NEXT)| (ADD ? TO 
YOUR LIST OF ACTORS-TO-RUN-NEXT) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(ADD ? TO YOUR LIST OF (VARIABLES-DEPENDED-UPON-BY ?))| 
(SOMETHING-ADD-21) MATCHING-METHODS) (DEFPROP 
|SOMETHING(ADD ? TO YOUR LIST OF (VARIABLES-DEPENDED-UPON-BY ?))| (ADD ? TO YOUR LIST OF 
(VARIABLES-DEPENDED-UPON-BY ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(REMOVE ? FROM YOUR LIST OF PARTS)| (SOMETHING-REMOVE-23) 
MATCHING-METHODS) (DEFPROP |SOMETHING(REMOVE ? FROM YOUR LIST OF PARTS)| (REMOVE ? FROM YOUR 
LIST OF PARTS) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(REMOVE CLAUSE FOR RECALL YOUR ?)| (SOMETHING-REMOVE-63) 
MATCHING-METHODS) (DEFPROP |SOMETHING(REMOVE CLAUSE FOR RECALL YOUR ?)| (REMOVE CLAUSE FOR 
RECALL YOUR ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(REMOVE CLAUSE FOR SET YOUR ? TO ANYTHING)| (SOMETHING-REMOVE-63) 
MATCHING-METHODS) (DEFPROP |SOMETHING(REMOVE CLAUSE FOR SET YOUR ? TO ANYTHING)| (REMOVE 
CLAUSE FOR SET YOUR ? TO ANYTHING) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(UNTRACE)| (SOMETHING-UNTRACE-66) MATCHING-METHODS) (DEFPROP 
|SOMETHING(UNTRACE)| (UNTRACE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(DO THE FOLLOWING: %)| (SOMETHING-DO-57) MATCHING-METHODS) 
(DEFPROP |SOMETHING(DO THE FOLLOWING: %)| (DO THE FOLLOWING: %) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(PLAN AFTER 1 TICKS DIRECTOR-SYMBOL-FOR-EVAL MESSAGE)| 
(SOMETHING-PLAN-44) MATCHING-METHODS) (DEFPROP 
|SOMETHING(PLAN AFTER 1 TICKS DIRECTOR-SYMBOL-FOR-EVAL MESSAGE)| (PLAN AFTER 1 TICKS 
DIRECTOR-SYMBOL-FOR-EVAL MESSAGE) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(PLAN AFTER ? TICKS %)| (SOMETHING-PLAN-44 SOMETHING-PLAN-47 
SOMETHING-PLAN-48) MATCHING-METHODS) (DEFPROP |SOMETHING(PLAN AFTER ? TICKS %)| (PLAN AFTER 
? TICKS %) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(PLAN NEXT REPEAT ? FOREVER)| (SOMETHING-PLAN-45) 
MATCHING-METHODS) (DEFPROP |SOMETHING(PLAN NEXT REPEAT ? FOREVER)| (PLAN NEXT REPEAT ? 
FOREVER) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(PLAN AFTER ? TICKS REPEAT ? ? TIMES EVERY ? TICKS %)| 
(SOMETHING-PLAN-44) MATCHING-METHODS) (DEFPROP 
|SOMETHING(PLAN AFTER ? TICKS REPEAT ? ? TIMES EVERY ? TICKS %)| (PLAN AFTER ? TICKS REPEAT 
? ? TIMES EVERY ? TICKS %) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(PLAN NEXT REPEAT ? ? TIMES %)| (SOMETHING-PLAN-45) 
MATCHING-METHODS) (DEFPROP |SOMETHING(PLAN NEXT REPEAT ? ? TIMES %)| (PLAN NEXT REPEAT ? ? 
TIMES %) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(LIST ALL YOUR VARIABLE NAMES)| (SOMETHING-LIST-24) 
MATCHING-METHODS) (DEFPROP |SOMETHING(LIST ALL YOUR VARIABLE NAMES)| (LIST ALL YOUR VARIABLE 
NAMES) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(FORGET YOUR ?)| (SOMETHING-FORGET-62) MATCHING-METHODS) (DEFPROP 
|SOMETHING(FORGET YOUR ?)| (FORGET YOUR ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(REMOB)| (SOMETHING-REMOB-33) MATCHING-METHODS) (DEFPROP 
|SOMETHING(REMOB)| (REMOB) MESSAGE-PATTERN)) 
(PROGN (DEFPROP 
|SOMETHING(MEMORIZE (DIFFERENCE: TYPE VARIABLE VARIABLE ? (? VALUE) ? (? VALUE) ?))| 
(SOMETHING-MEMORIZE-35) MATCHING-METHODS) (DEFPROP 
|SOMETHING(MEMORIZE (DIFFERENCE: TYPE VARIABLE VARIABLE ? (? VALUE) ? (? VALUE) ?))| 
(MEMORIZE (DIFFERENCE: TYPE VARIABLE VARIABLE ? (? VALUE) ? (? VALUE) ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MEMORIZE (DIFFERENCE: TYPE EXISTENCE WHO-EXISTS ? WHO-DOESNT ?))| 
(SOMETHING-MEMORIZE-35) MATCHING-METHODS) (DEFPROP 
|SOMETHING(MEMORIZE (DIFFERENCE: TYPE EXISTENCE WHO-EXISTS ? WHO-DOESNT ?))| (MEMORIZE 
(DIFFERENCE: TYPE EXISTENCE WHO-EXISTS ? WHO-DOESNT ?)) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(MEMORIZE ?)| (SOMETHING-MEMORIZE-35) MATCHING-METHODS) (DEFPROP 
|SOMETHING(MEMORIZE ?)| (MEMORIZE ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |SOMETHING(COLLECT ITEMS MEMORIZED MATCHING (When receiving ? I %))| 
(SOMETHING-COLLECT-41) MATCHING-METHODS) (DEFPROP 
|SOMETHING(COLLECT ITEMS MEMORIZED MATCHING (When receiving ? I %))| (COLLECT ITEMS 
MEMORIZED MATCHING (|When receiving| ? I %)) MESSAGE-PATTERN)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE UNIVERSE) (QUOTE |DSK:KEN;SOME DEPEND|)) 
(PROGN (DEFPROP |UNIVERSE(TICK)| (UNIVERSE-TICK-3 SOMETHING-TICK-43) MATCHING-METHODS) 
(DEFPROP |UNIVERSE(TICK)| (TICK) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |UNIVERSE(RECALL YOUR ACTORS-TO-RUN-NEXT)| (SOMETHING-RECALL-16) 
MATCHING-METHODS) (DEFPROP |UNIVERSE(RECALL YOUR ACTORS-TO-RUN-NEXT)| (RECALL YOUR 
ACTORS-TO-RUN-NEXT) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |UNIVERSE(SET YOUR ACTORS-TO-RUN-NEXT TO NIL)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |UNIVERSE(SET YOUR ACTORS-TO-RUN-NEXT TO NIL)| (SET YOUR 
ACTORS-TO-RUN-NEXT TO NIL) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |UNIVERSE(SET YOUR ACTORS-TO-RUN-NEXT TO ?)| (SOMETHING-SET-14) 
MATCHING-METHODS) (DEFPROP |UNIVERSE(SET YOUR ACTORS-TO-RUN-NEXT TO ?)| (SET YOUR 
ACTORS-TO-RUN-NEXT TO ?) MESSAGE-PATTERN)) 
(PROGN (DEFPROP |UNIVERSE(RUN FOR ? TICKS)| (UNIVERSE-RUN-4) MATCHING-METHODS) (DEFPROP 
|UNIVERSE(RUN FOR ? TICKS)| (RUN FOR ? TICKS) MESSAGE-PATTERN)) 
(PUT-DEPENDENT-COMPILED-TRANSMISSIONS (QUOTE DEFAULT-UNIVERSE) (QUOTE |DSK:KEN;SOME DEPEND|)) 